// src/svelte/ArcanaInputMask.svelte
<script lang="ts">
  /**
   * `<ArcanaInputMask>` — Svelte 5 port. Input mascarado shadcn (`class="arcana-input"` +
   * `arcana-input--${size}`/`--disabled`), idêntico ao SFC.
   *
   * Decisão sobre a máscara (parity com React/Angular): o SFC usa a diretiva `v-maska`,
   * inexistente fora do Vue. Em vez de reimplementar a máscara, reusamos as funções CORE
   * da lib `maska` (`mask`/`tokens`), agnósticas de framework:
   *   - display formatado   = `mask(raw, maskStr, tokens)`         (masked = true)
   *   - raw sem separadores = `mask(raw, maskStr, tokens, false)`  (masked = false)
   * O `false` no 4º arg devolve o mesmo `maskRawValue` da diretiva → valor emitido idêntico.
   *
   * Equivalências: `modelValue` → `value` + `onValueChange` (sempre o raw);
   * `emit('blur'|'focus')` → `onBlur`/`onFocus`; watch(modelValue) → `$effect`.
   */
  import { untrack } from "svelte";
  import { mask as maskaMask, tokens as maskaTokens } from "maska";

  let {
    value = "",
    mask,
    placeholder = "",
    disabled = false,
    readonly = false,
    name,
    size = "md",
    onValueChange,
    onBlur,
    onFocus,
    class: className = "",
  }: {
    value?: string | number | null;
    mask: string | string[];
    placeholder?: string;
    disabled?: boolean;
    readonly?: boolean;
    name?: string;
    size?: "sm" | "md" | "lg";
    onValueChange?: (value: string) => void;
    onBlur?: (ev: FocusEvent) => void;
    onFocus?: (ev: FocusEvent) => void;
    class?: string;
  } = $props();

  // `maska` aceita string única ou array stringificado (máscara dinâmica por tamanho).
  const maskStr = $derived(Array.isArray(mask) ? JSON.stringify(mask) : mask);

  // `tempValue` (display mascarado) ≠ raw emitido — igual ao SFC.
  let tempValue = $state(value ? maskaMask(String(value), maskStr, maskaTokens) : "");

  // Re-aplica a máscara quando o pai muda `value` (load/reset). Compara com o raw atual
  // do display pra evitar reformatar durante a própria digitação.
  $effect(() => {
    const incoming = value == null ? "" : String(value);
    const ms = maskStr;
    untrack(() => {
      const currentRaw = tempValue ? maskaMask(tempValue, ms, maskaTokens, false) : "";
      if (incoming !== currentRaw) {
        tempValue = incoming ? maskaMask(incoming, ms, maskaTokens) : "";
      }
    });
  });

  const rootClasses = $derived(
    [
      "arcana-input",
      `arcana-input--${size}`,
      disabled ? "arcana-input--disabled" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );

  function onInput(e: Event) {
    const typed = (e.target as HTMLInputElement).value;
    const display = maskaMask(typed, maskStr, maskaTokens);
    const raw = maskaMask(typed, maskStr, maskaTokens, false);
    tempValue = display;
    onValueChange?.(raw);
  }
</script>

<input
  class={rootClasses}
  {placeholder}
  {disabled}
  {readonly}
  {name}
  value={tempValue}
  oninput={onInput}
  onblur={onBlur}
  onfocus={onFocus}
/>

// src/angular/arcana-input-mask.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, OnChanges, Output, SimpleChanges
} from "@angular/core";
import { mask as maskaMask, tokens as maskaTokens } from "maska";

/**
 * `ArcanaInputMaskComponent` — Angular port do SFC Vue `ArcanaInputMask`.
 *
 * Attribute selector num `<input>` (`<input arcanaInputMask>`): input mascarado
 * shadcn (`class="arcana-input"` + `--${size}`/`--disabled`), idêntico ao Vue/React.
 *
 * Decisão sobre a máscara (mesma do React — sem deps novas):
 * - O SFC usa a diretiva Vue `v-maska`, inexistente no Angular. Reusamos as funções CORE
 *   da `maska` (`mask`/`tokens`), agnósticas de framework:
 *   - display formatado   = `mask(raw, maskStr, tokens)`          (masked = true)
 *   - raw sem separadores  = `mask(raw, maskStr, tokens, false)`  (masked = false)
 *   Assim o valor EMITIDO é o mesmo raw do SFC (sem pontos/traços).
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange` (sempre o raw)
 * - `emit('blur'|'focus')` → eventos nativos do próprio `<input>` host
 * - watch(modelValue) → `ngOnChanges` re-aplica a máscara em mudança externa
 */
@Component({
  selector: "input[arcanaInputMask]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[value]": "tempValue",
    "[attr.placeholder]": "placeholder || null",
    "[disabled]": "disabled",
    "[attr.readonly]": "readonly ? '' : null",
    "[attr.name]": "name ?? null",
    "(input)": "onInput($event)"
  },
  template: ""
})
export class ArcanaInputMaskComponent implements OnChanges {
  @Input() value: string | number | null = "";
  @Input() mask: string | string[] = "";
  @Input() placeholder = "";
  @Input() disabled = false;
  @Input() readonly = false;
  @Input() name?: string;
  @Input() size: "sm" | "md" | "lg" = "md";
  @Input() className = "";

  @Output() valueChange = new EventEmitter<string>();

  tempValue = "";

  private get maskStr(): string {
    return Array.isArray(this.mask) ? JSON.stringify(this.mask) : this.mask;
  }

  get rootClass(): string {
    return [
      "arcana-input",
      `arcana-input--${this.size}`,
      this.disabled ? "arcana-input--disabled" : "",
      this.className
    ].filter(Boolean).join(" ");
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"] || changes["mask"]) {
      const incoming = this.value == null ? "" : String(this.value);
      const currentRaw = this.tempValue
        ? maskaMask(this.tempValue, this.maskStr, maskaTokens, false)
        : "";
      if (incoming !== currentRaw) {
        this.tempValue = incoming ? maskaMask(incoming, this.maskStr, maskaTokens) : "";
      }
    }
  }

  onInput(ev: Event): void {
    const typed = (ev.target as HTMLInputElement).value;
    this.tempValue = maskaMask(typed, this.maskStr, maskaTokens);
    const raw = maskaMask(typed, this.maskStr, maskaTokens, false);
    this.valueChange.emit(raw);
  }
}
