// src/svelte/ArcanaWizard.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { setContext } from "svelte";
  import { canNavigateTo, clampStep, formatStepLabel, stepStatus } from "../core/wizard";
  import { WIZARD_CONTEXT, type WizardContextValue, type WizardStepMeta } from "./wizard-context";

  type WizardValidate = (step: number) => boolean | string | Promise<boolean | string>;

  export interface WizardFooterScope {
    step: number;
    total: number;
    isFirst: boolean;
    isLast: boolean;
    back: () => void;
    next: () => void | Promise<void>;
    finish: () => void;
    cancel: () => void;
  }

  /**
   * `<ArcanaWizard>` — Svelte 5 port do shell de passos (stepper + corpo + rodapé), pai
   * do `<ArcanaWizardStep>`. Reproduz o MESMO markup/classes de
   * `src/vue/components/ArcanaWizard.vue` (fonte da verdade da anatomia/API — ver lá
   * pro detalhe visual em `src/styles/parts/wizard.scss`).
   *
   * Equivalências Vue → Svelte 5:
   * | Vue                                   | Svelte 5                                   |
   * | -------------------------------------- | ------------------------------------------- |
   * | `provide('wizardApi', …)` + `inject`   | `setContext(WIZARD_CONTEXT, …)` (aqui) +     |
   * |                                         | `getContext` (no `<ArcanaWizardStep>`)       |
   * | `mounted`/`beforeUnmount` (registro)   | `$effect` com `untrack` no register + cleanup |
   * | `modelValue` (v-model)                 | prop `value` + `onValueChange`               |
   * | `emit('next'\|'back'\|'cancel'\|'finish')` | `onNext`/`onBack`/`onCancel`/`onFinish`  |
   * | slot `header-actions`                  | snippet prop `headerActions?`                |
   * | slot `footer` (escopado)               | snippet prop `footer?: Snippet<[Scope]>`     |
   * |                                         | (snippets Svelte ACEITAM argumentos — ao     |
   * |                                         | contrário do Angular, que não suporta slot   |
   * |                                         | escopado com `<ng-content>`)                 |
   * | slot default                           | snippet `children` (os `<ArcanaWizardStep>`) |
   *
   * Anatomia (idêntica ao SFC — ver `wizard.scss` pro CSS compartilhado):
   *   .arcana-wizard
   *     .arcana-wizard__stepper
   *       .arcana-wizard__step (.is-active|.is-completed|.is-pending, +.is-clickable)
   *         .arcana-wizard__indicator (número OU .arcana-wizard__check quando concluído)
   *         .arcana-wizard__label > .arcana-wizard__title + .arcana-wizard__description
   *       .arcana-wizard__connector (+.is-completed entre passos já concluídos)
   *       .arcana-wizard__header-actions (snippet `headerActions`)
   *     .arcana-wizard__body — os `<ArcanaWizardStep>` do `children` se auto-registram
   *       aqui, só o passo ativo renderiza seu corpo (ver `<ArcanaWizardStep>`)
   *     .arcana-wizard__footer
   *       .arcana-wizard__footer-text — "Step {current} of {total}" (`stepLabel`)
   *       .arcana-wizard__footer-actions — snippet `footer` (com escopo) ou os botões
   *         default (Cancel/Back/Continue/Finish), classes `.arcana-wizard__btn` +
   *         `--primary` (Continue/Finish) ou `--default` (Back/Cancel). Botões crus
   *         (`<button>`), não `<ArcanaButton>` — mesma decisão do Vue/React.
   *
   * Contrato compartilhado com `<ArcanaWizardStep>` (`WIZARD_CONTEXT`, provido aqui):
   * `register({ title, description }) => index`, `unregister(index)`, `isActive(index)`,
   * `current()`. Os filhos se registram no mount (`$effect`) e se desregistram no cleanup
   * do `$effect` (equivalente a `beforeUnmount`).
   *
   * Passos estáticos apenas: os índices são a ordem de `register()` (= ordem de mount dos
   * `<ArcanaWizardStep>`, para passos declarados estaticamente no `children`). `unregister`
   * NÃO reindexa a lista — só marca a posição como "tombstone" (`null`), pra que os índices
   * já entregues a outros passos continuem válidos. `activeSteps` filtra os tombstones.
   * Adicionar/remover passos em runtime está fora do escopo (mesma ressalva do Vue).
   *
   * `totalSteps === 0` acontece por um instante entre o primeiro render do shell e o
   * `$effect` (pós-mount) dos `<ArcanaWizardStep>` — registro é assíncrono, igual ao
   * `mounted` do Vue. Sem a guarda em `isLast`, `0 >= -1` faria o rodapé mostrar "Finish"
   * antes do primeiro passo existir.
   *
   * Contrato de `validate(step)`: chamado (com `await`) antes de avançar via Continue.
   * Retorno `false` ou uma `string` BLOQUEIA o avanço — a string não é exibida
   * automaticamente (sem toast embutido); cabe ao consumidor tratar o retorno se quiser
   * mostrá-la. `true`/`undefined` (ou promise resolvida assim) libera o avanço, chama
   * `onNext` e atualiza `value` via `onValueChange`. No último passo, o botão vira "Finish"
   * e chama `onFinish` (sem chamar `validate`).
   */
  let {
    value = 0,
    onValueChange,
    validate,
    linear = true,
    cancellable = false,
    continueLabel = "Continue",
    backLabel = "Back",
    cancelLabel = "Cancel",
    finalLabel = "Finish",
    finalDisabled = false,
    stepLabel = "Step {current} of {total}",
    class: className = "",
    children,
    headerActions,
    footer,
    onNext,
    onBack,
    onCancel,
    onFinish,
  }: {
    value?: number;
    onValueChange?: (value: number) => void;
    validate?: WizardValidate;
    /** `true` (default): navegação direta no stepper só pra passos já alcançados. */
    linear?: boolean;
    cancellable?: boolean;
    continueLabel?: string;
    backLabel?: string;
    cancelLabel?: string;
    finalLabel?: string;
    finalDisabled?: boolean;
    stepLabel?: string;
    class?: string;
    children?: Snippet;
    headerActions?: Snippet;
    footer?: Snippet<[WizardFooterScope]>;
    onNext?: (step: number) => void;
    onBack?: (step: number) => void;
    onCancel?: () => void;
    onFinish?: () => void;
  } = $props();

  // Tombstone-on-unregister (ver doc acima): posições desregistradas viram `null` em vez
  // de removidas, pra não deslocar os índices já entregues aos passos que continuam montados.
  let steps = $state<Array<WizardStepMeta | null>>([]);

  const ctx: WizardContextValue = {
    register: (step) => {
      steps.push(step);
      return steps.length - 1;
    },
    unregister: (index) => {
      if (index >= 0 && index < steps.length) steps[index] = null;
    },
    // Funções leem `value` (prop reativa) no momento da chamada — o `$derived` do Step
    // que invoca `isActive` rastreia essa leitura e recomputa quando `value` muda.
    isActive: (index) => index === value,
    current: () => value,
  };
  setContext(WIZARD_CONTEXT, ctx);

  const activeSteps = $derived.by(() => {
    const out: Array<WizardStepMeta & { originalIndex: number }> = [];
    steps.forEach((step, originalIndex) => {
      if (step) out.push({ ...step, originalIndex });
    });
    return out;
  });

  const totalSteps = $derived(activeSteps.length);
  const isLast = $derived(totalSteps > 0 && value >= totalSteps - 1);
  const isFirst = $derived(value <= 0);
  const footerText = $derived(formatStepLabel(stepLabel, value, totalSteps));
  const classes = $derived(["arcana-wizard", className].filter(Boolean).join(" "));

  function isCompleted(i: number): boolean {
    return stepStatus(i, value) === "completed";
  }

  function stepClasses(i: number): string {
    return [
      "arcana-wizard__step",
      `is-${stepStatus(i, value)}`,
      canNavigateTo(i, value, linear) ? "is-clickable" : "",
    ]
      .filter(Boolean)
      .join(" ");
  }

  function goToStep(step: number) {
    onValueChange?.(clampStep(step, totalSteps));
  }

  function goToStepIfAllowed(i: number) {
    if (canNavigateTo(i, value, linear)) goToStep(i);
  }

  function goBack() {
    onBack?.(value);
    goToStep(value - 1);
  }

  async function handleNext() {
    if (validate) {
      const result = await validate(value);
      if (result === false || typeof result === "string") return;
    }
    onNext?.(value);
    goToStep(value + 1);
  }

  function emitFinish() {
    onFinish?.();
  }

  function emitCancel() {
    onCancel?.();
  }

  const footerScope = $derived<WizardFooterScope>({
    step: value,
    total: totalSteps,
    isFirst,
    isLast,
    back: goBack,
    next: handleNext,
    finish: emitFinish,
    cancel: emitCancel,
  });
</script>

<div class={classes}>
  <div class="arcana-wizard__stepper">
    {#each activeSteps as s, idx (s.originalIndex)}
      <div
        class={stepClasses(s.originalIndex)}
        onclick={() => goToStepIfAllowed(s.originalIndex)}
      >
        <div class="arcana-wizard__indicator">
          {#if isCompleted(s.originalIndex)}
            <svg
              class="arcana-wizard__check"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="3"
              stroke-linecap="round"
              stroke-linejoin="round"
              aria-hidden="true"
            >
              <polyline points="20 6 9 17 4 12" />
            </svg>
          {:else}
            {s.originalIndex + 1}
          {/if}
        </div>
        <div class="arcana-wizard__label">
          <div class="arcana-wizard__title">{s.title}</div>
          {#if s.description}
            <div class="arcana-wizard__description">{s.description}</div>
          {/if}
        </div>
      </div>
      {#if idx < activeSteps.length - 1}
        <div class="arcana-wizard__connector" class:is-completed={s.originalIndex < value}></div>
      {/if}
    {/each}
    {#if headerActions}
      <div class="arcana-wizard__header-actions">{@render headerActions()}</div>
    {/if}
  </div>

  <div class="arcana-wizard__body">{@render children?.()}</div>

  <div class="arcana-wizard__footer">
    <div class="arcana-wizard__footer-text">{footerText}</div>
    <div class="arcana-wizard__footer-actions">
      {#if footer}
        {@render footer(footerScope)}
      {:else}
        {#if cancellable}
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--default"
            onclick={emitCancel}
          >
            {cancelLabel}
          </button>
        {/if}
        {#if value > 0}
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--default"
            onclick={goBack}
          >
            {backLabel}
          </button>
        {/if}
        {#if !isLast}
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--primary"
            onclick={handleNext}
          >
            {continueLabel}
          </button>
        {:else}
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--primary"
            disabled={finalDisabled}
            onclick={emitFinish}
          >
            {finalLabel}
          </button>
        {/if}
      {/if}
    </div>
  </div>
</div>

// src/angular/arcana-wizard.component.ts
import {
  ChangeDetectionStrategy, ChangeDetectorRef, Component, EventEmitter, Input, Output, inject
} from "@angular/core";
import { canNavigateTo, clampStep, formatStepLabel, stepStatus } from "../core/wizard";

export type ArcanaWizardValidate = (step: number) => boolean | string | Promise<boolean | string>;

/** Registro interno de um passo (título/descrição) — ver `register`/`unregister`. */
type WizardStepMeta = { title: string; description?: string };

/**
 * `ArcanaWizardComponent` — Angular port do SFC Vue `ArcanaWizard`. Shell de passos
 * (stepper + corpo + rodapé), pai do `ArcanaWizardStepComponent`. Fonte da verdade da
 * anatomia/classes: `src/vue/components/ArcanaWizard.vue` + `src/styles/parts/wizard.scss`.
 *
 * Attribute selector num `<div>` (`<div arcanaWizard>`): reproduz `.arcana-wizard`,
 * `__stepper`, `__step` (+ `is-active`/`is-completed`/`is-pending`, +`is-clickable`),
 * `__indicator` (número OU `__check` svg quando concluído), `__label` > `__title` +
 * `__description`, `__connector` (+`is-completed`), `__header-actions`, `__body`,
 * `__footer` > `__footer-text` + `__footer-actions` (botões `__btn` +
 * `--primary`/`--default`), idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `@Input() value` + `@Output() valueChange`
 * - `provide('wizardApi', …)` → DI de componente pai: `ArcanaWizardStepComponent` injeta
 *   esta instância via `inject(ArcanaWizardComponent)` (mesma técnica do
 *   `ArcanaAccordionItemComponent`/`ArcanaAccordionComponent`). `register`/`unregister`/
 *   `isActive` viram métodos públicos desta classe.
 * - slot `header-actions` → `<ng-content select="[arcanaWizardHeaderActions]">`
 * - slot `footer` (SCOPED no Vue: `step`/`total`/`isFirst`/`isLast`/`back`/`next`/`finish`/
 *   `cancel`) → **DEVIATION**: `<ng-content>` não suporta slots escopados (não há como
 *   passar dados do componente pra dentro do conteúdo projetado, ao contrário de
 *   `v-slot`/render props). Replicar isso exigiria `*ngTemplateOutlet` com um `TemplateRef`
 *   de `@Input()` (API bem diferente da dos outros ports). Nesta fase o rodapé Angular só
 *   renderiza os botões default (Cancel/Back/Continue/Finish) — sem customização — e
 *   `header-actions` (slot não-escopado) é projetado normalmente via `<ng-content select>`.
 * - `emit('next'|'back'|'cancel'|'finish')` → `@Output() next`/`back`/`cancel`/`finish`.
 *   Os métodos internos usam nomes distintos (`goNext`/`goBack`) porque um `@Output()` não
 *   pode compartilhar nome com um método na mesma classe — mesma solução do port do
 *   QuickSearch (`search()` → `emitSearch()`).
 *
 * Contrato de `validate(step)`: chamado (com `await`) antes de avançar via Continue.
 * Retorno `false` ou uma `string` BLOQUEIA o avanço (sem alerta automático — cabe ao
 * consumidor tratar o retorno). `true`/`undefined` libera o avanço, emite `next` e
 * atualiza `value`. No último passo, o botão vira "Finish" e emite `finish` (sem chamar
 * `validate`).
 *
 * Passos estáticos apenas: `ArcanaWizardStepComponent` se registra no `ngOnInit` (que roda
 * DEPOIS do primeiro `detectChanges` do pai — registro é assíncrono, igual ao `mounted` do
 * Vue) e se desregistra no `ngOnDestroy`. `unregister` NÃO reindexa — só marca a posição
 * como tombstone (`null`), pra que os índices já entregues a passos que continuam montados
 * sigam válidos (`activeSteps` filtra os tombstones). `register`/`unregister` chamam
 * `markForCheck()` porque o componente é `OnPush` e essas mutações não passam por um
 * `@Input()`. Adicionar/remover passos em runtime está fora do escopo (mesma ressalva do
 * Vue).
 */
@Component({
  selector: "div[arcanaWizard]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "class": "arcana-wizard"
  },
  template: `
    <div class="arcana-wizard__stepper">
      @for (s of activeSteps; track s.originalIndex; let idx = $index) {
        <div
          [class]="stepClass(s.originalIndex)"
          (click)="goToStepIfAllowed(s.originalIndex)"
        >
          <div class="arcana-wizard__indicator">
            @if (isCompleted(s.originalIndex)) {
              <svg
                class="arcana-wizard__check"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="3"
                stroke-linecap="round"
                stroke-linejoin="round"
                aria-hidden="true"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            } @else {
              {{ s.originalIndex + 1 }}
            }
          </div>
          <div class="arcana-wizard__label">
            <div class="arcana-wizard__title">{{ s.title }}</div>
            @if (s.description) {
              <div class="arcana-wizard__description">{{ s.description }}</div>
            }
          </div>
        </div>
        @if (idx < activeSteps.length - 1) {
          <div class="arcana-wizard__connector" [class.is-completed]="s.originalIndex < value"></div>
        }
      }
      <div class="arcana-wizard__header-actions">
        <ng-content select="[arcanaWizardHeaderActions]"></ng-content>
      </div>
    </div>

    <div class="arcana-wizard__body">
      <ng-content></ng-content>
    </div>

    <div class="arcana-wizard__footer">
      <div class="arcana-wizard__footer-text">{{ footerText }}</div>
      <div class="arcana-wizard__footer-actions">
        @if (cancellable) {
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--default"
            (click)="emitCancel()"
          >{{ cancelLabel }}</button>
        }
        @if (value > 0) {
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--default"
            (click)="goBack()"
          >{{ backLabel }}</button>
        }
        @if (!isLast) {
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--primary"
            (click)="goNext()"
          >{{ continueLabel }}</button>
        } @else {
          <button
            type="button"
            class="arcana-wizard__btn arcana-wizard__btn--primary"
            [disabled]="finalDisabled"
            (click)="emitFinish()"
          >{{ finalLabel }}</button>
        }
      </div>
    </div>
  `
})
export class ArcanaWizardComponent {
  private readonly cdr = inject(ChangeDetectorRef);

  @Input() value = 0;
  @Input() validate?: ArcanaWizardValidate;
  @Input() linear = true;
  @Input() cancellable = false;
  @Input() continueLabel = "Continue";
  @Input() backLabel = "Back";
  @Input() cancelLabel = "Cancel";
  @Input() finalLabel = "Finish";
  @Input() finalDisabled = false;
  @Input() stepLabel = "Step {current} of {total}";

  @Output() valueChange = new EventEmitter<number>();
  @Output() next = new EventEmitter<number>();
  @Output() back = new EventEmitter<number>();
  @Output() cancel = new EventEmitter<void>();
  @Output() finish = new EventEmitter<void>();

  // Tombstone-on-unregister (ver doc da classe): posições desregistradas viram `null`
  // em vez de removidas, pra não deslocar os índices já entregues aos passos montados.
  private steps: Array<WizardStepMeta | null> = [];

  get activeSteps(): Array<WizardStepMeta & { originalIndex: number }> {
    const out: Array<WizardStepMeta & { originalIndex: number }> = [];
    this.steps.forEach((step, originalIndex) => {
      if (step) out.push({ ...step, originalIndex });
    });
    return out;
  }

  get totalSteps(): number {
    return this.activeSteps.length;
  }

  get isLast(): boolean {
    // `totalSteps === 0` acontece por um instante entre o primeiro render do shell e o
    // `ngOnInit` dos passos (registro é assíncrono). Sem essa guarda, `0 >= -1` faria o
    // rodapé mostrar "Finish" antes do primeiro passo existir.
    return this.totalSteps > 0 && this.value >= this.totalSteps - 1;
  }

  get footerText(): string {
    return formatStepLabel(this.stepLabel, this.value, this.totalSteps);
  }

  isActive(index: number): boolean {
    return index === this.value;
  }

  isCompleted(i: number): boolean {
    return stepStatus(i, this.value) === "completed";
  }

  stepClass(i: number): string {
    return [
      "arcana-wizard__step",
      `is-${stepStatus(i, this.value)}`,
      canNavigateTo(i, this.value, this.linear) ? "is-clickable" : ""
    ].filter(Boolean).join(" ");
  }

  register(step: WizardStepMeta): number {
    this.steps.push(step);
    this.cdr.markForCheck();
    return this.steps.length - 1;
  }

  unregister(index: number): void {
    if (index >= 0 && index < this.steps.length) this.steps[index] = null;
    this.cdr.markForCheck();
  }

  goToStep(step: number): void {
    const s = clampStep(step, this.totalSteps);
    this.valueChange.emit(s);
  }

  goToStepIfAllowed(i: number): void {
    if (canNavigateTo(i, this.value, this.linear)) this.goToStep(i);
  }

  goBack(): void {
    this.back.emit(this.value);
    this.goToStep(this.value - 1);
  }

  async goNext(): Promise<void> {
    if (this.validate) {
      const result = await this.validate(this.value);
      if (result === false || typeof result === "string") return;
    }
    this.next.emit(this.value);
    this.goToStep(this.value + 1);
  }

  emitFinish(): void {
    this.finish.emit();
  }

  emitCancel(): void {
    this.cancel.emit();
  }
}
