// src/react/ArcanaTable.tsx
import type { ReactNode } from "react";

/**
 * `<ArcanaTable>` — React port. Tabela estática (dados locais) shadcn. Reproduz
 * `<div class="arcana-table-wrap"><table class="arcana-table">`, o `thead`/`tbody`/`tfoot`,
 * `__th--right`/`__td--right`, `__empty` e `__foot`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slot de célula `#cell-<key>` → `col.render?({ row, value, index })`
 * - slot `#footer` → prop `footer` (ReactNode)
 */
export interface ArcanaTableColumn {
    key: string;
    label: string;
    width?: string;
    align?: "left" | "right";
    valueGetter?: (value: any, row: any, index: number) => any;
    /** Render custom da célula (equivale ao slot `#cell-<key>` do SFC). */
    render?: (args: { row: any; value: any; index: number }) => ReactNode;
}

export interface ArcanaTableProps {
    columns: ArcanaTableColumn[];
    rows?: any[];
    emptyText?: string;
    footer?: ReactNode;
    className?: string;
}

export function ArcanaTable({
    columns,
    rows = [],
    emptyText = "Nenhum registro.",
    footer,
    className,
}: ArcanaTableProps) {
    const formatCell = (row: any, col: ArcanaTableColumn, index: number): any => {
        const value = row?.[col.key];
        if (col.valueGetter) return col.valueGetter(value, row, index);
        return value ?? "—";
    };

    return (
        <div
            className={["arcana-table-wrap", className ?? ""]
                .filter(Boolean)
                .join(" ")}
        >
            <table className="arcana-table">
                <thead>
                    <tr>
                        {columns.map((col) => (
                            <th
                                key={col.key}
                                style={col.width ? { width: col.width } : undefined}
                                className={
                                    col.align === "right"
                                        ? "arcana-table__th--right"
                                        : undefined
                                }
                            >
                                {col.label}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {!rows.length ? (
                        <tr>
                            <td colSpan={columns.length} className="arcana-table__empty">
                                {emptyText}
                            </td>
                        </tr>
                    ) : (
                        rows.map((row, i) => (
                            <tr key={i}>
                                {columns.map((col) => (
                                    <td
                                        key={col.key}
                                        className={
                                            col.align === "right"
                                                ? "arcana-table__td--right"
                                                : undefined
                                        }
                                    >
                                        {col.render
                                            ? col.render({
                                                  row,
                                                  value: row?.[col.key],
                                                  index: i,
                                              })
                                            : formatCell(row, col, i)}
                                    </td>
                                ))}
                            </tr>
                        ))
                    )}
                </tbody>
                {footer ? (
                    <tfoot className="arcana-table__foot">{footer}</tfoot>
                ) : null}
            </table>
        </div>
    );
}

// src/angular/arcana-table.component.ts
import {
  ChangeDetectionStrategy, Component, Input, TemplateRef
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

/**
 * `ArcanaTableComponent` — Angular port do SFC Vue `ArcanaTable`. Tabela estática
 * (dados locais) shadcn.
 *
 * Attribute selector num `<div>` (`<div arcanaTable>`): reproduz
 * `.arcana-table-wrap > table.arcana-table`, o `thead`/`tbody`/`tfoot`,
 * `__th--right`/`__td--right`, `__empty` e `__foot`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - slot de célula `#cell-<key>` → `@Input() cellTemplates` (mapa key→TemplateRef;
 *   contexto `{ $implicit: value, row, value, index }`) OU `col.valueGetter`
 * - slot `#footer` → `@Input() footerTemplate` (TemplateRef)
 */
export interface ArcanaTableColumn {
  key: string;
  label: string;
  width?: string;
  align?: "left" | "right";
  valueGetter?: (value: unknown, row: Record<string, unknown>, index: number) => unknown;
}

@Component({
  selector: "div[arcanaTable]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { "[class]": "rootClass" },
  template: `
    <table class="arcana-table">
      <thead>
        <tr>
          @for (col of columns; track col.key) {
            <th
              [style.width]="col.width || null"
              [class.arcana-table__th--right]="col.align === 'right'"
            >{{ col.label }}</th>
          }
        </tr>
      </thead>
      <tbody>
        @if (!rows.length) {
          <tr>
            <td [attr.colspan]="columns.length" class="arcana-table__empty">{{ emptyText }}</td>
          </tr>
        } @else {
          @for (row of rows; track $index) {
            <tr>
              @for (col of columns; track col.key) {
                <td [class.arcana-table__td--right]="col.align === 'right'">
                  @if (cellTemplates[col.key]; as tpl) {
                    <ng-container
                      [ngTemplateOutlet]="tpl"
                      [ngTemplateOutletContext]="cellContext(row, col, $index)"
                    ></ng-container>
                  } @else {
                    {{ formatCell(row, col, $index) }}
                  }
                </td>
              }
            </tr>
          }
        }
      </tbody>
      @if (footerTemplate) {
        <tfoot class="arcana-table__foot">
          <ng-container [ngTemplateOutlet]="footerTemplate"></ng-container>
        </tfoot>
      }
    </table>
  `
})
export class ArcanaTableComponent {
  @Input() columns: ArcanaTableColumn[] = [];
  @Input() rows: Record<string, unknown>[] = [];
  @Input() emptyText = "Nenhum registro.";
  @Input() cellTemplates: Record<string, TemplateRef<unknown>> = {};
  @Input() footerTemplate?: TemplateRef<unknown>;
  @Input() className = "";

  get rootClass(): string {
    return ["arcana-table-wrap", this.className].filter(Boolean).join(" ");
  }

  formatCell(row: Record<string, unknown>, col: ArcanaTableColumn, index: number): unknown {
    const value = row?.[col.key];
    if (col.valueGetter) return col.valueGetter(value, row, index);
    return value ?? "—";
  }

  cellContext(row: Record<string, unknown>, col: ArcanaTableColumn, index: number) {
    const value = row?.[col.key];
    return { $implicit: value, row, value, index };
  }
}
