// src/react/ArcanaSwitchSegmented.tsx
import type { CSSProperties, KeyboardEvent, ReactNode } from "react";

/**
 * `<ArcanaSwitchSegmented>` — React port. Reproduz `<div class="arcana-switch-segmented">`
 * (+ `is-on`/`is-disabled`/`is-compact`/`is-squared`), o `__indicator` e as duas metades
 * `__option--off`/`__option--on` (com `__radio` opcional), idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` + `onValueChange`; `emit('change')` → `onChange`
 * - slots `#off-label`/`#on-label` → props `offSlot`/`onSlot` (ReactNode)
 *
 * `offIcon`/`onIcon` (classe FontAwesome) viram um `<i class="arcana-switch-segmented__icon">`
 * decorativo antes do texto de cada lado; `offIconColor`/`onIconColor` aplicam `color` inline
 * (vence o CSS, inclusive no lado ativo). Com o label vazio (`offLabel=""`) o lado fica
 * icon-only, com o ícone centralizado — nenhum texto é forçado.
 */
export interface ArcanaSwitchSegmentedProps {
    value?: boolean;
    offLabel?: string;
    onLabel?: string;
    /** Classe FontAwesome do ícone da opção esquerda (ex: `"fa-solid fa-moon"`). */
    offIcon?: string;
    /** Classe FontAwesome do ícone da opção direita (ex: `"fa-solid fa-sun"`). */
    onIcon?: string;
    /** Cor inline do `offIcon` (qualquer string CSS válida). */
    offIconColor?: string;
    /** Cor inline do `onIcon`. */
    onIconColor?: string;
    disabled?: boolean;
    ariaLabel?: string;
    compact?: boolean;
    squared?: boolean;
    activeColor?: string;
    radio?: boolean;
    offSlot?: ReactNode;
    onSlot?: ReactNode;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    className?: string;
}

export function ArcanaSwitchSegmented({
    value = false,
    offLabel = "Inativo",
    onLabel = "Ativo",
    offIcon = "",
    onIcon = "",
    offIconColor = "",
    onIconColor = "",
    disabled = false,
    ariaLabel = "",
    compact = false,
    squared = false,
    activeColor = "",
    radio = false,
    offSlot,
    onSlot,
    onValueChange,
    onChange,
    className,
}: ArcanaSwitchSegmentedProps) {
    // Labels vazios (modo icon-only) são descartados pra não gerar " ou ".
    const ariaLabelFallback = [offLabel, onLabel].filter(Boolean).join(" ou ");

    const toggle = () => {
        if (disabled) return;
        const next = !value;
        onValueChange?.(next);
        onChange?.(next);
    };

    const onKeydown = (e: KeyboardEvent<HTMLDivElement>) => {
        if (disabled) return;
        if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            toggle();
            return;
        }
        if (e.key === "ArrowLeft" && value) {
            e.preventDefault();
            toggle();
        }
        if (e.key === "ArrowRight" && !value) {
            e.preventDefault();
            toggle();
        }
    };

    const rootClasses = [
        "arcana-switch-segmented",
        value ? "is-on" : "",
        disabled ? "is-disabled" : "",
        compact ? "is-compact" : "",
        squared ? "is-squared" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const rootStyle = activeColor
        ? ({ "--seg-active": activeColor } as CSSProperties)
        : undefined;

    return (
        <div
            className={rootClasses}
            style={rootStyle}
            role="switch"
            aria-checked={Boolean(value)}
            aria-label={ariaLabel || ariaLabelFallback || undefined}
            aria-disabled={disabled}
            tabIndex={disabled ? -1 : 0}
            onClick={toggle}
            onKeyDown={onKeydown}
        >
            <div className="arcana-switch-segmented__indicator" aria-hidden="true" />

            <div className="arcana-switch-segmented__option arcana-switch-segmented__option--off">
                {radio ? (
                    <span
                        className="arcana-switch-segmented__radio"
                        aria-hidden="true"
                    />
                ) : null}
                {offIcon ? (
                    <i
                        className={`arcana-switch-segmented__icon ${offIcon}`}
                        style={offIconColor ? { color: offIconColor } : undefined}
                        aria-hidden="true"
                    />
                ) : null}
                {offSlot ?? (offLabel || null)}
            </div>
            <div className="arcana-switch-segmented__option arcana-switch-segmented__option--on">
                {radio ? (
                    <span
                        className="arcana-switch-segmented__radio"
                        aria-hidden="true"
                    />
                ) : null}
                {onIcon ? (
                    <i
                        className={`arcana-switch-segmented__icon ${onIcon}`}
                        style={onIconColor ? { color: onIconColor } : undefined}
                        aria-hidden="true"
                    />
                ) : null}
                {onSlot ?? (onLabel || null)}
            </div>
        </div>
    );
}

// src/angular/arcana-switch-segmented.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ArcanaSwitchSegmentedComponent` — Angular port do SFC Vue `ArcanaSwitchSegmented`.
 *
 * Attribute selector num `<div>` (`<div arcanaSwitchSegmented>`): reproduz
 * `.arcana-switch-segmented` (+ `is-on`/`is-disabled`/`is-compact`/`is-squared`),
 * o `__indicator` e as duas metades `__option--off`/`__option--on` (com `__radio`
 * opcional), idêntico ao Vue/React. Preserva o inline `--seg-active`.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 * - slots `#off-label`/`#on-label` → conteúdo projetado `[segOff]`/`[segOn]` (fallback: offLabel/onLabel)
 *
 * `offIcon`/`onIcon` (classe FontAwesome) viram um `<i class="arcana-switch-segmented__icon">`
 * decorativo antes do texto de cada lado; `offIconColor`/`onIconColor` aplicam `color` inline
 * (vence o CSS, inclusive no lado ativo). Com o label vazio (`offLabel=""`) o lado fica
 * icon-only, com o ícone centralizado — nenhum texto é forçado.
 */
@Component({
  selector: "div[arcanaSwitchSegmented]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.--seg-active]": "activeColor || null",
    "role": "switch",
    "[attr.aria-checked]": "!!value",
    "[attr.aria-label]": "ariaLabel || ariaLabelFallback || null",
    "[attr.aria-disabled]": "disabled",
    "[attr.tabindex]": "disabled ? -1 : 0",
    "(click)": "toggle()",
    "(keydown)": "onKeydown($event)"
  },
  template: `
    <div class="arcana-switch-segmented__indicator" aria-hidden="true"></div>

    <div class="arcana-switch-segmented__option arcana-switch-segmented__option--off">
      @if (radio) {
        <span class="arcana-switch-segmented__radio" aria-hidden="true"></span>
      }
      @if (offIcon) {
        <i
          [class]="'arcana-switch-segmented__icon ' + offIcon"
          [style.color]="offIconColor || null"
          aria-hidden="true"
        ></i>
      }
      <ng-content select="[segOff]">{{ offLabel }}</ng-content>
    </div>
    <div class="arcana-switch-segmented__option arcana-switch-segmented__option--on">
      @if (radio) {
        <span class="arcana-switch-segmented__radio" aria-hidden="true"></span>
      }
      @if (onIcon) {
        <i
          [class]="'arcana-switch-segmented__icon ' + onIcon"
          [style.color]="onIconColor || null"
          aria-hidden="true"
        ></i>
      }
      <ng-content select="[segOn]">{{ onLabel }}</ng-content>
    </div>
  `
})
export class ArcanaSwitchSegmentedComponent {
  @Input() value = false;
  @Input() offLabel = "Inativo";
  @Input() onLabel = "Ativo";
  /** Classe FontAwesome do ícone da opção esquerda (ex: `"fa-solid fa-moon"`). */
  @Input() offIcon = "";
  /** Classe FontAwesome do ícone da opção direita (ex: `"fa-solid fa-sun"`). */
  @Input() onIcon = "";
  /** Cor inline do `offIcon` (qualquer string CSS válida). */
  @Input() offIconColor = "";
  /** Cor inline do `onIcon`. */
  @Input() onIconColor = "";
  @Input() disabled = false;
  @Input() ariaLabel = "";
  @Input() compact = false;
  @Input() squared = false;
  @Input() activeColor = "";
  @Input() radio = false;

  @Output() valueChange = new EventEmitter<boolean>();
  @Output() change = new EventEmitter<boolean>();

  get ariaLabelFallback(): string {
    // Labels vazios (modo icon-only) são descartados pra não gerar " ou ".
    return [this.offLabel, this.onLabel].filter(Boolean).join(" ou ");
  }

  get rootClass(): string {
    return [
      "arcana-switch-segmented",
      this.value ? "is-on" : "",
      this.disabled ? "is-disabled" : "",
      this.compact ? "is-compact" : "",
      this.squared ? "is-squared" : ""
    ].filter(Boolean).join(" ");
  }

  toggle(): void {
    if (this.disabled) return;
    const next = !this.value;
    this.valueChange.emit(next);
    this.change.emit(next);
  }

  onKeydown(e: KeyboardEvent): void {
    if (this.disabled) return;
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      this.toggle();
      return;
    }
    if (e.key === "ArrowLeft" && this.value) {
      e.preventDefault();
      this.toggle();
    }
    if (e.key === "ArrowRight" && !this.value) {
      e.preventDefault();
      this.toggle();
    }
  }
}
