// src/react/ArcanaSkeleton.tsx
import type { CSSProperties } from "react";

/**
 * `<ArcanaSkeleton>` — React port. Placeholder shimmer. Reproduz
 * `<span class="arcana-skeleton arcana-skeleton--rounded-${rounded}">` com width/height
 * inline e `aria-hidden`, idêntico ao SFC.
 */
export interface ArcanaSkeletonProps {
    width?: string;
    height?: string;
    rounded?: "sm" | "md" | "lg" | "full" | "none";
    className?: string;
}

export function ArcanaSkeleton({
    width = "100%",
    height = "14px",
    rounded = "md",
    className,
}: ArcanaSkeletonProps) {
    const classes = [
        "arcana-skeleton",
        `arcana-skeleton--rounded-${rounded}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const style: CSSProperties = { width, height };

    return <span className={classes} style={style} aria-hidden="true" />;
}

// src/angular/arcana-skeleton.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `ArcanaSkeletonComponent` — Angular port do SFC Vue `ArcanaSkeleton`.
 *
 * Attribute selector num `<span>` (`<span arcanaSkeleton>`): emite
 * `span.arcana-skeleton arcana-skeleton--rounded-${rounded}` com width/height inline e
 * `aria-hidden`, idêntico ao Vue/React.
 */
export type SkeletonRounded = "sm" | "md" | "lg" | "full" | "none";

@Component({
  selector: "span[arcanaSkeleton]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.width]": "width",
    "[style.height]": "height",
    "[attr.aria-hidden]": "true"
  },
  template: ""
})
export class ArcanaSkeletonComponent {
  @Input() width = "100%";
  @Input() height = "14px";
  @Input() rounded: SkeletonRounded = "md";
  @Input() className = "";

  get rootClass(): string {
    return [
      "arcana-skeleton",
      `arcana-skeleton--rounded-${this.rounded}`,
      this.className
    ].filter(Boolean).join(" ");
  }
}
