// src/svelte/ArcanaTooltip.svelte
<script module lang="ts">
  // Contador de instâncias no escopo do MÓDULO (um `let` no `<script>` de
  // instância reiniciaria em 0 a cada componente e duplicaria os ids).
  let panelIdSeq = 0;
</script>

<script lang="ts">
  /**
   * `<ArcanaTooltip>` — Svelte 5 port. Balão de texto curto que abre ao passar o
   * mouse pelo gatilho (e ao focá-lo pelo teclado). Versão enxuta e opinativa do
   * `<ArcanaHoverCard>`: conteúdo textual, balão escuro com setinha, e nunca
   * interativo (`pointer-events: none` no CSS).
   *
   * Estrutura: gatilho inline (snippet `trigger`) + balão PORTADO pro `<body>`
   * com `position: fixed`, posicionado por `placeHoverCard` (`core/hover-card`)
   * com flip automático quando não cabe do lado pedido.
   *
   * Equivalências Vue → Svelte 5:
   * - slot `trigger` → snippet `trigger`; slot default → snippet `children`
   * - `<Teleport to="body">` → action `use:portal`
   * - `emit('open-change')` → callback `onOpenChange`
   *
   * Acessibilidade: o gatilho recebe `aria-describedby` apontando pro balão
   * enquanto aberto e o balão é `role="tooltip"`. `Escape` fecha. Ponha um
   * elemento naturalmente focável (botão/link) no snippet `trigger` pra que a
   * abertura por teclado funcione.
   */
  import type { Snippet } from "svelte";
  import { placeHoverCard, resolveHoverCardPlacement } from "../core/hover-card";
  import type { HoverCardAlign, HoverCardPlacement, HoverCardSide } from "../core/hover-card";
  import { portal } from "./portal";

  /** Tamanho presumido antes da 1ª medição (evita flip errado no 1º frame). */
  const PANEL_ESTIMATE = { width: 160, height: 32 };
  /** Folga mínima entre a seta e o canto do balão. */
  const ARROW_EDGE = 10;

  let {
    label = "",
    openDelay = 200,
    closeDelay = 0,
    side = "top",
    align = "center",
    placement = undefined,
    offset = 6,
    arrow = true,
    disabled = false,
    panelClass = undefined,
    trigger,
    children,
    onOpenChange,
    class: className = "",
  }: {
    /** Texto do tooltip. Use o snippet `children` pra conteúdo custom (o snippet vence). */
    label?: string;
    /** ms até abrir depois do `mouseenter` (o foco por teclado abre na hora). Default `200`. */
    openDelay?: number;
    /** ms de carência antes de fechar no mouse (default `0` = imediato). */
    closeDelay?: number;
    side?: HoverCardSide;
    align?: HoverCardAlign;
    /** Atalho `"{side}-{align}"` (ex: `"top-start"`); vence `side`/`align`. */
    placement?: HoverCardPlacement;
    /** Distância entre gatilho e balão em px. Default `6`. */
    offset?: number;
    /** Mostra a setinha apontando pro gatilho. Default `true`. */
    arrow?: boolean;
    disabled?: boolean;
    /**
     * Classe extra no balão. Como ele é portado pro `<body>`, um seletor no
     * wrapper não o alcança — é assim que se tematiza uma instância.
     */
    panelClass?: string;
    /** O gatilho (slot `trigger` do Vue). */
    trigger?: Snippet;
    /** O conteúdo do balão (slot default do Vue) — sobrepõe `label`. */
    children?: Snippet;
    onOpenChange?: (open: boolean) => void;
    class?: string;
  } = $props();

  const panelId = `arcana-tooltip-${++panelIdSeq}`;

  let isOpen = $state(false);
  let panelStyle = $state("");
  let resolvedSide = $state<HoverCardSide>("top");
  let triggerEl = $state<HTMLElement | undefined>(undefined);
  let panelEl = $state<HTMLElement | undefined>(undefined);

  let openTimer: ReturnType<typeof setTimeout> | undefined;
  let closeTimer: ReturnType<typeof setTimeout> | undefined;

  /* ─────────────────────────── posicionamento ──────────────────────────────── */

  function clampArrow(value: number, size: number): number {
    return Math.max(ARROW_EDGE, Math.min(value, size - ARROW_EDGE));
  }

  /**
   * Posição da seta ao longo da borda do balão, apontando pro centro do gatilho.
   * Nos lados verticais (top/bottom) é um X; nos horizontais, um Y. Preso (clamp)
   * pra não escapar do balão.
   */
  function arrowOffset(
    place: { left: number; top: number; side: HoverCardSide },
    rect: DOMRect,
    panelWidth: number,
    panelHeight: number
  ): string {
    const vertical = place.side === "top" || place.side === "bottom";
    if (vertical) {
      const center = rect.left + rect.width / 2 - place.left;
      return `${clampArrow(center, panelWidth)}px`;
    }
    const center = rect.top + rect.height / 2 - place.top;
    return `${clampArrow(center, panelHeight)}px`;
  }

  function reposition() {
    if (!triggerEl) return;

    const rect = triggerEl.getBoundingClientRect();
    const panelWidth = panelEl?.offsetWidth || PANEL_ESTIMATE.width;
    const panelHeight = panelEl?.offsetHeight || PANEL_ESTIMATE.height;

    const parts = resolveHoverCardPlacement(placement, side, align);
    const place = placeHoverCard(
      rect,
      { width: panelWidth, height: panelHeight },
      { width: window.innerWidth, height: window.innerHeight },
      { ...parts, gap: offset }
    );

    resolvedSide = place.side;
    panelStyle =
      `position: fixed; left: ${place.left}px; top: ${place.top}px;` +
      ` --arcana-tooltip-arrow-offset: ${arrowOffset(place, rect, panelWidth, panelHeight)};`;
  }

  /* ─────────────────────── abertura / fechamento ───────────────────────────── */

  function clearOpenTimer() {
    if (!openTimer) return;
    clearTimeout(openTimer);
    openTimer = undefined;
  }

  function cancelClose() {
    if (!closeTimer) return;
    clearTimeout(closeTimer);
    closeTimer = undefined;
  }

  function open() {
    if (disabled || isOpen) return;
    isOpen = true;
    onOpenChange?.(true);
  }

  function close() {
    clearOpenTimer();
    cancelClose();
    if (!isOpen) return;
    isOpen = false;
    onOpenChange?.(false);
  }

  function scheduleOpen(delay: number) {
    cancelClose();
    if (disabled || isOpen) return;
    clearOpenTimer();
    if (delay <= 0) {
      open();
      return;
    }
    openTimer = setTimeout(() => {
      openTimer = undefined;
      open();
    }, delay);
  }

  function scheduleClose() {
    clearOpenTimer();
    if (!isOpen || closeTimer) return;
    if (closeDelay <= 0) {
      close();
      return;
    }
    closeTimer = setTimeout(() => {
      closeTimer = undefined;
      close();
    }, closeDelay);
  }

  // `disabled` ligado no meio do caminho fecha o que estiver aberto.
  $effect(() => {
    if (disabled) close();
  });

  // Mede/posiciona assim que o balão entra no DOM e registra os listeners
  // globais só enquanto ele está aberto.
  $effect(() => {
    if (!isOpen || !panelEl) return;

    reposition();

    const onKeydown = (event: KeyboardEvent) => {
      if (event.key === "Escape") close();
    };
    const onScroll = () => reposition();
    const onResize = () => reposition();

    document.addEventListener("keydown", onKeydown);
    window.addEventListener("scroll", onScroll, true);
    window.addEventListener("resize", onResize);
    return () => {
      document.removeEventListener("keydown", onKeydown);
      window.removeEventListener("scroll", onScroll, true);
      window.removeEventListener("resize", onResize);
    };
  });

  // Timers pendentes não sobrevivem ao componente.
  $effect(() => () => {
    clearOpenTimer();
    cancelClose();
  });
</script>

<span
  class={["arcana-tooltip", isOpen ? "is-open" : "", disabled ? "is-disabled" : "", className]
    .filter(Boolean)
    .join(" ")}
>
  <span
    bind:this={triggerEl}
    class="arcana-tooltip__trigger"
    aria-describedby={isOpen ? panelId : undefined}
    onmouseenter={() => scheduleOpen(openDelay)}
    onmouseleave={() => scheduleClose()}
    onfocusin={() => scheduleOpen(0)}
    onfocusout={() => scheduleClose()}
  >
    {@render trigger?.()}
  </span>

  <!--
    Balão portado pro <body> (position: fixed via `placeHoverCard`) pra escapar
    de qualquer ancestral com overflow:hidden / z-index restritivo.
    `pointer-events: none` (no CSS) — nunca é alvo do mouse.
  -->
  {#if isOpen}
    <div
      use:portal
      bind:this={panelEl}
      id={panelId}
      class={["arcana-tooltip__panel", `arcana-tooltip__panel--${resolvedSide}`, panelClass]
        .filter(Boolean)
        .join(" ")}
      style={panelStyle}
      role="tooltip"
    >
      {#if children}{@render children()}{:else}{label}{/if}
      {#if arrow}<span class="arcana-tooltip__arrow" aria-hidden="true"></span>{/if}
    </div>
  {/if}
</span>

// src/angular/arcana-tooltip.component.ts
import {
  ChangeDetectionStrategy, ChangeDetectorRef, Component, ElementRef, EmbeddedViewRef,
  EventEmitter, Input, OnChanges, OnDestroy, Output, SimpleChanges, TemplateRef,
  ViewChild, ViewContainerRef, inject
} from "@angular/core";
import { placeHoverCard, resolveHoverCardPlacement } from "../core/hover-card";
import type { HoverCardAlign, HoverCardPlacement, HoverCardSide } from "../core/hover-card";

/**
 * `ArcanaTooltipComponent` — Angular port do SFC Vue `ArcanaTooltip`.
 *
 * Attribute selector num `<span>` (`<span arcanaTooltip>`): balão de texto curto
 * que abre ao passar o mouse pelo gatilho (e ao focá-lo pelo teclado). Versão
 * enxuta e opinativa do `ArcanaHoverCard` — conteúdo textual, balão escuro com
 * setinha e nunca interativo. Emite o MESMO markup e as MESMAS classes do
 * Vue/React/Svelte — `.arcana-tooltip` no host, `.arcana-tooltip__trigger` e o
 * `.arcana-tooltip__panel` TELEPORTADO pro `<body>` (+ `--{side}` efetivo, seta).
 *
 * Portal (sem deps novas — NÃO usa CDK Overlay): o balão vive num `<ng-template>`;
 * ao abrir criamos um `EmbeddedViewRef` via `ViewContainerRef` e movemos seu root
 * pro `document.body` (mesma técnica do `ArcanaHoverCard`). Posicionamento por
 * `placeHoverCard` (`core/hover-card`), com flip automático quando não cabe.
 *
 * Vue → Angular:
 * - slot `trigger` → `<ng-content select="[arcanaTooltipTrigger]">`;
 * - slot default (conteúdo do balão, sobrepõe `label`) → `<ng-content>` com
 *   fallback `{{ label }}` (renderizado quando nada é projetado);
 * - `emit('open-change')` → `@Output() openChange`.
 *
 * Acessibilidade: o gatilho recebe `aria-describedby` apontando pro balão enquanto
 * aberto e o balão é `role="tooltip"` (pointer-events:none — nunca é alvo do
 * mouse). `Escape` fecha. Ponha um elemento naturalmente focável (botão/link) no
 * gatilho pra que a abertura por teclado funcione.
 *
 * @example
 * <span arcanaTooltip label="Salvar rascunho" side="top">
 *   <button arcanaTooltipTrigger aria-label="Salvar"><i class="icon-save"></i></button>
 * </span>
 */

/** Tamanho presumido antes da 1ª medição (evita flip errado no 1º frame). */
const PANEL_ESTIMATE = { width: 160, height: 32 };
/** Folga mínima entre a seta e o canto do balão. */
const ARROW_EDGE = 10;

let panelIdSeq = 0;

@Component({
  selector: "span[arcanaTooltip]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass"
  },
  template: `
    <span
      #triggerEl
      class="arcana-tooltip__trigger"
      [attr.aria-describedby]="isOpen ? panelId : null"
      (mouseenter)="onTriggerEnter()"
      (mouseleave)="scheduleClose()"
      (focusin)="onTriggerFocusIn()"
      (focusout)="scheduleClose()"
    >
      <ng-content select="[arcanaTooltipTrigger]"></ng-content>
    </span>

    <!--
      Balão teleportado pro <body> (position: fixed via placeHoverCard) pra
      escapar de qualquer ancestral com overflow:hidden / z-index restritivo.
      pointer-events:none (no CSS) — nunca é alvo do mouse.
    -->
    <ng-template #panelTpl>
      <div
        [id]="panelId"
        [class]="panelClasses"
        [style]="panelStyle"
        role="tooltip"
      >
        <ng-content>{{ label }}</ng-content>
        @if (arrow) {
          <span class="arcana-tooltip__arrow" aria-hidden="true"></span>
        }
      </div>
    </ng-template>
  `
})
export class ArcanaTooltipComponent implements OnChanges, OnDestroy {
  /** Texto do tooltip. Use conteúdo projetado pra custom (o projetado vence). */
  @Input() label = "";
  /** ms até abrir depois do `mouseenter` (o foco por teclado abre na hora). Default `200`. */
  @Input() openDelay = 200;
  /** ms de carência antes de fechar (default `0` — fecha na hora). */
  @Input() closeDelay = 0;
  @Input() side: HoverCardSide = "top";
  @Input() align: HoverCardAlign = "center";
  /** Atalho `'{side}-{align}'` (ex: `'top-start'`); vence `side`/`align`. */
  @Input() placement?: HoverCardPlacement;
  /** Distância entre gatilho e balão em px. Default `6`. */
  @Input() offset = 6;
  /** Mostra a setinha apontando pro gatilho. Default `true`. */
  @Input() arrow = true;
  @Input() disabled = false;
  /**
   * Classe extra no balão. Como ele é teleportado pro `<body>`, um seletor no
   * host não o alcança — é assim que se tematiza uma instância.
   */
  @Input() panelClass?: string;

  @Output() openChange = new EventEmitter<boolean>();

  @ViewChild("panelTpl") panelTpl?: TemplateRef<unknown>;
  @ViewChild("triggerEl") triggerRef?: ElementRef<HTMLElement>;

  isOpen = false;
  panelStyle = "";
  resolvedSide: HoverCardSide = "top";
  readonly panelId = `arcana-tooltip-${++panelIdSeq}`;

  private readonly vcr = inject(ViewContainerRef);
  private readonly cdr = inject(ChangeDetectorRef);

  private embeddedView?: EmbeddedViewRef<unknown>;
  private panelEl?: HTMLElement;
  private openTimer?: ReturnType<typeof setTimeout>;
  private closeTimer?: ReturnType<typeof setTimeout>;

  get rootClass(): string {
    return [
      "arcana-tooltip",
      this.isOpen ? "is-open" : "",
      this.disabled ? "is-disabled" : ""
    ].filter(Boolean).join(" ");
  }

  get panelClasses(): string {
    return [
      "arcana-tooltip__panel",
      `arcana-tooltip__panel--${this.resolvedSide}`,
      this.panelClass
    ].filter(Boolean).join(" ");
  }

  /* ─────────────────────── eventos do gatilho ──────────────────────────────── */

  onTriggerEnter(): void {
    this.scheduleOpen(this.openDelay);
  }

  /** Teclado não tem "trajeto do mouse": abrir com atraso só atrapalharia. */
  onTriggerFocusIn(): void {
    this.scheduleOpen(0);
  }

  /* ─────────────────────── agendamento ─────────────────────────────────────── */

  scheduleOpen(delay: number): void {
    this.cancelClose();
    if (this.disabled || this.isOpen) return;
    this.clearOpenTimer();
    if (delay <= 0) {
      this.open();
      return;
    }
    this.openTimer = setTimeout(() => {
      this.openTimer = undefined;
      this.open();
    }, delay);
  }

  scheduleClose(): void {
    this.clearOpenTimer();
    if (!this.isOpen) return;
    if (this.closeDelay <= 0) {
      this.close();
      return;
    }
    if (this.closeTimer) return;
    this.closeTimer = setTimeout(() => {
      this.closeTimer = undefined;
      this.close();
    }, this.closeDelay);
  }

  cancelClose(): void {
    if (!this.closeTimer) return;
    clearTimeout(this.closeTimer);
    this.closeTimer = undefined;
  }

  private clearOpenTimer(): void {
    if (!this.openTimer) return;
    clearTimeout(this.openTimer);
    this.openTimer = undefined;
  }

  /* ─────────────────────── abertura / fechamento ───────────────────────────── */

  open(): void {
    if (this.disabled || this.isOpen || !this.panelTpl) return;

    // Pré-posiciona com a estimativa pra que o balão já monte perto do lugar
    // final (medir depois de montado devolve o tamanho real).
    const rect = this.triggerRef?.nativeElement.getBoundingClientRect();
    if (rect) this.applyPlacement(rect, PANEL_ESTIMATE);

    this.isOpen = true;
    this.embeddedView = this.vcr.createEmbeddedView(this.panelTpl);
    this.embeddedView.detectChanges();
    this.panelEl = this.embeddedView.rootNodes[0] as HTMLElement;
    document.body.appendChild(this.panelEl);
    this.attachListeners();
    this.openChange.emit(true);

    if (typeof requestAnimationFrame === "function") {
      requestAnimationFrame(() => {
        this.reposition();
        this.cdr.markForCheck();
      });
    } else {
      this.reposition();
    }
    this.cdr.markForCheck();
  }

  close(): void {
    this.clearOpenTimer();
    this.cancelClose();
    if (!this.isOpen) return;
    this.isOpen = false;
    this.detachListeners();
    this.embeddedView?.destroy();
    this.embeddedView = undefined;
    this.panelEl = undefined;
    this.openChange.emit(false);
    this.cdr.markForCheck();
  }

  ngOnChanges(changes: SimpleChanges): void {
    // `disabled` ligado no meio do caminho fecha o que estiver aberto.
    if (changes["disabled"] && this.disabled) this.close();
  }

  ngOnDestroy(): void {
    this.clearOpenTimer();
    this.cancelClose();
    this.detachListeners();
    this.embeddedView?.destroy();
    this.embeddedView = undefined;
    this.panelEl = undefined;
  }

  /* ─────────────────────── posicionamento ──────────────────────────────────── */

  private applyPlacement(rect: DOMRect, panel: { width: number; height: number }): void {
    const parts = resolveHoverCardPlacement(this.placement, this.side, this.align);
    const place = placeHoverCard(
      rect,
      panel,
      { width: window.innerWidth, height: window.innerHeight },
      { ...parts, gap: this.offset }
    );
    this.resolvedSide = place.side;
    const arrowOffset = this.arrowOffset(place, rect, panel.width, panel.height);
    this.panelStyle =
      `position: fixed; left: ${place.left}px; top: ${place.top}px;` +
      ` --arcana-tooltip-arrow-offset: ${arrowOffset};`;
  }

  /**
   * Posição da seta ao longo da borda do balão, apontando pro centro do gatilho.
   * Nos lados verticais (top/bottom) é um X; nos horizontais, um Y. Preso (clamp)
   * pra não escapar do balão.
   */
  private arrowOffset(
    place: { left: number; top: number; side: HoverCardSide },
    rect: DOMRect,
    panelWidth: number,
    panelHeight: number
  ): string {
    const vertical = place.side === "top" || place.side === "bottom";
    if (vertical) {
      const center = rect.left + rect.width / 2 - place.left;
      return `${this.clampArrow(center, panelWidth)}px`;
    }
    const center = rect.top + rect.height / 2 - place.top;
    return `${this.clampArrow(center, panelHeight)}px`;
  }

  private clampArrow(value: number, size: number): number {
    return Math.max(ARROW_EDGE, Math.min(value, size - ARROW_EDGE));
  }

  private reposition(): void {
    const trigger = this.triggerRef?.nativeElement;
    if (!trigger) return;
    this.applyPlacement(trigger.getBoundingClientRect(), {
      width: this.panelEl?.offsetWidth || PANEL_ESTIMATE.width,
      height: this.panelEl?.offsetHeight || PANEL_ESTIMATE.height
    });
    // O balão vive fora da árvore de CD do host — re-renderiza na mão.
    this.embeddedView?.detectChanges();
  }

  /* ─────────────────────── listeners globais ───────────────────────────────── */

  private readonly onKeydown = (event: KeyboardEvent): void => {
    if (event.key === "Escape") {
      this.close();
      this.cdr.markForCheck();
    }
  };

  private readonly onScroll = (): void => {
    this.reposition();
  };

  private readonly onResize = (): void => {
    this.reposition();
  };

  private attachListeners(): void {
    document.addEventListener("keydown", this.onKeydown);
    window.addEventListener("scroll", this.onScroll, true);
    window.addEventListener("resize", this.onResize);
  }

  private detachListeners(): void {
    document.removeEventListener("keydown", this.onKeydown);
    window.removeEventListener("scroll", this.onScroll, true);
    window.removeEventListener("resize", this.onResize);
  }
}
