// src/svelte/ArcanaSpecSheetField.svelte
<script lang="ts">
  /**
   * `<ArcanaSpecSheetField>` — Svelte 5 port do SFC Vue. Campo individual da
   * `<ArcanaSpecSheetSection>`: label uppercase mono + valor. Valor vazio mostra
   * `emptyText` em italic muted. Slot default substitui o valor (badges/HTML custom).
   *
   * slot default → snippet `children` (quando presente, NUNCA renderiza como vazio).
   */
  import type { Snippet } from "svelte";

  let {
    label,
    value = "",
    emptyText = "Não informado",
    span = 1,
    children,
  }: {
    label: string;
    value?: string | number | null;
    emptyText?: string;
    span?: number | string;
    children?: Snippet;
  } = $props();

  const isEmpty = $derived(
    !children && (value === null || value === undefined || value === "")
  );
  const displayValue = $derived(isEmpty ? emptyText : String(value));

  const valueClasses = $derived(
    ["arcana-spec-sheet__value", isEmpty ? "arcana-spec-sheet__value--empty" : ""]
      .filter(Boolean)
      .join(" ")
  );
</script>

<div class="arcana-spec-sheet__field" style={Number(span) > 1 ? `grid-column:span ${span};` : undefined}>
  <div class="arcana-spec-sheet__label">{label}</div>
  <div class={valueClasses}>
    {#if children}{@render children()}{:else}{displayValue}{/if}
  </div>
</div>

// src/angular/arcana-spec-sheet-field.component.ts
import {
  ChangeDetectionStrategy, Component, Input, TemplateRef
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

/**
 * `ArcanaSpecSheetFieldComponent` — Angular port do SFC Vue `ArcanaSpecSheetField`.
 *
 * Attribute selector num `<div>` (`<div arcanaSpecSheetField>`): campo individual da
 * `ArcanaSpecSheetSection`. Reproduz `.arcana-spec-sheet__field`, `__label`, `__value`
 * (+`--empty`), com `gridColumn: span N` quando `span > 1`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - slot default (substitui o valor por HTML/badge custom) → `@Input() valueTemplate`
 *   (`TemplateRef`). Quando presente, o campo NUNCA é renderizado como vazio.
 * - `value` vazio (null/undefined/"") → mostra `emptyText` em italic muted.
 */
@Component({
  selector: "div[arcanaSpecSheetField]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: {
    "class": "arcana-spec-sheet__field",
    "[style.gridColumn]": "spanStyle"
  },
  template: `
    <div class="arcana-spec-sheet__label">{{ label }}</div>
    <div class="arcana-spec-sheet__value" [class.arcana-spec-sheet__value--empty]="isEmpty">
      @if (valueTemplate) {
        <ng-container [ngTemplateOutlet]="valueTemplate"></ng-container>
      } @else {
        {{ displayValue }}
      }
    </div>
  `
})
export class ArcanaSpecSheetFieldComponent {
  @Input({ required: true }) label!: string;
  @Input() value: string | number | null = "";
  @Input() emptyText = "Não informado";
  @Input() span: number | string = 1;
  @Input() valueTemplate?: TemplateRef<unknown>;

  get spanStyle(): string | null {
    return Number(this.span) > 1 ? `span ${this.span}` : null;
  }

  get isEmpty(): boolean {
    if (this.valueTemplate) return false;
    return this.value === null || this.value === undefined || this.value === "";
  }

  get displayValue(): string {
    if (this.isEmpty) return this.emptyText;
    return String(this.value);
  }
}
