// src/svelte/ShadcnAccordionItem.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { getContext } from "svelte";
  import { ACCORDION_CONTEXT, type AccordionApi } from "./ShadcnAccordion.svelte";

  /**
   * `<ShadcnAccordionItem>` — Svelte 5 port. Reproduz o item (`shadcn-accordion-item` +
   * `open`/`disabled`, `shadcn-accordion-trigger`, `shadcn-accordion-title`,
   * `shadcn-accordion-chevron`, `shadcn-accordion-content`), idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - `inject('accordionApi')` → `getContext(ACCORDION_CONTEXT)`
   * - slots default/`#title` → snippet `children` / prop `title` (`string | Snippet`)
   */
  let {
    name,
    title = "",
    disabled = false,
    class: className = "",
    children,
  }: {
    name: string;
    title?: string | Snippet;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
  } = $props();

  const api = getContext<AccordionApi>(ACCORDION_CONTEXT);
  if (!api) {
    throw new Error("ShadcnAccordionItem must be used within a ShadcnAccordion");
  }

  const open = $derived(api.isOpen(name));

  const rootClasses = $derived(
    ["shadcn-accordion-item", open ? "open" : "", disabled ? "disabled" : "", className]
      .filter(Boolean)
      .join(" ")
  );

  function onToggle() {
    if (disabled) return;
    api.toggle(name);
  }
</script>

<div class={rootClasses}>
  <button type="button" class="shadcn-accordion-trigger" {disabled} onclick={onToggle}>
    <span class="shadcn-accordion-title">
      {#if typeof title === "function"}{@render title()}{:else}{title}{/if}
    </span>
    <i class="fa-solid fa-chevron-down shadcn-accordion-chevron"></i>
  </button>
  <!-- Vue usa `v-show` — o content fica montado e alterna via `display` (preserva estado). -->
  <div class="shadcn-accordion-content" style={open ? undefined : "display: none;"}>
    {@render children?.()}
  </div>
</div>

// src/angular/shadcn-accordion-item.component.ts
import {
  ChangeDetectionStrategy, Component, Input, inject
} from "@angular/core";
import { ShadcnAccordionComponent } from "./shadcn-accordion.component";

/**
 * `ShadcnAccordionItemComponent` — Angular port do SFC Vue `ShadcnAccordionItem`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnAccordionItem name="…">`): reproduz
 * `.shadcn-accordion-item` (+ `open`/`disabled`), `.shadcn-accordion-trigger`,
 * `.shadcn-accordion-title`, `.shadcn-accordion-chevron` e `.shadcn-accordion-content`,
 * idêntico ao Vue/React. O `inject`/`provide` do Vue vira `inject(ShadcnAccordionComponent)`
 * (o item é projetado dentro do accordion, logo ele está na cadeia de injeção).
 *
 * Change detection Default (não OnPush): o estado `open` vem do `value` do accordion pai —
 * quando um item abre e os outros precisam fechar (modo single), a CD do consumidor
 * re-checa todos os itens sem precisar de `markForCheck` manual.
 *
 * Vue → Angular: slot `#title` → `@Input() title` (string) nesta fase; slot default → `<ng-content>`.
 */
@Component({
  selector: "div[arcanaShadcnAccordionItem]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.Default,
  host: {
    "[class]": "rootClass"
  },
  template: `
    <button type="button" class="shadcn-accordion-trigger" [disabled]="disabled" (click)="onToggle()">
      <span class="shadcn-accordion-title">{{ title }}</span>
      <i class="fa-solid fa-chevron-down shadcn-accordion-chevron"></i>
    </button>
    <div class="shadcn-accordion-content" [style.display]="isOpen ? null : 'none'">
      <ng-content></ng-content>
    </div>
  `
})
export class ShadcnAccordionItemComponent {
  private readonly accordion = inject(ShadcnAccordionComponent);

  @Input({ required: true }) name!: string;
  @Input() title = "";
  @Input() disabled = false;

  get isOpen(): boolean {
    return this.accordion.isOpen(this.name);
  }

  get rootClass(): string {
    return [
      "shadcn-accordion-item",
      this.isOpen ? "open" : "",
      this.disabled ? "disabled" : ""
    ].filter(Boolean).join(" ");
  }

  onToggle(): void {
    if (this.disabled) return;
    this.accordion.toggle(this.name);
  }
}
