// src/react/ShadcnButton.tsx
import type { MouseEvent, ReactNode } from "react";

/**
 * `<ShadcnButton>` — React port do SFC Vue de mesmo nome. Emite o MESMO markup e as
 * MESMAS classes (`shadcn-button`, `shadcn-button--${variant}`, `is-disabled`) pra
 * reusar o CSS compartilhado (`@arcanalabs/ui-components/styles.css`).
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 * - `emit('click', ev)` → `onClick(ev)`
 */
export type ShadcnButtonVariant =
    | "primary"
    | "outline"
    | "outline-danger"
    | "ghost"
    | "danger"
    | "destructive"
    | "destructive-outline"
    | "success"
    | "secondary"
    | "dark"
    | "indigo"
    | "alert"
    | "info"
    | "warning"
    | "teal";

export interface ShadcnButtonProps {
    variant?: ShadcnButtonVariant;
    type?: "button" | "submit";
    disabled?: boolean;
    onClick?: (ev: MouseEvent<HTMLButtonElement>) => void;
    className?: string;
    children?: ReactNode;
}

export function ShadcnButton({
    variant = "primary",
    type = "button",
    disabled = false,
    onClick,
    className,
    children,
}: ShadcnButtonProps) {
    const classes = [
        "shadcn-button",
        `shadcn-button--${variant}`,
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <button
            type={type}
            className={classes}
            disabled={disabled}
            onClick={(ev) => onClick?.(ev)}
        >
            {children}
        </button>
    );
}

// src/angular/shadcn-button.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `ShadcnButtonComponent` — Angular port do SFC Vue `ShadcnButton`.
 *
 * Attribute selector num `<button>` (`<button arcanaShadcnButton>`) para que o DOM de
 * saída seja idêntico ao Vue/React: um `<button class="shadcn-button shadcn-button--…">`
 * de verdade, sem wrapper. As classes são aplicadas via host binding.
 *
 * Vue → Angular:
 * - props `variant`/`type`/`disabled` → `@Input()`
 * - slot default → `<ng-content>`
 * - `emit('click', ev)` → o host É um `<button>` nativo, então o consumidor binda o
 *   `(click)` DOM diretamente (`<button arcanaShadcnButton (click)="…">`) — sem Output
 *   custom (que colidiria com o evento nativo do próprio host).
 */
export type ShadcnButtonVariant =
  | "primary" | "outline" | "outline-danger" | "ghost" | "danger" | "destructive"
  | "destructive-outline" | "success" | "secondary" | "dark" | "indigo" | "alert"
  | "info" | "warning" | "teal";

@Component({
  selector: "button[arcanaShadcnButton]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[attr.type]": "type",
    "[disabled]": "disabled"
  },
  template: `<ng-content></ng-content>`
})
export class ShadcnButtonComponent {
  @Input() variant: ShadcnButtonVariant = "primary";
  @Input() type: "button" | "submit" = "button";
  @Input() disabled = false;
  @Input() className = "";

  get rootClass(): string {
    return [
      "shadcn-button",
      `shadcn-button--${this.variant}`,
      this.disabled ? "is-disabled" : "",
      this.className
    ].filter(Boolean).join(" ");
  }
}
