// src/react/ShadcnBadge.tsx
import type { MouseEvent, ReactNode } from "react";

/**
 * `<ShadcnBadge>` — React port. Pill/badge shadcn. Emite `span.shadcn-badge` +
 * `shadcn-badge--${variant}` (+ `--sm`, `--clickable`) e o `span.shadcn-badge__dot`
 * opcional, idêntico ao SFC Vue.
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 * - `@click` no root → `onClick`
 */
export type ShadcnBadgeVariant = "neutral" | "blue" | "green" | "red" | "amber" | "violet";

export interface ShadcnBadgeProps {
    variant?: ShadcnBadgeVariant;
    dot?: boolean;
    size?: "sm" | "md";
    clickable?: boolean;
    onClick?: (ev: MouseEvent<HTMLSpanElement>) => void;
    className?: string;
    children?: ReactNode;
}

export function ShadcnBadge({
    variant = "neutral",
    dot = false,
    size = "md",
    clickable = false,
    onClick,
    className,
    children,
}: ShadcnBadgeProps) {
    const classes = [
        "shadcn-badge",
        `shadcn-badge--${variant}`,
        size === "sm" ? "shadcn-badge--sm" : "",
        clickable ? "shadcn-badge--clickable" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <span className={classes} onClick={onClick}>
            {dot ? <span className="shadcn-badge__dot" /> : null}
            {children}
        </span>
    );
}

// src/angular/shadcn-badge.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `ShadcnBadgeComponent` — Angular port do SFC Vue `ShadcnBadge`.
 *
 * Attribute selector num `<span>` (`<span arcanaShadcnBadge>`): emite
 * `span.shadcn-badge` + `shadcn-badge--${variant}` (+ `--sm`, `--clickable`) e o
 * `span.shadcn-badge__dot` opcional, idêntico ao Vue/React. O `@click` cai no próprio host.
 *
 * Vue → Angular: props → `@Input()`; slot default → `<ng-content>`.
 */
export type ShadcnBadgeVariant = "neutral" | "blue" | "green" | "red" | "amber" | "violet";

@Component({
  selector: "span[arcanaShadcnBadge]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass"
  },
  template: `
    @if (dot) {
      <span class="shadcn-badge__dot"></span>
    }
    <ng-content></ng-content>
  `
})
export class ShadcnBadgeComponent {
  @Input() variant: ShadcnBadgeVariant = "neutral";
  @Input() dot = false;
  @Input() size: "sm" | "md" = "md";
  @Input() clickable = false;
  @Input() className = "";

  get rootClass(): string {
    return [
      "shadcn-badge",
      `shadcn-badge--${this.variant}`,
      this.size === "sm" ? "shadcn-badge--sm" : "",
      this.clickable ? "shadcn-badge--clickable" : "",
      this.className
    ].filter(Boolean).join(" ");
  }
}
