// src/react/ShadcnSkeleton.tsx
import type { CSSProperties } from "react";

/**
 * `<ShadcnSkeleton>` — React port. Placeholder shimmer. Reproduz
 * `<span class="shadcn-skeleton shadcn-skeleton--rounded-${rounded}">` com width/height
 * inline e `aria-hidden`, idêntico ao SFC.
 */
export interface ShadcnSkeletonProps {
    width?: string;
    height?: string;
    rounded?: "sm" | "md" | "lg" | "full" | "none";
    className?: string;
}

export function ShadcnSkeleton({
    width = "100%",
    height = "14px",
    rounded = "md",
    className,
}: ShadcnSkeletonProps) {
    const classes = [
        "shadcn-skeleton",
        `shadcn-skeleton--rounded-${rounded}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const style: CSSProperties = { width, height };

    return <span className={classes} style={style} aria-hidden="true" />;
}

// src/angular/shadcn-skeleton.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `ShadcnSkeletonComponent` — Angular port do SFC Vue `ShadcnSkeleton`.
 *
 * Attribute selector num `<span>` (`<span arcanaShadcnSkeleton>`): emite
 * `span.shadcn-skeleton shadcn-skeleton--rounded-${rounded}` com width/height inline e
 * `aria-hidden`, idêntico ao Vue/React.
 */
export type SkeletonRounded = "sm" | "md" | "lg" | "full" | "none";

@Component({
  selector: "span[arcanaShadcnSkeleton]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.width]": "width",
    "[style.height]": "height",
    "[attr.aria-hidden]": "true"
  },
  template: ""
})
export class ShadcnSkeletonComponent {
  @Input() width = "100%";
  @Input() height = "14px";
  @Input() rounded: SkeletonRounded = "md";
  @Input() className = "";

  get rootClass(): string {
    return [
      "shadcn-skeleton",
      `shadcn-skeleton--rounded-${this.rounded}`,
      this.className
    ].filter(Boolean).join(" ");
  }
}
