// src/react/ShadcnOnboardingPanel.tsx
import type { ReactNode } from "react";

/**
 * `<ShadcnOnboardingPanel>` — React port do SFC Vue. Empty state / CTA panel para
 * primeiras configurações. Markup/classes `shadcn-onboarding*` idênticos ao SFC.
 *
 * Equivalências Vue → React:
 * - slot default → `children` (fallback: `description`)
 * - slot `#action` → prop `action` (ReactNode; substitui a CTA padrão)
 * - slot `#sub-hint` → prop `subHintSlot` (ReactNode; substitui o sub-hint padrão)
 * - `emit('action'|'secondary-action')` → `onAction` / `onSecondaryAction`
 */
export interface ShadcnOnboardingPanelProps {
    icon: string;
    title: string;
    description?: string;
    actionLabel?: string;
    actionIcon?: string;
    actionLoading?: boolean;
    secondaryActionLabel?: string;
    secondaryActionIcon?: string;
    subHint?: string;
    subHintIcon?: string;
    /** Substitui o slot default (descrição rica). */
    children?: ReactNode;
    /** Substitui o slot `#action` (botão custom). */
    action?: ReactNode;
    /** Substitui o slot `#sub-hint`. */
    subHintSlot?: ReactNode;
    onAction?: () => void;
    onSecondaryAction?: () => void;
}

export function ShadcnOnboardingPanel({
    icon,
    title,
    description = "",
    actionLabel = "",
    actionIcon = "fa-solid fa-plus",
    actionLoading = false,
    secondaryActionLabel = "",
    secondaryActionIcon = "",
    subHint = "",
    subHintIcon = "",
    children,
    action,
    subHintSlot,
    onAction,
    onSecondaryAction,
}: ShadcnOnboardingPanelProps) {
    const hasDescription = Boolean(children) || Boolean(description);
    const hasActionZone = Boolean(action || actionLabel || secondaryActionLabel);
    const hasSubHint = Boolean(subHintSlot || subHint);

    return (
        <div className="shadcn-onboarding">
            <div className="shadcn-onboarding__visual">
                <div className="shadcn-onboarding__ring" />
                <div className="shadcn-onboarding__ring shadcn-onboarding__ring--2" />
                <div className="shadcn-onboarding__icon">
                    <i className={icon} />
                </div>
            </div>

            <h3 className="shadcn-onboarding__title">{title}</h3>

            {hasDescription && (
                <p className="shadcn-onboarding__desc">{children ?? description}</p>
            )}

            {hasActionZone && (
                <div className="shadcn-onboarding__action">
                    {action ?? (
                        <>
                            {actionLabel && (
                                <button
                                    className="shadcn-onboarding__cta"
                                    disabled={actionLoading}
                                    onClick={() => onAction?.()}
                                >
                                    {actionLoading ? (
                                        <i className="fa-solid fa-spinner fa-spin" />
                                    ) : actionIcon ? (
                                        <i className={actionIcon} />
                                    ) : null}
                                    <span>{actionLabel}</span>
                                </button>
                            )}
                            {secondaryActionLabel && (
                                <button
                                    className="shadcn-onboarding__cta shadcn-onboarding__cta--secondary"
                                    onClick={() => onSecondaryAction?.()}
                                >
                                    {secondaryActionIcon && <i className={secondaryActionIcon} />}
                                    <span>{secondaryActionLabel}</span>
                                </button>
                            )}
                        </>
                    )}
                </div>
            )}

            {hasSubHint && (
                <p className="shadcn-onboarding__sub-hint">
                    {subHintSlot ?? (
                        <>
                            {subHintIcon && <i className={subHintIcon} />}
                            <span>{subHint}</span>
                        </>
                    )}
                </p>
            )}
        </div>
    );
}

// src/angular/shadcn-onboarding-panel.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output, TemplateRef
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

/**
 * `ShadcnOnboardingPanelComponent` — Angular port do SFC Vue `ShadcnOnboardingPanel`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnOnboardingPanel>`): empty state / CTA
 * panel. Reproduz `.shadcn-onboarding` (visual/ring/icon), `__title`/`__desc`/`__action`/
 * `__cta`(+`--secondary`)/`__sub-hint`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - slot default (descrição rica) → `@Input() descriptionTemplate` (`TemplateRef`) OU
 *   `<ng-content>` (fallback: prop `description`).
 * - slot `#action` → `@Input() actionTemplate`; slot `#sub-hint` → `@Input() subHintTemplate`.
 * - `emit('action')` / `emit('secondary-action')` → `@Output() action` / `@Output() secondaryAction`.
 */
@Component({
  selector: "div[arcanaShadcnOnboardingPanel]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { "class": "shadcn-onboarding" },
  template: `
    <div class="shadcn-onboarding__visual">
      <div class="shadcn-onboarding__ring"></div>
      <div class="shadcn-onboarding__ring shadcn-onboarding__ring--2"></div>
      <div class="shadcn-onboarding__icon">
        <i [class]="icon"></i>
      </div>
    </div>

    <h3 class="shadcn-onboarding__title">{{ title }}</h3>

    @if (descriptionTemplate) {
      <p class="shadcn-onboarding__desc">
        <ng-container [ngTemplateOutlet]="descriptionTemplate"></ng-container>
      </p>
    } @else if (description) {
      <p class="shadcn-onboarding__desc">{{ description }}</p>
    }

    @if (actionTemplate || actionLabel || secondaryActionLabel) {
      <div class="shadcn-onboarding__action">
        @if (actionTemplate) {
          <ng-container [ngTemplateOutlet]="actionTemplate"></ng-container>
        } @else {
          @if (actionLabel) {
            <button
              class="shadcn-onboarding__cta"
              [disabled]="actionLoading"
              (click)="action.emit()"
            >
              @if (actionLoading) {
                <i class="fa-solid fa-spinner fa-spin"></i>
              } @else if (actionIcon) {
                <i [class]="actionIcon"></i>
              }
              <span>{{ actionLabel }}</span>
            </button>
          }
          @if (secondaryActionLabel) {
            <button
              class="shadcn-onboarding__cta shadcn-onboarding__cta--secondary"
              (click)="secondaryAction.emit()"
            >
              @if (secondaryActionIcon) {
                <i [class]="secondaryActionIcon"></i>
              }
              <span>{{ secondaryActionLabel }}</span>
            </button>
          }
        }
      </div>
    }

    @if (subHintTemplate || subHint) {
      <p class="shadcn-onboarding__sub-hint">
        @if (subHintTemplate) {
          <ng-container [ngTemplateOutlet]="subHintTemplate"></ng-container>
        } @else {
          @if (subHintIcon) {
            <i [class]="subHintIcon"></i>
          }
          <span>{{ subHint }}</span>
        }
      </p>
    }
  `
})
export class ShadcnOnboardingPanelComponent {
  @Input({ required: true }) icon!: string;
  @Input({ required: true }) title!: string;
  @Input() description = "";
  @Input() actionLabel = "";
  @Input() actionIcon = "fa-solid fa-plus";
  @Input() actionLoading = false;
  @Input() secondaryActionLabel = "";
  @Input() secondaryActionIcon = "";
  @Input() subHint = "";
  @Input() subHintIcon = "";
  @Input() descriptionTemplate?: TemplateRef<unknown>;
  @Input() actionTemplate?: TemplateRef<unknown>;
  @Input() subHintTemplate?: TemplateRef<unknown>;

  @Output() action = new EventEmitter<void>();
  @Output() secondaryAction = new EventEmitter<void>();
}
