// src/svelte/ShadcnSegmentedOptions.svelte
<script lang="ts">
  /**
   * `<ShadcnSegmentedOptions>` — Svelte 5 port. Segmented control de N opções. Reproduz
   * `<div class="shadcn-segmented-options">` (+ `is-compact`/`is-squared`/`is-disabled`),
   * cada `<button class="shadcn-segmented-options__option">` (+ `is-active`), o
   * `__radio`/`__icon` opcionais e o `__empty`, idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - `modelValue` (v-model) → prop `value` + `onValueChange`; `emit('change')` → `onChange`
   * - `--seg-active` inline style preservado
   */
  export interface SegmentedOption {
    label: string;
    value: string | number;
    disabled?: boolean;
    icon?: string;
  }

  let {
    value = null,
    options = [],
    disabled = false,
    compact = false,
    squared = false,
    activeColor = "",
    radio = false,
    autoSelectFirst = false,
    ariaLabel = "",
    emptyText = "Sem opções disponíveis",
    onValueChange,
    onChange,
    class: className = "",
  }: {
    value?: string | number | null;
    options?: SegmentedOption[];
    disabled?: boolean;
    compact?: boolean;
    squared?: boolean;
    activeColor?: string;
    radio?: boolean;
    autoSelectFirst?: boolean;
    ariaLabel?: string;
    emptyText?: string;
    onValueChange?: (value: string | number) => void;
    onChange?: (value: string | number) => void;
    class?: string;
  } = $props();

  const normalizedOptions = $derived(options ?? []);

  function select(opt: SegmentedOption) {
    if (disabled || opt.disabled || opt.value === value) return;
    onValueChange?.(opt.value);
    onChange?.(opt.value);
  }

  // `autoSelectFirst`: quando as options carregam e nada está selecionado, seleciona a
  // 1ª habilitada. Reproduz o watch(options)+mounted do SFC.
  $effect(() => {
    // Depende de `options` (nova referência a cada carga dinâmica).
    void options;
    if (!autoSelectFirst || disabled) return;
    const hasValue = value !== null && value !== undefined && value !== "";
    if (hasValue) return;
    const first = normalizedOptions.find((o) => !o.disabled);
    if (!first) return;
    onValueChange?.(first.value);
    onChange?.(first.value);
  });

  const rootClasses = $derived(
    [
      "shadcn-segmented-options",
      compact ? "is-compact" : "",
      squared ? "is-squared" : "",
      disabled ? "is-disabled" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );
</script>

<div
  class={rootClasses}
  style={activeColor ? `--seg-active: ${activeColor};` : undefined}
  role="radiogroup"
  aria-label={ariaLabel || undefined}
>
  {#each normalizedOptions as opt (String(opt.value))}
    <button
      type="button"
      class={["shadcn-segmented-options__option", opt.value === value ? "is-active" : ""]
        .filter(Boolean)
        .join(" ")}
      role="radio"
      aria-checked={opt.value === value}
      disabled={disabled || opt.disabled}
      onclick={() => select(opt)}
    >
      {#if radio}<span class="shadcn-segmented-options__radio" aria-hidden="true"></span>{/if}
      {#if opt.icon}<i class={`shadcn-segmented-options__icon ${opt.icon}`}></i>{/if}
      <span>{opt.label}</span>
    </button>
  {/each}

  {#if !normalizedOptions.length}
    <span class="shadcn-segmented-options__empty">{emptyText}</span>
  {/if}
</div>

// src/angular/shadcn-segmented-options.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, OnChanges, OnInit,
  Output, SimpleChanges
} from "@angular/core";

/**
 * `ShadcnSegmentedOptionsComponent` — Angular port do SFC Vue `ShadcnSegmentedOptions`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnSegmentedOptions>`): segmented control
 * de N opções. Reproduz `.shadcn-segmented-options` (+ `is-compact`/`is-squared`/`is-disabled`),
 * cada `.shadcn-segmented-options__option` (+ `is-active`), o `__radio`/`__icon` opcionais e o
 * `__empty`, idêntico ao Vue/React. Preserva o inline `--seg-active`.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 */
export interface SegmentedOption {
  label: string;
  value: string | number;
  disabled?: boolean;
  icon?: string;
}

@Component({
  selector: "div[arcanaShadcnSegmentedOptions]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.--seg-active]": "activeColor || null",
    "role": "radiogroup",
    "[attr.aria-label]": "ariaLabel || null"
  },
  template: `
    @for (opt of normalizedOptions; track opt.value) {
      <button
        type="button"
        class="shadcn-segmented-options__option"
        [class.is-active]="opt.value === value"
        role="radio"
        [attr.aria-checked]="opt.value === value"
        [disabled]="disabled || opt.disabled"
        (click)="select(opt)"
      >
        @if (radio) {
          <span class="shadcn-segmented-options__radio" aria-hidden="true"></span>
        }
        @if (opt.icon) {
          <i [class]="'shadcn-segmented-options__icon ' + opt.icon"></i>
        }
        <span>{{ opt.label }}</span>
      </button>
    }

    @if (!normalizedOptions.length) {
      <span class="shadcn-segmented-options__empty">{{ emptyText }}</span>
    }
  `
})
export class ShadcnSegmentedOptionsComponent implements OnInit, OnChanges {
  @Input() value: string | number | null = null;
  @Input() options: SegmentedOption[] = [];
  @Input() disabled = false;
  @Input() compact = false;
  @Input() squared = false;
  @Input() activeColor = "";
  @Input() radio = false;
  @Input() autoSelectFirst = false;
  @Input() ariaLabel = "";
  @Input() emptyText = "Sem opções disponíveis";

  @Output() valueChange = new EventEmitter<string | number>();
  @Output() change = new EventEmitter<string | number>();

  get normalizedOptions(): SegmentedOption[] {
    return this.options ?? [];
  }

  get rootClass(): string {
    return [
      "shadcn-segmented-options",
      this.compact ? "is-compact" : "",
      this.squared ? "is-squared" : "",
      this.disabled ? "is-disabled" : ""
    ].filter(Boolean).join(" ");
  }

  ngOnInit(): void {
    this.autoSelectDefault();
  }

  ngOnChanges(changes: SimpleChanges): void {
    // `options` chega novo do backend → replica o watch(options) do SFC.
    if (changes["options"] && !changes["options"].firstChange) {
      this.autoSelectDefault();
    }
  }

  select(opt: SegmentedOption): void {
    if (this.disabled || opt.disabled || opt.value === this.value) return;
    this.valueChange.emit(opt.value);
    this.change.emit(opt.value);
  }

  private autoSelectDefault(): void {
    if (!this.autoSelectFirst || this.disabled) return;
    const hasValue = this.value !== null && this.value !== undefined && this.value !== "";
    if (hasValue) return;
    const first = this.normalizedOptions.find((o) => !o.disabled);
    if (!first) return;
    this.valueChange.emit(first.value);
    this.change.emit(first.value);
  }
}
