// src/svelte/ShadcnCheckbox.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  /**
   * `<ShadcnCheckbox>` — Svelte 5 port. Reproduz o `<label class="shadcn-checkbox">` com
   * `<input type="checkbox" class="shadcn-checkbox__input">` NATIVO + a pintura
   * (`shadcn-checkbox__box`/`__icon`/`__label`), idêntico ao SFC Vue.
   *
   * Equivalências Vue → Svelte 5:
   * - `modelValue` (v-model) → prop `value` + `onValueChange`
   * - `emit('change')` → `onChange` (mesmo booleano)
   * - slot default → snippet `children` (fallback pro `label`)
   */
  let {
    value = false,
    indeterminate = false,
    disabled = false,
    label = "",
    name = "",
    ariaLabel = "",
    onValueChange,
    onChange,
    class: className = "",
    children,
  }: {
    value?: boolean;
    indeterminate?: boolean;
    disabled?: boolean;
    label?: string;
    name?: string;
    ariaLabel?: string;
    onValueChange?: (checked: boolean) => void;
    onChange?: (checked: boolean) => void;
    class?: string;
    children?: Snippet;
  } = $props();

  const rootClasses = $derived(
    [
      "shadcn-checkbox",
      value || indeterminate ? "shadcn-checkbox--checked" : "",
      disabled ? "shadcn-checkbox--disabled" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );

  function handleChange(checked: boolean) {
    onValueChange?.(checked);
    onChange?.(checked);
  }
</script>

<label class={rootClasses}>
  <input
    type="checkbox"
    class="shadcn-checkbox__input"
    checked={value}
    {disabled}
    name={name || undefined}
    aria-label={ariaLabel || undefined}
    onchange={(e) => handleChange((e.target as HTMLInputElement).checked)}
  />

  <span class="shadcn-checkbox__box" aria-hidden="true">
    {#if indeterminate}
      <i class="fa-solid fa-minus shadcn-checkbox__icon"></i>
    {:else if value}
      <i class="fa-solid fa-check shadcn-checkbox__icon"></i>
    {/if}
  </span>

  {#if children || label}
    <span class="shadcn-checkbox__label">
      {#if children}{@render children()}{:else}{label}{/if}
    </span>
  {/if}
</label>

// src/angular/shadcn-checkbox.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ShadcnCheckboxComponent` — Angular port do SFC Vue `ShadcnCheckbox`.
 *
 * Attribute selector num `<label>` (`<label arcanaShadcnCheckbox>`): reproduz o
 * `<label class="shadcn-checkbox">` com `<input type="checkbox" class="shadcn-checkbox__input">`
 * NATIVO + a pintura (`__box`/`__icon`/`__label`), idêntico ao Vue/React. O input real
 * preserva `check()`/`uncheck()` do Dusk.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 * - slot default (label) → `@Input() label` (string) nesta fase.
 */
@Component({
  selector: "label[arcanaShadcnCheckbox]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass"
  },
  template: `
    <input
      type="checkbox"
      class="shadcn-checkbox__input"
      [checked]="value"
      [disabled]="disabled"
      [attr.name]="name || null"
      [attr.aria-label]="ariaLabel || null"
      (change)="onChange($event)"
    />

    <span class="shadcn-checkbox__box" aria-hidden="true">
      @if (indeterminate) {
        <i class="fa-solid fa-minus shadcn-checkbox__icon"></i>
      } @else if (value) {
        <i class="fa-solid fa-check shadcn-checkbox__icon"></i>
      }
    </span>

    @if (label) {
      <span class="shadcn-checkbox__label">{{ label }}</span>
    }
  `
})
export class ShadcnCheckboxComponent {
  @Input() value = false;
  @Input() indeterminate = false;
  @Input() disabled = false;
  @Input() label = "";
  @Input() name = "";
  @Input() ariaLabel = "";

  @Output() valueChange = new EventEmitter<boolean>();
  @Output() change = new EventEmitter<boolean>();

  get rootClass(): string {
    return [
      "shadcn-checkbox",
      this.value || this.indeterminate ? "shadcn-checkbox--checked" : "",
      this.disabled ? "shadcn-checkbox--disabled" : ""
    ].filter(Boolean).join(" ");
  }

  onChange(ev: Event): void {
    const checked = (ev.target as HTMLInputElement).checked;
    this.valueChange.emit(checked);
    this.change.emit(checked);
  }
}
