// src/svelte/ShadcnTabs.svelte
<script lang="ts" module>
  export interface ShadcnTabItem {
    name: string | number;
    label: string;
    disabled?: boolean;
    icon?: string;
    iconColor?: string;
    badge?: string | number;
    group?: string;
    tone?: "default" | "danger";
    eager?: boolean;
  }

  export type ShadcnTabsVariant =
    | "pills" | "underline" | "boxed" | "sidebar" | "sidebar-soft" | "sidebar-shell" | "segmented";

  let uidCounter = 0;
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import { tick } from "svelte";

  /**
   * `<ShadcnTabs>` — Svelte 5 port do SFC Vue. Reproduz o mesmo markup/classes:
   * `shadcn-tabs` (+ `--${variant}`, `--${orientation}`, `--flush`), `shadcn-tabs__list`,
   * `shadcn-tabs__trigger` (+ `is-active`/`is-disabled`/`is-tone-*`), `__trigger-icon`,
   * `__trigger-label`, `__trigger-badge`, `__group-header` e `shadcn-tabs__panel`.
   *
   * Equivalências Vue → Svelte 5:
   * - `modelValue` (v-model) → prop `value` + `onValueChange`; `emit('change')` → `onChange`
   * - slots nomeados (um por `tab.name`) → prop `panels` (mapa name → Snippet) ou `panel`
   *   (Snippet que recebe o tab ativo); `#list-header` → snippet `listHeader`
   *
   * Nota: `tooltipPlacement` do SFC usa `<el-tooltip>` (Element Plus, Vue-only) — este port
   * renderiza os triggers SEM o wrapper de tooltip (o markup do `<button>` é idêntico). A prop
   * é aceita mas ignorada nesta fase.
   */
  type RenderableItem =
    | { type: "header"; label: string; key: string }
    | { type: "tab"; tab: ShadcnTabItem; key: string };

  let {
    value,
    tabs,
    variant = "pills",
    orientation = "horizontal",
    ariaLabel = "",
    keepAlive = false,
    flush = false,
    tooltipPlacement = "",
    onValueChange,
    onChange,
    panels,
    panel,
    listHeader,
    class: className = "",
  }: {
    value: string | number;
    tabs: ShadcnTabItem[];
    variant?: ShadcnTabsVariant;
    orientation?: "horizontal" | "vertical";
    ariaLabel?: string;
    keepAlive?: boolean;
    flush?: boolean;
    tooltipPlacement?: string;
    onValueChange?: (name: string | number) => void;
    onChange?: (name: string | number) => void;
    /** Mapa `tab.name` → snippet do painel (equivale aos slots nomeados do Vue). */
    panels?: Record<string, Snippet>;
    /** Alternativa a `panels`: snippet único que recebe o tab a renderizar. */
    panel?: Snippet<[ShadcnTabItem]>;
    /** Equivale ao slot `#list-header`. */
    listHeader?: Snippet;
    class?: string;
  } = $props();

  void tooltipPlacement;

  const uid = ++uidCounter;
  const triggerRefs: (HTMLButtonElement | null)[] = [];

  // keepAlive LAZY: nomes de tabs já visitadas ao menos uma vez.
  let activatedTabNames = $state<string[]>(
    value != null && value !== "" ? [String(value)] : []
  );

  $effect(() => {
    const name = value == null ? "" : String(value);
    if (name && !activatedTabNames.includes(name)) {
      activatedTabNames = [...activatedTabNames, name];
    }
  });

  const normalizedTabs = $derived(tabs ?? []);
  const isSidebarLike = $derived(
    variant === "sidebar" || variant === "sidebar-soft" || variant === "sidebar-shell"
  );
  const effectiveOrientation = $derived(isSidebarLike ? "vertical" : orientation);
  const showsGroupHeaders = $derived(variant === "sidebar-soft" || variant === "sidebar-shell");

  const rootClasses = $derived(
    [
      "shadcn-tabs",
      `shadcn-tabs--${variant}`,
      `shadcn-tabs--${effectiveOrientation}`,
      flush ? "shadcn-tabs--flush" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );

  const isActive = (tab: ShadcnTabItem) => tab.name === value;
  const isDisabled = (tab: ShadcnTabItem) => Boolean(tab.disabled);
  const wasActivated = (tab: ShadcnTabItem) =>
    Boolean(tab.eager) || activatedTabNames.includes(String(tab.name));
  const triggerId = (tab: ShadcnTabItem) => `shadcn-tabs-${uid}-trigger-${String(tab.name)}`;
  const panelId = (tab: ShadcnTabItem) => `shadcn-tabs-${uid}-panel-${String(tab.name)}`;
  const triggerIndexOf = (tab: ShadcnTabItem) =>
    normalizedTabs.findIndex((t) => t.name === tab.name);

  const activeTab = $derived(normalizedTabs.find((t) => t.name === value) ?? null);

  const renderableItems = $derived.by<RenderableItem[]>(() => {
    if (!showsGroupHeaders) {
      return normalizedTabs.map((t) => ({ type: "tab" as const, tab: t, key: String(t.name) }));
    }
    const out: RenderableItem[] = [];
    let currentGroup: string | null = null;
    for (const tab of normalizedTabs) {
      const tabGroup = tab.group ?? null;
      if (tabGroup && tabGroup !== currentGroup) {
        out.push({ type: "header", label: tabGroup, key: `__group__${tabGroup}` });
        currentGroup = tabGroup;
      } else if (!tabGroup) {
        currentGroup = null;
      }
      out.push({ type: "tab", tab, key: String(tab.name) });
    }
    return out;
  });

  function select(tab: ShadcnTabItem) {
    if (isDisabled(tab) || isActive(tab)) return;
    onValueChange?.(tab.name);
    onChange?.(tab.name);
  }

  async function focusTrigger(tab: ShadcnTabItem) {
    const tabIdx = triggerIndexOf(tab);
    await tick();
    triggerRefs[tabIdx]?.focus?.();
  }

  function onKeydown(e: KeyboardEvent) {
    const enabledTabs = normalizedTabs.filter((t) => !isDisabled(t));
    if (!enabledTabs.length) return;

    const currentIdx = enabledTabs.findIndex((t) => t.name === value);
    const isVertical =
      variant === "sidebar" ||
      variant === "sidebar-soft" ||
      variant === "sidebar-shell" ||
      orientation === "vertical";

    const nextKey = isVertical ? "ArrowDown" : "ArrowRight";
    const prevKey = isVertical ? "ArrowUp" : "ArrowLeft";

    if (e.key === nextKey) {
      e.preventDefault();
      const next = enabledTabs[(currentIdx + 1) % enabledTabs.length];
      select(next);
      focusTrigger(next);
    } else if (e.key === prevKey) {
      e.preventDefault();
      const prev = enabledTabs[(currentIdx - 1 + enabledTabs.length) % enabledTabs.length];
      select(prev);
      focusTrigger(prev);
    } else if (e.key === "Home") {
      e.preventDefault();
      select(enabledTabs[0]);
      focusTrigger(enabledTabs[0]);
    } else if (e.key === "End") {
      e.preventDefault();
      select(enabledTabs[enabledTabs.length - 1]);
      focusTrigger(enabledTabs[enabledTabs.length - 1]);
    }
  }
</script>

{#snippet panelBody(tab: ShadcnTabItem)}
  {#if panels?.[String(tab.name)]}{@render panels[String(tab.name)]()}{:else if panel}{@render panel(tab)}{/if}
{/snippet}

<div class={rootClasses}>
  <div
    class="shadcn-tabs__list"
    role="tablist"
    aria-label={ariaLabel || undefined}
    onkeydown={onKeydown}
  >
    {@render listHeader?.()}

    {#each renderableItems as item (item.key)}
      {#if item.type === "header"}
        <div class="shadcn-tabs__group-header" role="presentation">{item.label}</div>
      {:else}
        <button
          bind:this={triggerRefs[triggerIndexOf(item.tab)]}
          type="button"
          class={[
            "shadcn-tabs__trigger",
            isActive(item.tab) ? "is-active" : "",
            isDisabled(item.tab) ? "is-disabled" : "",
            item.tab.tone ? `is-tone-${item.tab.tone}` : "",
          ]
            .filter(Boolean)
            .join(" ")}
          role="tab"
          id={triggerId(item.tab)}
          aria-selected={isActive(item.tab)}
          aria-controls={panelId(item.tab)}
          aria-disabled={isDisabled(item.tab)}
          tabindex={isActive(item.tab) ? 0 : -1}
          disabled={isDisabled(item.tab)}
          onclick={() => select(item.tab)}
        >
          {#if item.tab.icon}
            <i
              class={`shadcn-tabs__trigger-icon ${item.tab.icon}`}
              style={item.tab.iconColor ? `color: ${item.tab.iconColor};` : undefined}
            ></i>
          {/if}
          <span class="shadcn-tabs__trigger-label">{item.tab.label}</span>
          {#if item.tab.badge != null}
            <span class="shadcn-tabs__trigger-badge">{item.tab.badge}</span>
          {/if}
        </button>
      {/if}
    {/each}
  </div>

  {#if keepAlive}
    {#each normalizedTabs as tab (String(tab.name))}
      {#if wasActivated(tab)}
        <div
          class="shadcn-tabs__panel"
          role="tabpanel"
          id={panelId(tab)}
          aria-labelledby={triggerId(tab)}
          tabindex={isActive(tab) ? 0 : -1}
          hidden={!isActive(tab) || undefined}
          style={isActive(tab) ? undefined : "display: none;"}
        >
          {@render panelBody(tab)}
        </div>
      {/if}
    {/each}
  {:else if activeTab}
    <div
      class="shadcn-tabs__panel"
      role="tabpanel"
      id={panelId(activeTab)}
      aria-labelledby={triggerId(activeTab)}
      tabindex={0}
    >
      {@render panelBody(activeTab)}
    </div>
  {/if}
</div>

// src/angular/shadcn-tabs.component.ts
import { NgTemplateOutlet } from "@angular/common";
import {
  ChangeDetectionStrategy, Component, ContentChildren, ElementRef, EventEmitter,
  Input, OnChanges, OnInit, Output, QueryList, SimpleChanges, TemplateRef, ViewChildren
} from "@angular/core";
import { ArcanaTabPanelDirective } from "./tab-panel.directive";

/**
 * `ShadcnTabsComponent` — Angular port do SFC Vue `ShadcnTabs`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnTabs>`): reproduz `.shadcn-tabs`
 * (+ `--${variant}`, `--${orientation}`, `--flush`), `.shadcn-tabs__list`,
 * `.shadcn-tabs__trigger` (+ `is-active`/`is-disabled`/`is-tone-*`), `__trigger-icon`,
 * `__trigger-label`, `__trigger-badge`, `__group-header` e `.shadcn-tabs__panel`,
 * idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 * - slots nomeados (um por `tab.name`) → diretiva estrutural `*arcanaTabPanel="name"`
 * - slot `#list-header` → `<ng-content select="[arcanaTabsListHeader]">`
 *
 * Nota: `tooltipPlacement` do SFC usa `<el-tooltip>` (Element Plus, Vue-only) — o port
 * Angular renderiza os triggers SEM tooltip (markup do `<button>` idêntico). A prop é
 * aceita mas ignorada nesta fase (paridade com o port React).
 */
export interface ShadcnTabItem {
  name: string | number;
  label: string;
  disabled?: boolean;
  icon?: string;
  iconColor?: string;
  badge?: string | number;
  group?: string;
  tone?: "default" | "danger";
  eager?: boolean;
}

export type ShadcnTabsVariant =
  | "pills" | "underline" | "boxed" | "sidebar" | "sidebar-soft" | "sidebar-shell" | "segmented";

type RenderableItem =
  | { type: "header"; label: string; key: string }
  | { type: "tab"; tab: ShadcnTabItem; key: string };

let uidCounter = 0;

@Component({
  selector: "div[arcanaShadcnTabs]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: {
    "[class]": "rootClass"
  },
  template: `
    <div class="shadcn-tabs__list" role="tablist" [attr.aria-label]="ariaLabel || null" (keydown)="onKeydown($event)">
      <ng-content select="[arcanaTabsListHeader]"></ng-content>

      @for (item of renderableItems; track item.key) {
        @if (item.type === 'header') {
          <div class="shadcn-tabs__group-header" role="presentation">{{ item.label }}</div>
        } @else {
          <button
            #trigger
            type="button"
            [class]="triggerClass(item.tab)"
            role="tab"
            [id]="triggerId(item.tab)"
            [attr.aria-selected]="isActive(item.tab)"
            [attr.aria-controls]="panelId(item.tab)"
            [attr.aria-disabled]="isDisabled(item.tab)"
            [attr.tabindex]="isActive(item.tab) ? 0 : -1"
            [disabled]="isDisabled(item.tab)"
            (click)="select(item.tab)"
          >
            @if (item.tab.icon) {
              <i
                [class]="'shadcn-tabs__trigger-icon ' + item.tab.icon"
                [style.color]="item.tab.iconColor || null"
              ></i>
            }
            <span class="shadcn-tabs__trigger-label">{{ item.tab.label }}</span>
            @if (item.tab.badge != null) {
              <span class="shadcn-tabs__trigger-badge">{{ item.tab.badge }}</span>
            }
          </button>
        }
      }
    </div>

    @if (keepAlive) {
      @for (tab of normalizedTabs; track tab.name) {
        @if (wasActivated(tab)) {
          <div
            class="shadcn-tabs__panel"
            role="tabpanel"
            [id]="panelId(tab)"
            [attr.aria-labelledby]="triggerId(tab)"
            [attr.tabindex]="isActive(tab) ? 0 : -1"
            [hidden]="!isActive(tab) ? true : null"
            [style.display]="isActive(tab) ? null : 'none'"
          >
            <ng-container *ngTemplateOutlet="panelTemplate(tab)"></ng-container>
          </div>
        }
      }
    } @else if (activeTab) {
      <div
        class="shadcn-tabs__panel"
        role="tabpanel"
        [id]="panelId(activeTab)"
        [attr.aria-labelledby]="triggerId(activeTab)"
        tabindex="0"
      >
        <ng-container *ngTemplateOutlet="panelTemplate(activeTab)"></ng-container>
      </div>
    }
  `
})
export class ShadcnTabsComponent implements OnInit, OnChanges {
  @Input({ required: true }) value!: string | number;
  @Input({ required: true }) tabs!: ShadcnTabItem[];
  @Input() variant: ShadcnTabsVariant = "pills";
  @Input() orientation: "horizontal" | "vertical" = "horizontal";
  @Input() ariaLabel = "";
  @Input() keepAlive = false;
  @Input() flush = false;
  /** Aceita, mas não renderiza tooltip (dependência el-tooltip é Vue-only). */
  @Input() tooltipPlacement = "";

  @Output() valueChange = new EventEmitter<string | number>();
  @Output() change = new EventEmitter<string | number>();

  @ViewChildren("trigger") triggerRefs!: QueryList<ElementRef<HTMLButtonElement>>;
  @ContentChildren(ArcanaTabPanelDirective) panels!: QueryList<ArcanaTabPanelDirective>;

  readonly uid = ++uidCounter;
  private activatedTabNames: string[] = [];

  ngOnInit(): void {
    if (this.value != null && this.value !== "") {
      this.activatedTabNames = [String(this.value)];
    }
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"]) {
      const v = changes["value"].currentValue;
      const name = v == null ? "" : String(v);
      if (name && !this.activatedTabNames.includes(name)) {
        this.activatedTabNames.push(name);
      }
    }
  }

  get normalizedTabs(): ShadcnTabItem[] {
    return this.tabs ?? [];
  }

  get activeTab(): ShadcnTabItem | null {
    return this.normalizedTabs.find((t) => t.name === this.value) ?? null;
  }

  private get showsGroupHeaders(): boolean {
    return this.variant === "sidebar-soft" || this.variant === "sidebar-shell";
  }

  get rootClass(): string {
    const isSidebarLike =
      this.variant === "sidebar" || this.variant === "sidebar-soft" || this.variant === "sidebar-shell";
    const effectiveOrientation = isSidebarLike ? "vertical" : this.orientation;
    return [
      "shadcn-tabs",
      `shadcn-tabs--${this.variant}`,
      `shadcn-tabs--${effectiveOrientation}`,
      this.flush ? "shadcn-tabs--flush" : ""
    ].filter(Boolean).join(" ");
  }

  get renderableItems(): RenderableItem[] {
    if (!this.showsGroupHeaders) {
      return this.normalizedTabs.map((t) => ({ type: "tab" as const, tab: t, key: String(t.name) }));
    }
    const out: RenderableItem[] = [];
    let currentGroup: string | null = null;
    for (const tab of this.normalizedTabs) {
      const tabGroup = tab.group ?? null;
      if (tabGroup && tabGroup !== currentGroup) {
        out.push({ type: "header", label: tabGroup, key: `__group__${tabGroup}` });
        currentGroup = tabGroup;
      } else if (!tabGroup) {
        currentGroup = null;
      }
      out.push({ type: "tab", tab, key: String(tab.name) });
    }
    return out;
  }

  isActive(tab: ShadcnTabItem): boolean {
    return tab.name === this.value;
  }

  isDisabled(tab: ShadcnTabItem): boolean {
    return Boolean(tab.disabled);
  }

  wasActivated(tab: ShadcnTabItem): boolean {
    return Boolean(tab.eager) || this.activatedTabNames.includes(String(tab.name));
  }

  triggerId(tab: ShadcnTabItem): string {
    return `shadcn-tabs-${this.uid}-trigger-${String(tab.name)}`;
  }

  panelId(tab: ShadcnTabItem): string {
    return `shadcn-tabs-${this.uid}-panel-${String(tab.name)}`;
  }

  triggerClass(tab: ShadcnTabItem): string {
    return [
      "shadcn-tabs__trigger",
      this.isActive(tab) ? "is-active" : "",
      this.isDisabled(tab) ? "is-disabled" : "",
      tab.tone ? `is-tone-${tab.tone}` : ""
    ].filter(Boolean).join(" ");
  }

  panelTemplate(tab: ShadcnTabItem): TemplateRef<unknown> | null {
    return this.panels?.find((p) => String(p.name) === String(tab.name))?.templateRef ?? null;
  }

  select(tab: ShadcnTabItem): void {
    if (this.isDisabled(tab) || this.isActive(tab)) return;
    this.valueChange.emit(tab.name);
    this.change.emit(tab.name);
  }

  onKeydown(e: KeyboardEvent): void {
    const enabledTabs = this.normalizedTabs.filter((t) => !this.isDisabled(t));
    if (!enabledTabs.length) return;

    const currentIdx = enabledTabs.findIndex((t) => t.name === this.value);
    const isVertical =
      this.variant === "sidebar" ||
      this.variant === "sidebar-soft" ||
      this.variant === "sidebar-shell" ||
      this.orientation === "vertical";

    const nextKey = isVertical ? "ArrowDown" : "ArrowRight";
    const prevKey = isVertical ? "ArrowUp" : "ArrowLeft";

    if (e.key === nextKey) {
      e.preventDefault();
      const next = enabledTabs[(currentIdx + 1) % enabledTabs.length];
      this.select(next);
      this.focusTrigger(next);
      return;
    }
    if (e.key === prevKey) {
      e.preventDefault();
      const prev = enabledTabs[(currentIdx - 1 + enabledTabs.length) % enabledTabs.length];
      this.select(prev);
      this.focusTrigger(prev);
      return;
    }
    if (e.key === "Home") {
      e.preventDefault();
      this.select(enabledTabs[0]);
      this.focusTrigger(enabledTabs[0]);
      return;
    }
    if (e.key === "End") {
      e.preventDefault();
      this.select(enabledTabs[enabledTabs.length - 1]);
      this.focusTrigger(enabledTabs[enabledTabs.length - 1]);
    }
  }

  private focusTrigger(tab: ShadcnTabItem): void {
    const tabIdx = this.normalizedTabs.findIndex((t) => t.name === tab.name);
    requestAnimationFrame(() => {
      this.triggerRefs?.get(tabIdx)?.nativeElement?.focus?.();
    });
  }
}
