// src/react/ShadcnSummaryTiles.tsx
import type { CSSProperties, ReactNode } from "react";

/**
 * `<ShadcnSummaryTiles>` — React port. Container grid pros tiles de resumo. Reproduz
 * `<div class="shadcn-summary-tiles" style="--shadcn-summary-tiles-cols: N">`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 */
export interface ShadcnSummaryTilesProps {
    columns?: number | string;
    children?: ReactNode;
    className?: string;
}

export function ShadcnSummaryTiles({
    columns = 3,
    children,
    className,
}: ShadcnSummaryTilesProps) {
    const style = {
        "--shadcn-summary-tiles-cols": String(columns),
    } as CSSProperties;

    return (
        <div
            className={["shadcn-summary-tiles", className ?? ""]
                .filter(Boolean)
                .join(" ")}
            style={style}
        >
            {children}
        </div>
    );
}

// src/angular/shadcn-summary-tiles.component.ts
import {
  ChangeDetectionStrategy, Component, Input
} from "@angular/core";

/**
 * `ShadcnSummaryTilesComponent` — Angular port do SFC Vue `ShadcnSummaryTiles`.
 * Container grid pros tiles de resumo.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnSummaryTiles>`): reproduz
 * `.shadcn-summary-tiles` com `style="--shadcn-summary-tiles-cols: N"`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - slot default → `<ng-content>`
 */
@Component({
  selector: "div[arcanaShadcnSummaryTiles]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.--shadcn-summary-tiles-cols]": "columnsVar"
  },
  template: `<ng-content></ng-content>`
})
export class ShadcnSummaryTilesComponent {
  @Input() columns: number | string = 3;
  @Input() className = "";

  get columnsVar(): string {
    return String(this.columns);
  }

  get rootClass(): string {
    return ["shadcn-summary-tiles", this.className].filter(Boolean).join(" ");
  }
}
