// src/react/ArcanaTable.tsx
import type { ReactNode } from "react";

/**
 * `<ArcanaTable>` — React port. Tabela estática (dados locais) shadcn. Reproduz
 * `<div class="arcana-table-wrap"><table class="arcana-table">`, o `thead`/`tbody`/`tfoot`,
 * `__th--right`/`__td--right`, `__empty` e `__foot`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slot de célula `#cell-<key>` → `col.render?({ row, value, index })`
 * - slot `#footer` → prop `footer` (ReactNode)
 */
export interface ArcanaTableColumn {
    key: string;
    label: string;
    width?: string;
    align?: "left" | "right";
    valueGetter?: (value: any, row: any, index: number) => any;
    /** Render custom da célula (equivale ao slot `#cell-<key>` do SFC). */
    render?: (args: { row: any; value: any; index: number }) => ReactNode;
}

export interface ArcanaTableProps {
    columns: ArcanaTableColumn[];
    rows?: any[];
    emptyText?: string;
    footer?: ReactNode;
    className?: string;
}

export function ArcanaTable({
    columns,
    rows = [],
    emptyText = "Nenhum registro.",
    footer,
    className,
}: ArcanaTableProps) {
    const formatCell = (row: any, col: ArcanaTableColumn, index: number): any => {
        const value = row?.[col.key];
        if (col.valueGetter) return col.valueGetter(value, row, index);
        return value ?? "—";
    };

    return (
        <div
            className={["arcana-table-wrap", className ?? ""]
                .filter(Boolean)
                .join(" ")}
        >
            <table className="arcana-table">
                <thead>
                    <tr>
                        {columns.map((col) => (
                            <th
                                key={col.key}
                                style={col.width ? { width: col.width } : undefined}
                                className={
                                    col.align === "right"
                                        ? "arcana-table__th--right"
                                        : undefined
                                }
                            >
                                {col.label}
                            </th>
                        ))}
                    </tr>
                </thead>
                <tbody>
                    {!rows.length ? (
                        <tr>
                            <td colSpan={columns.length} className="arcana-table__empty">
                                {emptyText}
                            </td>
                        </tr>
                    ) : (
                        rows.map((row, i) => (
                            <tr key={i}>
                                {columns.map((col) => (
                                    <td
                                        key={col.key}
                                        className={
                                            col.align === "right"
                                                ? "arcana-table__td--right"
                                                : undefined
                                        }
                                    >
                                        {col.render
                                            ? col.render({
                                                  row,
                                                  value: row?.[col.key],
                                                  index: i,
                                              })
                                            : formatCell(row, col, i)}
                                    </td>
                                ))}
                            </tr>
                        ))
                    )}
                </tbody>
                {footer ? (
                    <tfoot className="arcana-table__foot">{footer}</tfoot>
                ) : null}
            </table>
        </div>
    );
}

// src/svelte/ArcanaTable.svelte
<script lang="ts" module>
  import type { Snippet } from "svelte";

  export interface ArcanaTableColumn {
    key: string;
    label: string;
    width?: string;
    align?: "left" | "right";
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    valueGetter?: (value: any, row: any, index: number) => any;
    /** Render custom da célula (equivale ao slot `#cell-<key>` do SFC). */
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    render?: Snippet<[{ row: any; value: any; index: number }]>;
  }
</script>

<script lang="ts">
  /**
   * `<ArcanaTable>` — Svelte 5 port. Tabela estática (dados locais) shadcn. Reproduz
   * `<div class="arcana-table-wrap"><table class="arcana-table">`, o `thead`/`tbody`/`tfoot`,
   * `__th--right`/`__td--right`, `__empty` e `__foot`, idêntico ao SFC.
   *
   * Equivalências: slot de célula `#cell-<key>` → `col.render` (snippet);
   * slot `#footer` → snippet `footer`.
   */
  let {
    columns,
    rows = [],
    emptyText = "Nenhum registro.",
    footer,
    class: className = "",
  }: {
    columns: ArcanaTableColumn[];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    rows?: any[];
    emptyText?: string;
    footer?: Snippet;
    class?: string;
  } = $props();

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  function formatCell(row: any, col: ArcanaTableColumn, index: number): any {
    const value = row?.[col.key];
    if (col.valueGetter) return col.valueGetter(value, row, index);
    return value ?? "—";
  }
</script>

<div class={["arcana-table-wrap", className].filter(Boolean).join(" ")}>
  <table class="arcana-table">
    <thead>
      <tr>
        {#each columns as col (col.key)}
          <th
            style={col.width ? `width:${col.width};` : undefined}
            class={col.align === "right" ? "arcana-table__th--right" : undefined}
          >
            {col.label}
          </th>
        {/each}
      </tr>
    </thead>
    <tbody>
      {#if !rows.length}
        <tr>
          <td colspan={columns.length} class="arcana-table__empty">{emptyText}</td>
        </tr>
      {:else}
        {#each rows as row, i (i)}
          <tr>
            {#each columns as col (col.key)}
              <td class={col.align === "right" ? "arcana-table__td--right" : undefined}>
                {#if col.render}{@render col.render({ row, value: row?.[col.key], index: i })}{:else}{formatCell(row, col, i)}{/if}
              </td>
            {/each}
          </tr>
        {/each}
      {/if}
    </tbody>
    {#if footer}
      <tfoot class="arcana-table__foot">{@render footer()}</tfoot>
    {/if}
  </table>
</div>
