// src/vue/components/ArcanaSegmentedOptions.vue
<template>
    <div
        class="arcana-segmented-options"
        :class="{ 'is-compact': compact, 'is-squared': squared, 'is-disabled': disabled }"
        :style="activeColor ? { '--seg-active': activeColor } : undefined"
        role="radiogroup"
        :aria-label="ariaLabel || undefined"
    >
        <button
            v-for="opt in normalizedOptions"
            :key="String(opt.value)"
            type="button"
            class="arcana-segmented-options__option"
            :class="{ 'is-active': opt.value === modelValue }"
            role="radio"
            :aria-checked="opt.value === modelValue"
            :disabled="disabled || opt.disabled"
            @click="select(opt)"
        >
            <span v-if="radio" class="arcana-segmented-options__radio" aria-hidden="true"></span>
            <i
                v-if="opt.icon"
                :class="['arcana-segmented-options__icon', opt.icon]"
                :style="opt.iconColor ? { color: opt.iconColor } : undefined"
            ></i>
            <span>{{ opt.label }}</span>
        </button>

        <span v-if="!normalizedOptions.length" class="arcana-segmented-options__empty">
            {{ emptyText }}
        </span>
    </div>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

interface SegmentedOption {
    label: string
    value: string | number
    disabled?: boolean
    /** Classe do ícone (ex: FontAwesome `fa-solid fa-truck`). */
    icon?: string
    /**
     * Cor do ícone desta opção. Qualquer string CSS válida (hex, rgb, `var(...)`).
     * Aplicada como inline style no `<i>`, então vence o CSS e permanece válida
     * inclusive quando a opção está ativa (fundo escuro/colorido). Sem valor, o
     * ícone herda a cor do texto do segmento.
     */
    iconColor?: string
}

/**
 * `<ArcanaSegmentedOptions>` — segmented control de N opções (irmão do `<ArcanaSwitchSegmented>`,
 * que é binário). Renderiza um botão por opção dentro de uma cápsula; o item ativo fica destacado
 * (bg escuro, texto branco). Use quando há uma lista pequena de escolhas mutuamente exclusivas
 * (ex: tipo de entrega, modo de exibição) e um select seria pesado demais visualmente.
 *
 * Diferente do `ArcanaSwitchSegmented` (boolean, 2 metades com indicador deslizante), este aceita
 * qualquer número de opções via `options` e usa `modelValue` arbitrário (string/number).
 *
 * API:
 * - `modelValue` (v-model) — valor da opção ativa
 * - `options` — `Array<{ label, value, disabled?, icon?, iconColor? }>` (`iconColor` colore o
 *   ícone daquela opção individualmente, inclusive quando ela está ativa)
 * - `disabled` — desabilita o grupo inteiro
 * - `compact` — altura/fonte reduzidas (uso inline em forms densos)
 * - `squared` — cantos menos arredondados (radius moderado no lugar do pill)
 * - `emptyText` — texto exibido quando `options` está vazio
 *
 * Acessibilidade: `role="radiogroup"` + `role="radio"` com `aria-checked` por opção.
 */
export default {
    name: 'ArcanaSegmentedOptions',

    emits: ['update:modelValue', 'change'],

    props: {
        modelValue: {
            type: [String, Number, null] as PropType<string | number | null>,
            default: null,
        },
        options: {
            type: Array as PropType<SegmentedOption[]>,
            default: () => [],
        },
        disabled: {
            type: Boolean,
            default: false,
        },
        compact: {
            type: Boolean,
            default: false,
        },
        squared: {
            type: Boolean,
            default: false,
        },
        /**
         * Cor do segmento ativo. Qualquer string CSS válida (hex, rgb, var(...)). Default
         * `#18181b` (preto zinc). O texto do ativo permanece branco — use cor escura o
         * suficiente pra manter contraste.
         */
        activeColor: {
            type: String,
            default: '',
        },
        /**
         * Mostra um radio button (círculo) à esquerda de cada opção, preenchido na ativa.
         * Reforça visualmente a seleção além do destaque de fundo.
         */
        radio: {
            type: Boolean,
            default: false,
        },
        /**
         * Quando `true`, assim que as `options` carregam e nenhuma estiver selecionada
         * (`modelValue` vazio), seleciona automaticamente a primeira opção HABILITADA como
         * default. Útil quando a lista é dinâmica (ex: tipos de entrega vindos do backend) e
         * sempre deve haver uma escolha ativa. Opt-in pra não surpreender usos que querem
         * começar "sem seleção".
         */
        autoSelectFirst: {
            type: Boolean,
            default: false,
        },
        ariaLabel: {
            type: String,
            default: '',
        },
        emptyText: {
            type: String,
            default: 'Sem opções disponíveis',
        },
    },

    computed: {
        normalizedOptions(): SegmentedOption[] {
            return this.options ?? []
        },
    },

    watch: {
        // `options` é uma nova referência a cada carga (computed no caller) → dispara quando
        // a lista dinâmica chega do backend.
        options() {
            this.autoSelectDefault()
        },
    },

    mounted() {
        this.autoSelectDefault()
    },

    methods: {
        select(opt: SegmentedOption) {
            if (this.disabled || opt.disabled || opt.value === this.modelValue) return
            this.$emit('update:modelValue', opt.value)
            this.$emit('change', opt.value)
        },

        autoSelectDefault() {
            if (!this.autoSelectFirst || this.disabled) return

            const hasValue = this.modelValue !== null && this.modelValue !== undefined && this.modelValue !== ''
            if (hasValue) return

            const first = this.normalizedOptions.find((o) => !o.disabled)
            if (!first) return

            this.$emit('update:modelValue', first.value)
            this.$emit('change', first.value)
        },
    },
} as Component
</script>

// src/svelte/ArcanaSegmentedOptions.svelte
<script lang="ts">
  /**
   * `<ArcanaSegmentedOptions>` — Svelte 5 port. Segmented control de N opções. Reproduz
   * `<div class="arcana-segmented-options">` (+ `is-compact`/`is-squared`/`is-disabled`),
   * cada `<button class="arcana-segmented-options__option">` (+ `is-active`), o
   * `__radio`/`__icon` opcionais e o `__empty`, idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - `modelValue` (v-model) → prop `value` + `onValueChange`; `emit('change')` → `onChange`
   * - `--seg-active` inline style preservado
   * - `iconColor` por opção → inline style `color` no `<i>` (vence o CSS, inclusive na ativa)
   */
  export interface SegmentedOption {
    label: string;
    value: string | number;
    disabled?: boolean;
    /** Classe do ícone (ex: FontAwesome `fa-solid fa-truck`). */
    icon?: string;
    /**
     * Cor do ícone desta opção. Qualquer string CSS válida (hex, rgb, `var(...)`).
     * Aplicada como inline style no `<i>`, então vence o CSS e permanece válida
     * inclusive quando a opção está ativa (fundo escuro/colorido). Sem valor, o
     * ícone herda a cor do texto do segmento.
     */
    iconColor?: string;
  }

  let {
    value = null,
    options = [],
    disabled = false,
    compact = false,
    squared = false,
    activeColor = "",
    radio = false,
    autoSelectFirst = false,
    ariaLabel = "",
    emptyText = "Sem opções disponíveis",
    onValueChange,
    onChange,
    class: className = "",
  }: {
    value?: string | number | null;
    options?: SegmentedOption[];
    disabled?: boolean;
    compact?: boolean;
    squared?: boolean;
    activeColor?: string;
    radio?: boolean;
    autoSelectFirst?: boolean;
    ariaLabel?: string;
    emptyText?: string;
    onValueChange?: (value: string | number) => void;
    onChange?: (value: string | number) => void;
    class?: string;
  } = $props();

  const normalizedOptions = $derived(options ?? []);

  function select(opt: SegmentedOption) {
    if (disabled || opt.disabled || opt.value === value) return;
    onValueChange?.(opt.value);
    onChange?.(opt.value);
  }

  // `autoSelectFirst`: quando as options carregam e nada está selecionado, seleciona a
  // 1ª habilitada. Reproduz o watch(options)+mounted do SFC.
  $effect(() => {
    // Depende de `options` (nova referência a cada carga dinâmica).
    void options;
    if (!autoSelectFirst || disabled) return;
    const hasValue = value !== null && value !== undefined && value !== "";
    if (hasValue) return;
    const first = normalizedOptions.find((o) => !o.disabled);
    if (!first) return;
    onValueChange?.(first.value);
    onChange?.(first.value);
  });

  const rootClasses = $derived(
    [
      "arcana-segmented-options",
      compact ? "is-compact" : "",
      squared ? "is-squared" : "",
      disabled ? "is-disabled" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );
</script>

<div
  class={rootClasses}
  style={activeColor ? `--seg-active: ${activeColor};` : undefined}
  role="radiogroup"
  aria-label={ariaLabel || undefined}
>
  {#each normalizedOptions as opt (String(opt.value))}
    <button
      type="button"
      class={["arcana-segmented-options__option", opt.value === value ? "is-active" : ""]
        .filter(Boolean)
        .join(" ")}
      role="radio"
      aria-checked={opt.value === value}
      disabled={disabled || opt.disabled}
      onclick={() => select(opt)}
    >
      {#if radio}<span class="arcana-segmented-options__radio" aria-hidden="true"></span>{/if}
      {#if opt.icon}<i
          class={`arcana-segmented-options__icon ${opt.icon}`}
          style={opt.iconColor ? `color: ${opt.iconColor};` : undefined}
        ></i>{/if}
      <span>{opt.label}</span>
    </button>
  {/each}

  {#if !normalizedOptions.length}
    <span class="arcana-segmented-options__empty">{emptyText}</span>
  {/if}
</div>
