// src/react/ArcanaSettingsEditableField.tsx
import { useMemo, useRef, useState, type ReactNode } from "react";
import { ArcanaSettingsListItem } from "./ArcanaSettingsList";
import {
    ArcanaEditFieldDialog,
    type ArcanaEditFieldDialogHandle,
} from "./ArcanaEditFieldDialog";
import { ArcanaInput } from "./ArcanaInput";
import { ArcanaSelect } from "./ArcanaSelect";
import { ArcanaInputCurrency } from "./ArcanaInputCurrency";
import { CurrencyFormatter } from "../core/currency";

/**
 * `<ArcanaSettingsEditableField>` — React port do SFC Vue. Item smart de
 * `<ArcanaSettingsList>` que combina display read-only + botão "Alterar" + modal de
 * edição (`<ArcanaEditFieldDialog>`) numa única tag.
 *
 * Equivalências Vue → React:
 * - `v-model` (`modelValue`) → `value` + `onValueChange`; `emit('save')` → `onSave`
 * - buffer (`bufferValue`) snapshotado ao abrir; cancelar descarta; salvar emite
 *   `onValueChange(buffer)` + `onSave(buffer)` e fecha (idêntico ao SFC)
 * - `<Teleport>` do modal → o próprio `<ArcanaEditFieldDialog>` React já usa portal
 *
 * FormGroup: o SFC referencia um `<FormGroup>` GLOBAL do app host (não importado
 * localmente). No port, o wrapper de campo é REIMPLEMENTADO minimamente (label + input,
 * classe `demo-form-group` — mesma do stub usado na docs). Passe a render-prop
 * `formGroup` pra substituir por um wrapper próprio (kit de form do app consumidor).
 */
interface SelectOption {
    label: string;
    value: string | number | boolean | null;
}

export interface ArcanaSettingsEditableFieldProps {
    value?: string | number | boolean | null;
    label: string;
    caption?: string;
    type?: "text" | "currency" | "number" | "select";
    options?: SelectOption[];
    disabled?: boolean;
    nested?: boolean;
    displayFormatter?: (value: unknown) => string;
    modalTitle?: string;
    modalDescription?: string;
    inputLabel?: string;
    inputPlaceholder?: string;
    min?: number | string;
    max?: number | string;
    emptyText?: string;
    /** Substitui o `#label` slot do item (HTML custom com badge etc). */
    labelSlot?: ReactNode;
    /** Wrapper do campo dentro do modal. Default: label + input (classe `demo-form-group`). */
    formGroup?: (opts: { label: string; children: ReactNode }) => ReactNode;
    onValueChange?: (value: string | number | boolean | null) => void;
    onSave?: (value: string | number | boolean | null) => void;
}

function defaultFormGroup({ label, children }: { label: string; children: ReactNode }): ReactNode {
    return (
        <div className="demo-form-group">
            {label && <label className="demo-form-group__label">{label}</label>}
            {children}
        </div>
    );
}

export function ArcanaSettingsEditableField({
    value = null,
    label,
    caption = "",
    type = "text",
    options = [],
    disabled = false,
    nested = false,
    displayFormatter,
    modalTitle = "",
    modalDescription = "",
    inputLabel = "",
    inputPlaceholder = "",
    min,
    max,
    emptyText = "Não definido",
    labelSlot,
    formGroup = defaultFormGroup,
    onValueChange,
    onSave,
}: ArcanaSettingsEditableFieldProps) {
    const modalRef = useRef<ArcanaEditFieldDialogHandle | null>(null);
    const [bufferValue, setBufferValue] = useState<string | number | boolean | null>(null);

    const isEmpty = value === null || value === undefined || value === "";

    const displayValue = useMemo(() => {
        if (isEmpty) return emptyText;
        if (displayFormatter) return displayFormatter(value);
        if (type === "currency") return CurrencyFormatter.format(value as number);
        if (type === "select") {
            const opt = options.find((o) => o.value === value);
            return opt?.label ?? String(value);
        }
        return String(value);
    }, [isEmpty, emptyText, displayFormatter, type, value, options]);

    const valueClasses = ["arcana-settings-list__current-value"];
    if (isEmpty) valueClasses.push("arcana-settings-list__current-value--empty");

    const resolvedModalTitle = modalTitle || `Alterar ${label}`;
    const resolvedInputLabel = inputLabel || label;

    const openModal = () => {
        setBufferValue(value);
        modalRef.current?.show();
    };

    const handleSave = () => {
        onValueChange?.(bufferValue);
        onSave?.(bufferValue);
        modalRef.current?.hide();
    };

    let input: ReactNode = null;
    if (type === "text") {
        input = (
            <ArcanaInput
                value={bufferValue as string | number | null}
                placeholder={inputPlaceholder}
                onValueChange={(v) => setBufferValue(v)}
            />
        );
    } else if (type === "currency") {
        input = (
            <ArcanaInputCurrency
                value={bufferValue as string | number}
                onValueChange={(v) => setBufferValue(v)}
            />
        );
    } else if (type === "number") {
        input = (
            <ArcanaInput
                value={bufferValue as string | number | null}
                type="number"
                min={min}
                max={max}
                placeholder={inputPlaceholder}
                onValueChange={(v) => setBufferValue(v)}
            />
        );
    } else if (type === "select") {
        input = (
            <ArcanaSelect
                value={bufferValue}
                options={options}
                onValueChange={(v) => setBufferValue(v as string | number | boolean | null)}
            />
        );
    }

    return (
        <ArcanaSettingsListItem
            label={labelSlot ?? label}
            caption={caption}
            disabled={disabled}
            nested={nested}
        >
            <span className={valueClasses.join(" ")}>{displayValue}</span>
            <button
                className="arcana-settings-list__edit-btn"
                type="button"
                disabled={disabled}
                onClick={openModal}
            >
                <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                >
                    <path d="M12 20h9" />
                    <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z" />
                </svg>
                Alterar
            </button>

            <ArcanaEditFieldDialog
                ref={modalRef}
                title={resolvedModalTitle}
                description={modalDescription}
                onSave={handleSave}
            >
                {formGroup({ label: resolvedInputLabel, children: input })}
            </ArcanaEditFieldDialog>
        </ArcanaSettingsListItem>
    );
}

// src/svelte/ArcanaSettingsEditableField.svelte
<script lang="ts" module>
  export interface EditableFieldSelectOption {
    label: string;
    value: string | number | boolean | null;
  }
</script>

<script lang="ts">
  /**
   * `<ArcanaSettingsEditableField>` — Svelte 5 port do SFC Vue. Item smart de
   * `<ArcanaSettingsList>` que combina display read-only + botão "Alterar" + modal de
   * edição (`<ArcanaEditFieldDialog>`) numa única tag.
   *
   * Equivalências Vue → Svelte 5:
   * - `v-model` (`modelValue`) → prop `value` + `onValueChange`; `emit('save')` → `onSave`
   * - buffer (`bufferValue`) snapshotado ao abrir; cancelar descarta; salvar emite
   *   `onValueChange(buffer)` + `onSave(buffer)` e fecha (idêntico ao SFC)
   * - `<Teleport>` do modal → o próprio `<ArcanaEditFieldDialog>` já usa portal
   *
   * FormGroup: o SFC referencia um `<FormGroup>` GLOBAL do app host (não portável). No
   * Svelte, o campo do modal é envolvido por um wrapper mínimo (`demo-form-group`, label +
   * input). Passe o snippet `formGroup` (recebe `{ label, input }`, onde `input` é um snippet
   * com o input já ligado ao buffer) pra substituir pelo kit de form do app consumidor —
   * mesma ideia da render-prop `formGroup` do port React e do `TemplateRef` do Angular.
   */
  import type { Snippet } from "svelte";
  import ArcanaSettingsListItem from "./ArcanaSettingsListItem.svelte";
  import ArcanaEditFieldDialog from "./ArcanaEditFieldDialog.svelte";
  import ArcanaInput from "./ArcanaInput.svelte";
  import ArcanaSelect from "./ArcanaSelect.svelte";
  import ArcanaInputCurrency from "./ArcanaInputCurrency.svelte";
  import { CurrencyFormatter } from "../core/currency";

  let {
    value = null,
    label,
    caption = "",
    type = "text",
    options = [],
    disabled = false,
    nested = false,
    displayFormatter,
    modalTitle = "",
    modalDescription = "",
    inputLabel = "",
    inputPlaceholder = "",
    min,
    max,
    emptyText = "Não definido",
    labelSlot,
    formGroup,
    onValueChange,
    onSave,
  }: {
    value?: string | number | boolean | null;
    label: string;
    caption?: string;
    type?: "text" | "currency" | "number" | "select";
    options?: EditableFieldSelectOption[];
    disabled?: boolean;
    nested?: boolean;
    displayFormatter?: (value: unknown) => string;
    modalTitle?: string;
    modalDescription?: string;
    inputLabel?: string;
    inputPlaceholder?: string;
    min?: number | string;
    max?: number | string;
    emptyText?: string;
    /** Substitui o `#label` slot do item (HTML custom com badge etc). */
    labelSlot?: Snippet;
    /** Wrapper do campo dentro do modal. Default: label + input (classe `demo-form-group`). */
    formGroup?: Snippet<[{ label: string; input: Snippet }]>;
    onValueChange?: (value: string | number | boolean | null) => void;
    onSave?: (value: string | number | boolean | null) => void;
  } = $props();

  let modal: ArcanaEditFieldDialog;
  let bufferValue = $state<string | number | boolean | null>(null);

  const isEmpty = $derived(value === null || value === undefined || value === "");

  const displayValue = $derived.by(() => {
    if (isEmpty) return emptyText;
    if (displayFormatter) return displayFormatter(value);
    if (type === "currency") return CurrencyFormatter.format(value as number);
    if (type === "select") {
      const opt = options.find((o) => o.value === value);
      return opt?.label ?? String(value);
    }
    return String(value);
  });

  const valueClasses = $derived(
    [
      "arcana-settings-list__current-value",
      isEmpty ? "arcana-settings-list__current-value--empty" : "",
    ]
      .filter(Boolean)
      .join(" ")
  );

  const resolvedModalTitle = $derived(modalTitle || `Alterar ${label}`);
  const resolvedInputLabel = $derived(inputLabel || label);

  function openModal() {
    bufferValue = value;
    modal?.show();
  }

  function handleSave() {
    onValueChange?.(bufferValue);
    onSave?.(bufferValue);
    modal?.hide();
  }
</script>

{#snippet inputSnippet()}
  {#if type === "text"}
    <ArcanaInput
      value={bufferValue as string | number | null}
      placeholder={inputPlaceholder}
      onValueChange={(v) => (bufferValue = v)}
    />
  {:else if type === "currency"}
    <ArcanaInputCurrency
      value={bufferValue as string | number}
      onValueChange={(v) => (bufferValue = v)}
    />
  {:else if type === "number"}
    <ArcanaInput
      value={bufferValue as string | number | null}
      type="number"
      {min}
      {max}
      placeholder={inputPlaceholder}
      onValueChange={(v) => (bufferValue = v)}
    />
  {:else if type === "select"}
    <ArcanaSelect
      value={bufferValue}
      {options}
      onValueChange={(v) => (bufferValue = v as string | number | boolean | null)}
    />
  {/if}
{/snippet}

<ArcanaSettingsListItem label={labelSlot ?? label} {caption} {disabled} {nested}>
  <span class={valueClasses}>{displayValue}</span>
  <button
    class="arcana-settings-list__edit-btn"
    type="button"
    {disabled}
    onclick={openModal}
  >
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">
      <path d="M12 20h9" />
      <path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z" />
    </svg>
    Alterar
  </button>

  <ArcanaEditFieldDialog
    bind:this={modal}
    title={resolvedModalTitle}
    description={modalDescription}
    onSave={handleSave}
  >
    {#if formGroup}
      {@render formGroup({ label: resolvedInputLabel, input: inputSnippet })}
    {:else}
      <div class="demo-form-group">
        {#if resolvedInputLabel}
          <label class="demo-form-group__label">{resolvedInputLabel}</label>
        {/if}
        {@render inputSnippet()}
      </div>
    {/if}
  </ArcanaEditFieldDialog>
</ArcanaSettingsListItem>
