// src/vue/components/ArcanaContextMenuItem.vue
<template>
    <div v-if="divided" class="arcana-context-menu-item__separator"></div>

    <button
        type="button"
        class="arcana-context-menu-item"
        :class="[
            variant ? `arcana-context-menu-item--${variant}` : null,
            { 'is-disabled': disabled },
        ]"
        :disabled="disabled"
        role="menuitem"
        tabindex="-1"
        @click="handleClick"
    >
        <i v-if="icon" :class="['arcana-context-menu-item__icon', icon]" aria-hidden="true"></i>
        <span class="arcana-context-menu-item__label"><slot/></span>
        <span v-if="suffix || $slots.suffix" class="arcana-context-menu-item__suffix">
            <slot name="suffix">{{ suffix }}</slot>
        </span>
    </button>
</template>

<script lang="ts">
import type { Component } from "vue"
import type { ArcanaContextMenuVariant } from "../../core/context-menu"

/**
 * Item do `<ArcanaContextMenu>`: ícone + label + (opcional) atalho no `suffix`.
 *
 * Espelha o `ArcanaDropdownItem`, com duas diferenças:
 * - `tabindex="-1"`: o painel é quem tem o foco; ↑/↓ movem o foco entre os itens
 *   (roving tabindex do padrão WAI-ARIA de menu).
 * - fecha o menu chamando `close()` do contexto injetado (`arcanaContextMenu`),
 *   em vez do CustomEvent do dropdown.
 *
 * `divided` insere um separador ANTES do item. `closeOnClick` (default true)
 * fecha o menu depois do handler — desligue em itens que expandem algo inline.
 *
 * Emite `click` (MouseEvent cru) e `select` (ativação semântica: também dispara
 * pelo Enter/Espaço, que o painel converte em clique).
 */
export default {
    name: 'ArcanaContextMenuItem',

    props: {
        icon: { type: String, default: '' },
        /** Atalho exibido à direita (ex: "⌘C"). Também aceita o slot `#suffix`. */
        suffix: { type: String, default: '' },
        variant: {
            type: String as () => ArcanaContextMenuVariant,
            default: 'default',
        },
        disabled: { type: Boolean, default: false },
        /** Separador acima deste item. */
        divided: { type: Boolean, default: false },
        closeOnClick: { type: Boolean, default: true },
    },

    // Contexto do `<ArcanaContextMenu>` pai. Default `null` pra permitir uso solto.
    inject: {
        arcanaContextMenu: { default: null },
    },

    emits: ['click', 'select'],

    methods: {
        handleClick(event: MouseEvent) {
            if (this.disabled) return
            this.$emit('click', event)
            this.$emit('select', event)
            if (this.closeOnClick) {
                ((this as any).arcanaContextMenu as { close: () => void } | null)?.close()
            }
        },
    },
} as Component
</script>

// src/svelte/ArcanaContextMenuItem.svelte
<script lang="ts">
  /**
   * `<ArcanaContextMenuItem>` — Svelte 5 port do SFC Vue. Item do
   * `<ArcanaContextMenu>`: ícone + label + (opcional) atalho no `suffix`.
   *
   * Equivalências Vue → Svelte 5:
   * - `inject('arcanaContextMenu')` → `getContext(CONTEXT_MENU_CONTEXT)`
   * - slot default → snippet `children`; slot `#suffix` → `suffix` (string OU snippet)
   * - `emit('click')` / `emit('select')` → callbacks `onClick` / `onSelect`
   *
   * `tabindex="-1"`: quem tem o foco é o painel; ↑/↓ movem o foco entre os itens
   * (roving tabindex do padrão WAI-ARIA de menu).
   */
  import type { Snippet } from "svelte";
  import { getContext } from "svelte";
  import {
    CONTEXT_MENU_CONTEXT,
    type ContextMenuContextValue,
  } from "./context-menu-context";
  import type { ArcanaContextMenuVariant } from "../core/context-menu";

  let {
    icon = "",
    suffix = undefined,
    variant = "default",
    disabled = false,
    divided = false,
    closeOnClick = true,
    children,
    onClick,
    onSelect,
  }: {
    icon?: string;
    suffix?: string | Snippet;
    variant?: ArcanaContextMenuVariant;
    disabled?: boolean;
    divided?: boolean;
    closeOnClick?: boolean;
    children?: Snippet;
    onClick?: (e: MouseEvent) => void;
    onSelect?: (e: MouseEvent) => void;
  } = $props();

  // Contexto do `<ArcanaContextMenu>` pai (fallback quando usado solto).
  const ctx = getContext<ContextMenuContextValue | undefined>(CONTEXT_MENU_CONTEXT);

  const classes = $derived(
    [
      "arcana-context-menu-item",
      variant ? `arcana-context-menu-item--${variant}` : "",
      disabled ? "is-disabled" : "",
    ]
      .filter(Boolean)
      .join(" ")
  );

  function handleClick(e: MouseEvent) {
    if (disabled) return;
    onClick?.(e);
    onSelect?.(e);
    if (closeOnClick) ctx?.close();
  }
</script>

{#if divided}
  <div class="arcana-context-menu-item__separator"></div>
{/if}

<button
  type="button"
  class={classes}
  {disabled}
  role="menuitem"
  tabindex="-1"
  onclick={handleClick}
>
  {#if icon}
    <i class={`arcana-context-menu-item__icon ${icon}`} aria-hidden="true"></i>
  {/if}
  <span class="arcana-context-menu-item__label">{@render children?.()}</span>
  {#if suffix}
    <span class="arcana-context-menu-item__suffix">
      {#if typeof suffix === "function"}{@render suffix()}{:else}{suffix}{/if}
    </span>
  {/if}
</button>
