// src/vue/components/ArcanaInputCurrency.vue
<template>
    <div :class="shadcn ? ['icur-arcana-field', { 'is-disabled': disabled }] : (showIcon ? 'input-group' : '')">
        <slot name="prepend">
            <span class="input-group-addon" v-if="showIcon && !shadcn"><i :class="icon"></i></span>
            <span class="icur-arcana-field__icon" v-if="showIcon && shadcn"><i :class="icon"></i></span>
        </slot>

        <input
            v-show="!disabled"
            ref="input"
            type="text"
            inputmode="decimal"
            :class="[shadcn ? 'icur-arcana-input' : 'form-control', { 'has-icon': shadcn && showIcon }, $attrs.class]"
            :name="name"
            :value="display"
            @input="onInput"
            @keyup.enter="$emit('enter', $event)"
            @keyup="keyUp"
            @change="$emit('change', $event)"
            @blur="$emit('blur', $event)"
        />

        <input disabled :class="[shadcn ? 'icur-arcana-input' : 'form-control', { 'has-icon': shadcn && showIcon }, 'full-width']" v-show="disabled" type="text" :value="formattedCurrency">

        <slot name="append"></slot>
    </div>
</template>

<script lang="ts">
import {
    CurrencyFormatter,
    currencyDigitsFromValue,
    formatCurrencyDigits,
} from "../../core/currency"
import type {Component} from "@vue/runtime-core"

export default {
    emits: ['change', 'enter', 'blur', 'update:modelValue'],
    inheritAttrs: false,

    props: {
        disabled: {
            type: [Boolean, Number],
            default: false
        },
        allowBlank: {
            type: Boolean,
            default: false,
        },
        fraction: {
            type: Number,
            default: 2
        },
        name: String,
        modelValue: [String, Number],
        showIcon: {
            type: Boolean,
            default: true
        },
        prefix: {
            type: String,
            default: ""
        },
        icon: {
            type: String,
            default: "icon-coin-dollar"
        },
        max: {
            type: Number,
            default: Number.MAX_SAFE_INTEGER
        },
        min: {
            type: Number,
        },
        formatCurrency: {
            type: Boolean,
            default: true
        },
        /**
         * Estilo shadcn (palette zinc, igual `<ArcanaInput>`). Quando `true`, troca o
         * `form-control` Bootstrap pelo input shadcn e esconde o addon de ícone `$`.
         */
        shadcn: {
            type: Boolean,
            default: false,
        },
    },

    computed: {
        /**
         * Texto exibido no input. Vem do mesmo core que React, Angular e Svelte
         * usam — antes este port delegava à `v-money3`, o que custava uma
         * dependência de runtime e fazia do Vue a única implementação diferente.
         */
        display(): string {
            const digits = currencyDigitsFromValue(this.modelValue, this.fraction)
            return formatCurrencyDigits(digits, this.fraction, this.prefix)
        },

        formattedCurrency() {
            if (!this.formatCurrency) {
                return this.modelValue
            }

            return CurrencyFormatter.format(this.modelValue || 0)
        }
    },

    data() {
        return {
            displayBlankValue: false,
        }
    },

    methods: {
        /**
         * Reformata a cada tecla e reposiciona o cursor no fim: o preenchimento é
         * da direita para a esquerda (digitar "1" mostra "0,01"), então editar no
         * meio não faz sentido neste campo — é o mesmo comportamento dos demais
         * ports e do v-money3 que este código substitui.
         */
        onInput(event: Event) {
            const el = event.target as HTMLInputElement
            const digits = el.value.replace(/\D/g, "")
            const formatted = formatCurrencyDigits(digits, this.fraction, this.prefix)

            // O DOM precisa ser corrigido na mão: quando o formatado é igual ao
            // anterior (tecla rejeitada), o Vue não re-renderiza e o caractere
            // inválido ficaria visível.
            if (el.value !== formatted) el.value = formatted
            const fim = formatted.length
            el.setSelectionRange(fim, fim)

            this.$emit("update:modelValue", formatted)
        },

        keyUp(e: any) {
            if (e.key == '0') {
                this.displayBlankValue = false
            } else {
                this.displayBlankValue = true
            }
        },

        change(val: any) {
            this.$emit("update:modelValue", val)
        },

        focus() {
            (this.$refs.input as { focus: () => void }).focus()
        }
    }
} as Component
</script>

<!--
  Estilo NÃO-scoped (classe única `icur-arcana-input`) — mantido assim por
  compatibilidade: era necessário quando o campo era renderizado pelo `v-money3`,
  e continua sendo o seletor que os consumidores estilizam.
  Espelha `.arcana-input` do `<ArcanaInput>`.
-->

// src/svelte/ArcanaInputCurrency.svelte
<script lang="ts" module>
  const DECIMAL = ",";
  const THOUSANDS = ".";

  export function digitsFromValue(
    v: string | number | undefined,
    precision: number
  ): string {
    if (v == null || v === "") return "";
    if (typeof v === "number") {
      return String(Math.round(Math.abs(v) * Math.pow(10, precision)));
    }
    const s = String(v);
    if (s.includes(DECIMAL)) return s.replace(/\D/g, "");
    const n = parseFloat(s);
    if (!isFinite(n)) return s.replace(/\D/g, "");
    return String(Math.round(Math.abs(n) * Math.pow(10, precision)));
  }

  export function formatDigits(digits: string, precision: number, prefix: string): string {
    let d = digits.replace(/\D/g, "");
    if (!d) d = "0";
    if (precision > 0) d = d.padStart(precision + 1, "0");
    const cut = precision > 0 ? d.length - precision : d.length;
    let intPart = d.slice(0, cut).replace(/^0+(?=\d)/, "");
    const fracPart = precision > 0 ? d.slice(cut) : "";
    intPart = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, THOUSANDS);
    return prefix + intPart + (precision > 0 ? DECIMAL + fracPart : "");
  }
</script>

<script lang="ts">
  /**
   * `<ArcanaInputCurrency>` — Svelte 5 port. Input de moeda BRL.
   *
   * Decisão sobre a lib (parity com React/Angular): o SFC usa `v-money3` (Vue-only). Em
   * vez de adicionar dep, reimplementamos a máscara de moeda equivalente (mesma UX
   * right-to-left: dígitos preenchem a partir dos centavos), mantendo markup/classes
   * (`icur-arcana-field`/`icur-arcana-input` no modo shadcn; `input-group`/`form-control`
   * no modo Bootstrap). Como o v-money3 default (sem `masked:false`), o `modelValue`
   * emitido é a STRING mascarada BRL (ex. `"1.234,56"`).
   *
   * Equivalências: `modelValue` → `value` + `onValueChange`; `emit('change'|'enter'|'blur')`
   * → `onChange`/`onEnter`/`onBlur`; slots `#prepend`/`#append` → snippets `prepend`/`append`.
   */
  import type { Snippet } from "svelte";
  import { untrack } from "svelte";
  import { CurrencyFormatter } from "../core/currency";

  let {
    value = "",
    disabled = false,
    fraction = 2,
    name,
    showIcon = true,
    prefix = "",
    icon = "icon-coin-dollar",
    formatCurrency = true,
    shadcn = false,
    prepend,
    append,
    onValueChange,
    onChange,
    onEnter,
    onBlur,
    class: className = "",
  }: {
    value?: string | number;
    disabled?: boolean | number;
    allowBlank?: boolean;
    fraction?: number;
    name?: string;
    showIcon?: boolean;
    prefix?: string;
    icon?: string;
    max?: number;
    min?: number;
    formatCurrency?: boolean;
    shadcn?: boolean;
    prepend?: Snippet;
    append?: Snippet;
    onValueChange?: (value: string) => void;
    onChange?: (ev: unknown) => void;
    onEnter?: (ev: KeyboardEvent) => void;
    onBlur?: (ev: FocusEvent) => void;
    class?: string;
  } = $props();

  const isDisabled = $derived(Boolean(disabled));

  let display = $state(formatDigits(digitsFromValue(value, fraction), fraction, prefix));

  // Reflete mudança externa do `value` no display (load/reset). Compara pelos dígitos.
  $effect(() => {
    const incoming = digitsFromValue(value, fraction);
    const fr = fraction;
    const pf = prefix;
    untrack(() => {
      const current = display.replace(/\D/g, "");
      if (incoming.replace(/^0+(?=\d)/, "") !== current.replace(/^0+(?=\d)/, "")) {
        display = formatDigits(incoming, fr, pf);
      }
    });
  });

  const formattedCurrency = $derived(formatCurrency ? CurrencyFormatter.format(value || 0) : value);

  function onInput(e: Event) {
    const el = e.target as HTMLInputElement;
    const digits = el.value.replace(/\D/g, "");
    const formatted = formatDigits(digits, fraction, prefix);

    display = formatted;
    // O DOM precisa ser corrigido na mão: quando o formatado é IGUAL ao estado
    // anterior, o Svelte não re-renderiza e o texto cru continua visível. Ocorre,
    // por exemplo, ao digitar "0" num campo vazio, que já exibia "0,00".
    if (el.value !== formatted) el.value = formatted;

    onValueChange?.(formatted);
  }

  const inputClasses = $derived(
    [
      shadcn ? "icur-arcana-input" : "form-control",
      shadcn && showIcon ? "has-icon" : "",
      className,
    ]
      .filter(Boolean)
      .join(" ")
  );

  const wrapClasses = $derived(
    shadcn
      ? ["icur-arcana-field", isDisabled ? "is-disabled" : ""].filter(Boolean).join(" ")
      : showIcon
        ? "input-group"
        : ""
  );
</script>

<div class={wrapClasses || undefined}>
  {#if prepend}
    {@render prepend()}
  {:else}
    {#if showIcon && !shadcn}
      <span class="input-group-addon"><i class={icon}></i></span>
    {/if}
    {#if showIcon && shadcn}
      <span class="icur-arcana-field__icon"><i class={icon}></i></span>
    {/if}
  {/if}

  {#if !isDisabled}
    <input
      type="text"
      class={inputClasses}
      {name}
      value={display}
      oninput={onInput}
      onkeyup={(e) => {
        if (e.key === "Enter") onEnter?.(e);
      }}
      onblur={(e) => {
        onChange?.(display);
        onBlur?.(e);
      }}
    />
  {:else}
    <input
      disabled
      class={[
        shadcn ? "icur-arcana-input" : "form-control",
        shadcn && showIcon ? "has-icon" : "",
        "full-width",
      ]
        .filter(Boolean)
        .join(" ")}
      type="text"
      value={String(formattedCurrency)}
      readonly
    />
  {/if}

  {#if append}{@render append()}{/if}
</div>
