// src/angular/arcana-settings-list-group.component.ts
import {
  ChangeDetectionStrategy, Component, Input, OnInit, TemplateRef
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";

/**
 * `ArcanaSettingsListGroupComponent` — Angular port do SFC Vue `ArcanaSettingsListGroup`.
 *
 * Attribute selector num `<section>` (`<section arcanaSettingsListGroup>`): section
 * interna do `ArcanaSettingsList` com header (ícone boxed + título + meta) e opção
 * `collapsible` (header vira botão + chevron). Reproduz `.arcana-settings-list__group`
 * (+ `--compact`/`--collapsible`/`--collapsed`), `__group-head`/`-icon`/`-num`/`-title`/
 * `-meta`/`-chevron`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `<component :is="collapsible ? 'button' : 'header'">` → dois ramos `@if`.
 * - slot `#title` / `#meta` → `@Input() titleTemplate` / `metaTemplate` (`TemplateRef`),
 *   fallback pras props string. slot default → `<ng-content>`.
 */
export type SettingsGroupIconColor =
  "blue" | "emerald" | "amber" | "rose" | "violet" | "indigo" | "teal" | "slate";

@Component({
  selector: "section[arcanaSettingsListGroup]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { "[class]": "rootClass" },
  template: `
    @if (title || titleTemplate) {
      @if (collapsible) {
        <button
          type="button"
          class="arcana-settings-list__group-head"
          [attr.aria-expanded]="!isCollapsed"
          (click)="toggle()"
        >
          <ng-container [ngTemplateOutlet]="headInner"></ng-container>
        </button>
      } @else {
        <header class="arcana-settings-list__group-head">
          <ng-container [ngTemplateOutlet]="headInner"></ng-container>
        </header>
      }
    }

    <div [style.display]="(!collapsible || !isCollapsed) ? null : 'none'">
      <ng-content></ng-content>
    </div>

    <ng-template #headInner>
      <div class="arcana-settings-list__group-head-left">
        @if (icon) {
          <span
            [class]="'arcana-settings-list__group-icon arcana-settings-list__group-icon--' + iconColor"
            aria-hidden="true"
          >
            <i [class]="icon"></i>
          </span>
        }
        <div>
          @if (sectionNum) {
            <div class="arcana-settings-list__group-num">{{ sectionNum }}</div>
          }
          <div class="arcana-settings-list__group-title">
            @if (titleTemplate) {
              <ng-container [ngTemplateOutlet]="titleTemplate"></ng-container>
            } @else {
              {{ title }}
            }
          </div>
        </div>
      </div>

      <div class="arcana-settings-list__group-head-right">
        @if (meta || metaTemplate) {
          <div class="arcana-settings-list__group-meta">
            @if (metaTemplate) {
              <ng-container [ngTemplateOutlet]="metaTemplate"></ng-container>
            } @else {
              {{ meta }}
            }
          </div>
        }
        @if (collapsible) {
          <svg
            class="arcana-settings-list__group-chevron"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            stroke-width="2"
            stroke-linecap="round"
            stroke-linejoin="round"
            aria-hidden="true"
          >
            <polyline points="6 9 12 15 18 9" />
          </svg>
        }
      </div>
    </ng-template>
  `
})
export class ArcanaSettingsListGroupComponent implements OnInit {
  @Input() title = "";
  @Input() sectionNum = "";
  @Input() meta = "";
  @Input() icon = "";
  @Input() iconColor: SettingsGroupIconColor = "slate";
  @Input() collapsible = false;
  @Input() defaultCollapsed = false;
  @Input() compact = false;
  @Input() titleTemplate?: TemplateRef<unknown>;
  @Input() metaTemplate?: TemplateRef<unknown>;

  isCollapsed = false;

  ngOnInit(): void {
    this.isCollapsed = this.collapsible && this.defaultCollapsed;
  }

  get rootClass(): string {
    return [
      "arcana-settings-list__group",
      this.compact ? "arcana-settings-list__group--compact" : "",
      this.collapsible ? "arcana-settings-list__group--collapsible" : "",
      this.collapsible && this.isCollapsed ? "arcana-settings-list__group--collapsed" : ""
    ].filter(Boolean).join(" ");
  }

  toggle(): void {
    this.isCollapsed = !this.isCollapsed;
  }
}

// src/svelte/ArcanaSettingsListGroup.svelte
<script lang="ts" module>
  export type SettingsGroupIconColor =
    | "blue"
    | "emerald"
    | "amber"
    | "rose"
    | "violet"
    | "indigo"
    | "teal"
    | "slate";
</script>

<script lang="ts">
  /**
   * `<ArcanaSettingsListGroup>` — Svelte 5 port do SFC Vue. Section interna do
   * `<ArcanaSettingsList>` com header (ícone boxed opcional + title + meta opcional).
   *
   * Equivalências Vue → Svelte 5:
   * - `data.isCollapsed` → `$state`; `<component :is="collapsible ? 'button' : 'header'">`
   *   → branch `{#if collapsible}` (button/header) igual ao port React
   * - slots `#title` / `#meta` → snippets `title` / `meta` (fallback pras props string)
   * - slot default → snippet `children`
   */
  import type { Snippet } from "svelte";

  let {
    title = "",
    sectionNum = "",
    meta,
    icon = "",
    iconColor = "slate",
    collapsible = false,
    defaultCollapsed = false,
    compact = false,
    children,
  }: {
    title?: string | Snippet;
    sectionNum?: string;
    meta?: string | Snippet;
    icon?: string;
    iconColor?: SettingsGroupIconColor;
    collapsible?: boolean;
    defaultCollapsed?: boolean;
    compact?: boolean;
    children?: Snippet;
  } = $props();

  let isCollapsed = $state(collapsible && defaultCollapsed);

  function toggle() {
    isCollapsed = !isCollapsed;
  }

  const hasTitle = $derived(Boolean(title));
  const hasMeta = $derived(Boolean(meta));
  const showHead = $derived(hasTitle || hasMeta || Boolean(icon) || Boolean(sectionNum));

  const sectionClasses = $derived(
    [
      "arcana-settings-list__group",
      compact ? "arcana-settings-list__group--compact" : "",
      collapsible ? "arcana-settings-list__group--collapsible" : "",
      collapsible && isCollapsed ? "arcana-settings-list__group--collapsed" : "",
    ]
      .filter(Boolean)
      .join(" ")
  );
</script>

{#snippet headInner()}
  <div class="arcana-settings-list__group-head-left">
    {#if icon}
      <span
        class={`arcana-settings-list__group-icon arcana-settings-list__group-icon--${iconColor}`}
        aria-hidden="true"
      >
        <i class={icon}></i>
      </span>
    {/if}
    <div>
      {#if sectionNum}
        <div class="arcana-settings-list__group-num">{sectionNum}</div>
      {/if}
      <div class="arcana-settings-list__group-title">
        {#if typeof title === "function"}{@render title()}{:else}{title}{/if}
      </div>
    </div>
  </div>

  <div class="arcana-settings-list__group-head-right">
    {#if hasMeta}
      <div class="arcana-settings-list__group-meta">
        {#if typeof meta === "function"}{@render meta()}{:else}{meta}{/if}
      </div>
    {/if}
    {#if collapsible}
      <svg
        class="arcana-settings-list__group-chevron"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        aria-hidden="true"
      >
        <polyline points="6 9 12 15 18 9" />
      </svg>
    {/if}
  </div>
{/snippet}

<section class={sectionClasses}>
  {#if showHead}
    {#if collapsible}
      <button
        type="button"
        class="arcana-settings-list__group-head"
        aria-expanded={!isCollapsed}
        onclick={toggle}
      >
        {@render headInner()}
      </button>
    {:else}
      <header class="arcana-settings-list__group-head">
        {@render headInner()}
      </header>
    {/if}
  {/if}

  {#if !collapsible || !isCollapsed}
    <div>{@render children?.()}</div>
  {/if}
</section>
