// src/react/ShadcnSkeleton.tsx
import type { CSSProperties } from "react";

/**
 * `<ShadcnSkeleton>` — React port. Placeholder shimmer. Reproduz
 * `<span class="shadcn-skeleton shadcn-skeleton--rounded-${rounded}">` com width/height
 * inline e `aria-hidden`, idêntico ao SFC.
 */
export interface ShadcnSkeletonProps {
    width?: string;
    height?: string;
    rounded?: "sm" | "md" | "lg" | "full" | "none";
    className?: string;
}

export function ShadcnSkeleton({
    width = "100%",
    height = "14px",
    rounded = "md",
    className,
}: ShadcnSkeletonProps) {
    const classes = [
        "shadcn-skeleton",
        `shadcn-skeleton--rounded-${rounded}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const style: CSSProperties = { width, height };

    return <span className={classes} style={style} aria-hidden="true" />;
}

// src/svelte/ShadcnSkeleton.svelte
<script lang="ts">
  /**
   * `<ShadcnSkeleton>` — Svelte 5 port. Placeholder shimmer. Reproduz
   * `<span class="shadcn-skeleton shadcn-skeleton--rounded-${rounded}">` com width/height
   * inline e `aria-hidden`, idêntico ao SFC Vue.
   */
  let {
    width = "100%",
    height = "14px",
    rounded = "md",
    class: className = "",
  }: {
    width?: string;
    height?: string;
    rounded?: "sm" | "md" | "lg" | "full" | "none";
    class?: string;
  } = $props();

  const classes = $derived(
    ["shadcn-skeleton", `shadcn-skeleton--rounded-${rounded}`, className].filter(Boolean).join(" ")
  );
</script>

<span class={classes} style={`width: ${width}; height: ${height};`} aria-hidden="true"></span>
