// src/angular/shadcn-dropdown-item.component.ts
import {
  ChangeDetectionStrategy, Component, Input, TemplateRef, inject
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import { ShadcnDropdownComponent, type ShadcnDropdownSize } from "./shadcn-dropdown.component";

/**
 * `ShadcnDropdownItemComponent` — Angular port do SFC Vue `ShadcnDropdownItem`.
 *
 * Attribute selector (`<div arcanaShadcnDropdownItem>`) com `display: contents` no host,
 * pra que o separador opcional (`.shadcn-dropdown-item__separator`) e o `<button
 * .shadcn-dropdown-item>` fiquem como filhos diretos (visuais) do menu — idêntico ao markup
 * Vue (separador é sibling do botão). Reproduz `--${variant}`/`--comfortable`/`is-disabled`,
 * `__icon`/`__label`/`__suffix`.
 *
 * Contexto pai→filho: injeta o `ShadcnDropdownComponent` (o item é projetado dentro do
 * dropdown, logo está na cadeia de DI — mesma técnica do `ShadcnAccordionItem`). Herda o
 * `size` do pai e chama `dropdown.close()` no clique (substitui o CustomEvent do SFC).
 *
 * Vue → Angular:
 * - slot default → `<ng-content>` (label); slot `#suffix` → `@Input() suffix` (string) OU
 *   `@Input() suffixTemplate` (`TemplateRef`), espelhando o prop `suffix` do port React.
 * - `emit('click', ev)` → `@Output()`? não: o clique é tratado internamente (close). Pra
 *   reagir ao clique, use o `(click)` DOM no próprio conteúdo ou `onClick` via binding.
 */
@Component({
  selector: "div[arcanaShadcnDropdownItem]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { "style": "display: contents" },
  template: `
    @if (divided) {
      <div class="shadcn-dropdown-item__separator"></div>
    }

    <button
      type="button"
      [class]="buttonClasses"
      [disabled]="disabled"
      role="menuitem"
      (click)="handleClick($event)"
    >
      @if (icon) {
        <i class="shadcn-dropdown-item__icon {{ icon }}" [style.color]="iconColor || null" aria-hidden="true"></i>
      }
      <span class="shadcn-dropdown-item__label"><ng-content></ng-content></span>
      @if (suffixTemplate) {
        <span class="shadcn-dropdown-item__suffix">
          <ng-container [ngTemplateOutlet]="suffixTemplate"></ng-container>
        </span>
      } @else if (suffix) {
        <span class="shadcn-dropdown-item__suffix">{{ suffix }}</span>
      }
    </button>
  `
})
export class ShadcnDropdownItemComponent {
  @Input() icon = "";
  @Input() iconColor = "";
  @Input() variant: "default" | "danger" | "success" | "warning" = "default";
  @Input() disabled = false;
  @Input() divided = false;
  @Input() closeOnClick = true;
  /** Sobrescreve o `size` herdado do `ShadcnDropdown` pai só neste item. */
  @Input() size: ShadcnDropdownSize | null = null;
  @Input() suffix = "";
  @Input() suffixTemplate?: TemplateRef<unknown>;

  // Injeta o `ShadcnDropdown` pai (o item é projetado dentro dele → cadeia de DI).
  // `optional` pra permitir uso standalone; mesma técnica do `ShadcnAccordionItem`.
  private readonly dropdown = inject(ShadcnDropdownComponent, { optional: true });

  get effectiveSize(): ShadcnDropdownSize {
    return this.size ?? this.dropdown?.size ?? "default";
  }

  get buttonClasses(): string {
    return [
      "shadcn-dropdown-item",
      this.variant ? `shadcn-dropdown-item--${this.variant}` : "",
      this.effectiveSize === "comfortable" ? "shadcn-dropdown-item--comfortable" : "",
      this.disabled ? "is-disabled" : ""
    ].filter(Boolean).join(" ");
  }

  handleClick(_e: MouseEvent): void {
    if (this.disabled) return;
    if (this.closeOnClick) this.dropdown?.close();
  }
}

// src/svelte/ShadcnDropdownItem.svelte
<script lang="ts">
  /**
   * `<ShadcnDropdownItem>` — Svelte 5 port do SFC Vue. Item do `<ShadcnDropdown>`:
   * ícone + label + (opcional) suffix.
   *
   * Equivalências Vue → Svelte 5:
   * - `inject('shadcnDropdownSize')` → `getContext(DROPDOWN_CONTEXT)` (herda densidade do pai)
   * - CustomEvent `shadcn-dropdown-close` → chama `ctx.close()` direto quando `closeOnClick`
   * - slot default → snippet `children`; slot `#suffix` → snippet `suffix`
   * - `emit('click')` → callback `onClick`
   */
  import type { Snippet } from "svelte";
  import { getContext } from "svelte";
  import {
    DROPDOWN_CONTEXT,
    type DropdownContextValue,
    type ShadcnDropdownSize,
  } from "./ShadcnDropdown.svelte";

  let {
    icon = "",
    iconColor = "",
    variant = "default",
    disabled = false,
    divided = false,
    closeOnClick = true,
    size = null,
    suffix,
    children,
    onClick,
  }: {
    icon?: string;
    iconColor?: string;
    variant?: "default" | "danger" | "success" | "warning";
    disabled?: boolean;
    divided?: boolean;
    closeOnClick?: boolean;
    size?: ShadcnDropdownSize | null;
    suffix?: Snippet;
    children?: Snippet;
    onClick?: (e: MouseEvent) => void;
  } = $props();

  // Contexto do `<ShadcnDropdown>` pai (fallback quando usado standalone).
  const ctx = getContext<DropdownContextValue | undefined>(DROPDOWN_CONTEXT);

  const effectiveSize = $derived(size ?? ctx?.size ?? "default");

  const classes = $derived(
    [
      "shadcn-dropdown-item",
      variant ? `shadcn-dropdown-item--${variant}` : "",
      effectiveSize === "comfortable" ? "shadcn-dropdown-item--comfortable" : "",
      disabled ? "is-disabled" : "",
    ]
      .filter(Boolean)
      .join(" ")
  );

  function handleClick(e: MouseEvent) {
    if (disabled) return;
    onClick?.(e);
    if (closeOnClick) ctx?.close();
  }
</script>

{#if divided}
  <div class="shadcn-dropdown-item__separator"></div>
{/if}

<button
  type="button"
  class={classes}
  {disabled}
  role="menuitem"
  onclick={handleClick}
>
  {#if icon}
    <i
      class={`shadcn-dropdown-item__icon ${icon}`}
      style={iconColor ? `color:${iconColor};` : undefined}
      aria-hidden="true"
    ></i>
  {/if}
  <span class="shadcn-dropdown-item__label">{@render children?.()}</span>
  {#if suffix}
    <span class="shadcn-dropdown-item__suffix">{@render suffix()}</span>
  {/if}
</button>
