// src/react/ArcanaSwitch.tsx
import type { KeyboardEvent } from "react";

/**
 * `<ArcanaSwitch>` — React port. Reproduz o `<button role="switch" class="arcana-switch">`
 * (+ `arcana-switch--${size}`, `is-checked`, `is-disabled`), o `span.arcana-switch__thumb`
 * e o `<input class="arcana-switch__hidden-input">` opcional (quando `name`), idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` (controlado) + `onValueChange`
 * - `emit('change')` → `onChange`
 */
export interface ArcanaSwitchProps {
    value?: boolean;
    disabled?: boolean;
    size?: "sm" | "md" | "lg";
    name?: string;
    ariaLabel?: string;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    className?: string;
    /** Reproduz `tabindex`/`aria-hidden` que o ArcanaSwitchRow passa ao switch interno. */
    tabIndex?: number;
    "aria-hidden"?: boolean;
}

export function ArcanaSwitch({
    value = false,
    disabled = false,
    size = "md",
    name = "",
    ariaLabel = "",
    onValueChange,
    onChange,
    className,
    tabIndex,
    "aria-hidden": ariaHidden,
}: ArcanaSwitchProps) {
    const isChecked = Boolean(value);

    const rootClasses = [
        "arcana-switch",
        `arcana-switch--${size}`,
        isChecked ? "is-checked" : "",
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const toggle = () => {
        if (disabled) return;
        const next = !isChecked;
        onValueChange?.(next);
        onChange?.(next);
    };

    const onKeydown = (e: KeyboardEvent<HTMLButtonElement>) => {
        if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            toggle();
        }
    };

    return (
        <button
            type="button"
            role="switch"
            className={rootClasses}
            aria-checked={isChecked}
            aria-label={ariaLabel || undefined}
            aria-hidden={ariaHidden}
            disabled={disabled}
            tabIndex={tabIndex}
            onClick={toggle}
            onKeyDown={onKeydown}
        >
            <span className="arcana-switch__thumb" aria-hidden="true" />

            {name ? (
                <input
                    type="checkbox"
                    className="arcana-switch__hidden-input"
                    name={name}
                    checked={isChecked}
                    disabled={disabled}
                    tabIndex={-1}
                    aria-hidden="true"
                    readOnly
                    onClick={(e) => e.stopPropagation()}
                />
            ) : null}
        </button>
    );
}

// src/vue/components/ArcanaSwitch.vue
<template>
    <button
        type="button"
        role="switch"
        class="arcana-switch"
        :class="rootClasses"
        :aria-checked="isChecked"
        :aria-label="ariaLabel || undefined"
        :disabled="disabled"
        @click="toggle"
        @keydown="onKeydown"
    >
        <span class="arcana-switch__thumb" aria-hidden="true"></span>

        <!--
            Native input escondido pra integrar com forms HTML (submit, validação)
            e screen readers que não suportam role="switch" nativo. Sincroniza com
            o estado do componente.
        -->
        <input
            v-if="name"
            type="checkbox"
            class="arcana-switch__hidden-input"
            :name="name"
            :checked="isChecked"
            :disabled="disabled"
            tabindex="-1"
            aria-hidden="true"
            @change.stop
        />
    </button>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

/**
 * `<ArcanaSwitch>` — toggle binário on/off (palette zinc).
 *
 * UX: pra valores booleanos onde "ligar/desligar" faz mais sentido que "Sim/Não" num
 * select. Casos típicos: auto-renew, notifications, dark mode, etc.
 *
 * API:
 * - `modelValue` (v-model) — boolean
 * - `disabled` — boolean
 * - `size` — `'sm' | 'md' | 'lg'` (default `md`)
 * - `name` — opcional, name do checkbox HTML escondido (pra forms tradicionais)
 * - `ariaLabel` — opcional, descrição pra screen reader (recomendado quando não há `<label for>`)
 *
 * Acessibilidade:
 * - `role="switch"` + `aria-checked` (padrão WAI-ARIA pra toggle)
 * - `Space`/`Enter` ativam (browser default em `<button>`)
 * - `<input type="checkbox">` escondido pra integração com formulários nativos
 *
 * Exemplo:
 *
 *     <label class="form-row">
 *         <span>Auto-renovação</span>
 *         <ArcanaSwitch v-model="form.auto_renew" aria-label="Auto-renovação" />
 *     </label>
 */
export default {
    name: 'ArcanaSwitch',

    emits: ['update:modelValue', 'change'],

    props: {
        modelValue: {
            type: Boolean,
            default: false,
        },
        disabled: {
            type: Boolean,
            default: false,
        },
        size: {
            type: String as PropType<'sm' | 'md' | 'lg'>,
            default: 'md',
            validator: (v: string) => ['sm', 'md', 'lg'].includes(v),
        },
        name: {
            type: String,
            default: '',
        },
        ariaLabel: {
            type: String,
            default: '',
        },
    },

    computed: {
        isChecked(): boolean {
            return Boolean(this.modelValue)
        },
        rootClasses(): string {
            const cls = [`arcana-switch--${this.size}`]
            if (this.isChecked) cls.push('is-checked')
            if (this.disabled) cls.push('is-disabled')
            return cls.join(' ')
        },
    },

    methods: {
        toggle() {
            if (this.disabled) return
            const next = !this.isChecked
            this.$emit('update:modelValue', next)
            this.$emit('change', next)
        },

        onKeydown(e: KeyboardEvent) {
            // Space/Enter já ativam o button por default; aqui só interceptamos
            // pra evitar scroll da página ao apertar Space.
            if (e.key === ' ' || e.key === 'Enter') {
                e.preventDefault()
                this.toggle()
            }
        },
    },
} as Component
</script>
