// src/react/ArcanaSummaryTile.tsx
import type { CSSProperties, ReactNode } from "react";

/**
 * `<ArcanaSummaryTile>` — React port. Tile compacto de KPI. Reproduz
 * `<div class="arcana-summary-tile arcana-summary-tile--${tone}">`, o `__icon`,
 * `__main`/`__label`/`__sub` e `__value`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slots `#value`/`#sub` → props `valueSlot`/`subSlot` (ReactNode)
 */
export type SummaryTileTone = "neutral" | "positive" | "negative" | "indigo";

export interface ArcanaSummaryTileProps {
    label: string;
    value?: string | number | null;
    icon?: string;
    sub?: string;
    tone?: SummaryTileTone;
    valueSlot?: ReactNode;
    subSlot?: ReactNode;
    className?: string;
    style?: CSSProperties;
}

export function ArcanaSummaryTile({
    label,
    value = null,
    icon = "",
    sub = "",
    tone = "neutral",
    valueSlot,
    subSlot,
    className,
    style,
}: ArcanaSummaryTileProps) {
    const hasSub = Boolean(subSlot || sub);

    const rootClasses = [
        "arcana-summary-tile",
        `arcana-summary-tile--${tone}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={rootClasses} style={style}>
            {icon ? (
                <span className="arcana-summary-tile__icon" aria-hidden="true">
                    <i className={icon} />
                </span>
            ) : null}

            <div className="arcana-summary-tile__main">
                <span className="arcana-summary-tile__label">{label}</span>
                {hasSub ? (
                    <span className="arcana-summary-tile__sub">{subSlot ?? sub}</span>
                ) : null}
            </div>

            <span className="arcana-summary-tile__value">{valueSlot ?? value}</span>
        </div>
    );
}

// src/vue/components/ArcanaSummaryTile.vue
<template>
    <div class="arcana-summary-tile" :class="rootClasses">
        <span v-if="icon" class="arcana-summary-tile__icon" aria-hidden="true">
            <i :class="icon"></i>
        </span>

        <div class="arcana-summary-tile__main">
            <span class="arcana-summary-tile__label">{{ label }}</span>
            <span
                v-if="hasSub"
                class="arcana-summary-tile__sub"
            >
                <slot name="sub">{{ sub }}</slot>
            </span>
        </div>

        <span class="arcana-summary-tile__value">
            <slot name="value">{{ value }}</slot>
        </span>
    </div>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

type SummaryTileTone = 'neutral' | 'positive' | 'negative' | 'indigo'

/**
 * `<ArcanaSummaryTile>` — tile compacto de KPI/resumo. Layout horizontal:
 * `[icon pip] [label + sub] [value]`. Cabe num grid de 3 colunas em ~52px de altura.
 *
 * Tons (`tone`):
 * - `neutral` (default) — card branco, ícone cinza zinc
 * - `positive`          — card verde-100, borda verde-300, ícone/texto verde-700+
 * - `negative`          — card vermelho-50, borda vermelho-200, ícone/texto vermelho-700+
 * - `indigo`            — card branco neutro mas ícone com pip indigo (`Total do Acerto`)
 *
 * API:
 * - `label`  (string, required) — eyebrow uppercase
 * - `value`  (string|number) — valor monetário/numérico (já formatado pelo caller).
 *   Pode ser substituído inteiro pelo slot `#value` (ex: html com badge inline).
 * - `icon`   (string) — classe Font Awesome (ex: `'fa-solid fa-arrow-down'`)
 * - `sub`    (string) — texto secundário em baixo do label. Slot `#sub` sobrepõe.
 * - `tone`   — variante visual (default `'neutral'`)
 *
 * Slots:
 * - `value` — substitui o valor (default mostra `:value`)
 * - `sub`   — substitui o texto secundário (default mostra `:sub`)
 */
export default {
    name: 'ArcanaSummaryTile',

    props: {
        label: {
            type: String,
            required: true,
        },
        value: {
            type: [String, Number, null] as PropType<string | number | null>,
            default: null,
        },
        icon: {
            type: String,
            default: '',
        },
        sub: {
            type: String,
            default: '',
        },
        tone: {
            type: String as PropType<SummaryTileTone>,
            default: 'neutral',
            validator: (v: string) => ['neutral', 'positive', 'negative', 'indigo'].includes(v),
        },
    },

    computed: {
        rootClasses(): string {
            return `arcana-summary-tile--${this.tone}`
        },

        hasSub(): boolean {
            return Boolean(this.$slots.sub || this.sub)
        },
    },
} as Component
</script>
