// src/react/ArcanaStatistic.tsx
import type { CSSProperties, ReactNode } from "react";

import { formatStatisticValue } from "../core/statistic";

/**
 * `<ArcanaStatistic>` — React port. Número em destaque com rótulo. Reproduz
 * `<div class="arcana-statistic arcana-statistic--{size} arcana-statistic--{tone}">`, o
 * `__title`, o `__content` com `__icon`/`__prefix`/`__value`/`__suffix`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slots `#title`/`#prefix`/`#suffix` → props `titleSlot`/`prefixSlot`/`suffixSlot` (ReactNode)
 * - `valueColor` → inline `--arcana-statistic-value-color` na raiz (vale pro valor e pro ícone)
 *
 * A formatação numérica vive em `core/statistic.ts` (framework-agnóstica e testada): string
 * passa intacta, número é agrupado/fixado, `locale` liga o `Intl.NumberFormat` e vence os
 * separadores manuais.
 */
export type StatisticTone = "neutral" | "success" | "danger" | "warning" | "info";
export type StatisticSize = "sm" | "md" | "lg" | "xl";

export interface ArcanaStatisticProps {
    /** Número exibido. String passa intacta (escape hatch pra valor já formatado). */
    value?: number | string | null;
    title?: string;
    /** Alias de `title` (`title` vence quando os dois vêm). */
    label?: string;
    /** Casas decimais fixas. Omitido = mantém as casas do próprio número. */
    precision?: number;
    /** Separador de milhar (default `","`); `""` desliga o agrupamento. */
    groupSeparator?: string;
    /** Separador decimal (default `"."`). */
    decimalSeparator?: string;
    /** Quando informado, `Intl.NumberFormat` assume e ignora os separadores manuais. */
    locale?: string;
    /** Controle total da string final — tem precedência sobre todo o resto. */
    formatter?: (value: number | string | null) => string;
    prefix?: string;
    suffix?: string;
    tone?: StatisticTone;
    /** Cor CSS arbitrária do valor; vence o `tone`. */
    valueColor?: string;
    size?: StatisticSize;
    /** Classe do ícone (ex: `"fa-solid fa-arrow-trend-up"`). */
    icon?: string;
    titleSlot?: ReactNode;
    prefixSlot?: ReactNode;
    suffixSlot?: ReactNode;
    className?: string;
    style?: CSSProperties;
}

export function ArcanaStatistic({
    value = null,
    title = "",
    label = "",
    precision,
    groupSeparator = ",",
    decimalSeparator = ".",
    locale = "",
    formatter,
    prefix = "",
    suffix = "",
    tone = "neutral",
    valueColor = "",
    size = "md",
    icon = "",
    titleSlot,
    prefixSlot,
    suffixSlot,
    className,
    style,
}: ArcanaStatisticProps) {
    const resolvedTitle = title || label;
    const hasTitle = Boolean(titleSlot || resolvedTitle);
    const hasPrefix = Boolean(prefixSlot || prefix);
    const hasSuffix = Boolean(suffixSlot || suffix);

    const displayValue = formatter
        ? formatter(value ?? null)
        : formatStatisticValue(value, {
              precision,
              groupSeparator,
              decimalSeparator,
              locale: locale || undefined,
          });

    const rootClasses = [
        "arcana-statistic",
        `arcana-statistic--${size}`,
        `arcana-statistic--${tone}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const rootStyle = valueColor
        ? ({ ...(style ?? {}), "--arcana-statistic-value-color": valueColor } as CSSProperties)
        : style;

    return (
        <div className={rootClasses} style={rootStyle}>
            {hasTitle ? (
                <div className="arcana-statistic__title">{titleSlot ?? resolvedTitle}</div>
            ) : null}

            <div className="arcana-statistic__content">
                {icon ? (
                    <span className="arcana-statistic__icon" aria-hidden="true">
                        <i className={icon} />
                    </span>
                ) : null}

                {hasPrefix ? (
                    <span className="arcana-statistic__prefix">{prefixSlot ?? prefix}</span>
                ) : null}

                <span className="arcana-statistic__value">{displayValue}</span>

                {hasSuffix ? (
                    <span className="arcana-statistic__suffix">{suffixSlot ?? suffix}</span>
                ) : null}
            </div>
        </div>
    );
}

// src/vue/components/ArcanaStatistic.vue
<template>
    <div
        class="arcana-statistic"
        :class="[`arcana-statistic--${size}`, `arcana-statistic--${tone}`]"
        :style="valueColor ? { '--arcana-statistic-value-color': valueColor } : undefined"
    >
        <div v-if="hasTitle" class="arcana-statistic__title">
            <slot name="title">{{ resolvedTitle }}</slot>
        </div>

        <div class="arcana-statistic__content">
            <span v-if="icon" class="arcana-statistic__icon" aria-hidden="true">
                <i :class="icon"></i>
            </span>

            <span v-if="hasPrefix" class="arcana-statistic__prefix">
                <slot name="prefix">{{ prefix }}</slot>
            </span>

            <span class="arcana-statistic__value">{{ displayValue }}</span>

            <span v-if="hasSuffix" class="arcana-statistic__suffix">
                <slot name="suffix">{{ suffix }}</slot>
            </span>
        </div>
    </div>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

import { formatStatisticValue } from "../../core/statistic"

type StatisticTone = 'neutral' | 'success' | 'danger' | 'warning' | 'info'
type StatisticSize = 'sm' | 'md' | 'lg' | 'xl'

/**
 * `<ArcanaStatistic>` — número em destaque com rótulo (KPI de painel). Layout vertical:
 * `[título]` em cima, `[ícone] [prefixo] VALOR [sufixo]` embaixo, alinhados pela baseline.
 *
 * Irmão do `<ArcanaSummaryTile>` (que é um card horizontal compacto): aqui o valor é a
 * estrela — fonte grande, `tabular-nums`, sem moldura.
 *
 * API:
 * - `value` (number|string) — número exibido. **String passa intacta** (escape hatch pra
 *   valor já formatado pelo caller); só `number` é formatado pelas regras abaixo.
 * - `title` / `label` — rótulo acima do valor (`label` é alias; `title` vence)
 * - `precision` — casas decimais fixas. Sem ele, o número mantém as próprias casas.
 * - `groupSeparator` (default `','`) e `decimalSeparator` (default `'.'`) — separadores
 *   manuais. `groupSeparator: ''` desliga o agrupamento.
 * - `locale` — quando informado, a formatação passa a ser `Intl.NumberFormat(locale)` e os
 *   separadores manuais são IGNORADOS (quem manda é o locale). Tag inválida cai de volta
 *   no caminho manual, sem lançar.
 * - `formatter` — `(value) => string`, tem precedência sobre tudo (controle total)
 * - `prefix` / `suffix` — texto antes/depois do valor (ou slots homônimos)
 * - `tone` — `'neutral' | 'success' | 'danger' | 'warning' | 'info'`: colore valor+ícone
 *   pelos tokens de estado (`--arcana-success-text`, …)
 * - `valueColor` — cor CSS arbitrária pro valor; vence o `tone` (vira inline
 *   `--arcana-statistic-value-color`)
 * - `size` — `'sm' | 'md' | 'lg' | 'xl'` (default `'md'`)
 * - `icon` — classe do ícone (ex: `'fa-solid fa-arrow-trend-up'`), renderizado antes do prefixo
 *
 * Slots: `title`, `prefix`, `suffix` (cada um sobrepõe a prop de mesmo nome).
 *
 * A formatação vive em `core/statistic.ts` (framework-agnóstica e testada), então os 4
 * ports produzem exatamente o mesmo texto.
 */
export default {
    name: 'ArcanaStatistic',

    props: {
        value: {
            type: [Number, String, null] as PropType<number | string | null>,
            default: null,
        },
        title: {
            type: String,
            default: '',
        },
        /** Alias de `title` (quem escreve `label` no resto da lib não precisa lembrar dos dois). */
        label: {
            type: String,
            default: '',
        },
        precision: {
            type: Number,
            default: undefined,
        },
        groupSeparator: {
            type: String,
            default: ',',
        },
        decimalSeparator: {
            type: String,
            default: '.',
        },
        locale: {
            type: String,
            default: '',
        },
        formatter: {
            type: Function as PropType<(value: number | string | null) => string>,
            default: undefined,
        },
        prefix: {
            type: String,
            default: '',
        },
        suffix: {
            type: String,
            default: '',
        },
        tone: {
            type: String as PropType<StatisticTone>,
            default: 'neutral',
            validator: (v: string) => ['neutral', 'success', 'danger', 'warning', 'info'].includes(v),
        },
        valueColor: {
            type: String,
            default: '',
        },
        size: {
            type: String as PropType<StatisticSize>,
            default: 'md',
            validator: (v: string) => ['sm', 'md', 'lg', 'xl'].includes(v),
        },
        icon: {
            type: String,
            default: '',
        },
    },

    computed: {
        resolvedTitle(): string {
            return this.title || this.label
        },

        hasTitle(): boolean {
            return Boolean(this.$slots.title || this.resolvedTitle)
        },

        hasPrefix(): boolean {
            return Boolean(this.$slots.prefix || this.prefix)
        },

        hasSuffix(): boolean {
            return Boolean(this.$slots.suffix || this.suffix)
        },

        /** Texto final do valor — `formatter` vence; senão, as regras do core. */
        displayValue(): string {
            if (this.formatter) return this.formatter(this.value ?? null)
            return formatStatisticValue(this.value, {
                precision: this.precision,
                groupSeparator: this.groupSeparator,
                decimalSeparator: this.decimalSeparator,
                locale: this.locale || undefined,
            })
        },
    },
} as Component
</script>
