// src/angular/arcana-countdown.component.ts
import {
  ChangeDetectionStrategy, ChangeDetectorRef, Component, EventEmitter, Input, NgZone,
  OnChanges, OnDestroy, OnInit, Output, SimpleChanges, inject
} from "@angular/core";

import {
  DEFAULT_COUNTDOWN_FORMAT,
  countdownTickInterval,
  formatDuration,
  remainingMs
} from "../core/countdown";

/**
 * `ArcanaCountdownComponent` — Angular port do SFC Vue `ArcanaCountdown`.
 *
 * Attribute selector num `<div>` (`<div arcanaCountdown>`): contagem regressiva até um
 * instante alvo. Reproduz `.arcana-countdown` (+ `--{size}`/`--{tone}`/`is-finished`/
 * `is-paused`), o `__title` e o `__content` com `__prefix`/`__value`/`__suffix`, idêntico ao
 * Vue/React/Svelte. Preserva o inline `--arcana-countdown-value-color`.
 *
 * Vue → Angular:
 * - `emit('change', ms)` → `@Output() change`; `emit('finish')` → `@Output() finish`
 * - métodos `pause()/resume()/restart()` → métodos públicos (via template ref / `ViewChild`)
 * - slots `#title`/`#prefix`/`#suffix` → conteúdo projetado `[countdownTitle]`/
 *   `[countdownPrefix]`/`[countdownSuffix]` (o wrapper só sai quando a prop correspondente
 *   tem valor)
 *
 * Timers: um único `setInterval`, criado FORA do Angular (`NgZone.runOutsideAngular`) pra não
 * disparar change detection global a cada tick; o componente é `OnPush` e chama
 * `markForCheck()` por tick, o que funciona também em app zoneless. O intervalo é sempre
 * limpo antes de recriar (troca de `value`/`format`/`interval`/pausa) e no `ngOnDestroy` —
 * nada acumula. Cada tick recalcula o restante a partir do relógio (sem drift).
 */
export type CountdownTone = "neutral" | "success" | "danger" | "warning" | "info";
export type CountdownSize = "sm" | "md" | "lg" | "xl";

@Component({
  selector: "div[arcanaCountdown]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.--arcana-countdown-value-color]": "valueColor || null",
    "role": "timer"
  },
  template: `
    @if (title) {
      <div class="arcana-countdown__title">
        <ng-content select="[countdownTitle]">{{ title }}</ng-content>
      </div>
    }

    <div class="arcana-countdown__content">
      @if (prefix) {
        <span class="arcana-countdown__prefix">
          <ng-content select="[countdownPrefix]">{{ prefix }}</ng-content>
        </span>
      }

      <span class="arcana-countdown__value">{{ displayValue }}</span>

      @if (suffix) {
        <span class="arcana-countdown__suffix">
          <ng-content select="[countdownSuffix]">{{ suffix }}</ng-content>
        </span>
      }
    </div>
  `
})
export class ArcanaCountdownComponent implements OnInit, OnChanges, OnDestroy {
  /** Instante ALVO: epoch em ms, `Date` ou string ISO. Inválido/vazio zera o contador. */
  @Input() value: number | string | Date | null = null;
  /**
   * Tokens `DD`,`D`,`HH`,`H`,`mm`,`m`,`ss`,`s`,`SSS`,`SS`,`S` + literais entre colchetes.
   * A maior unidade presente absorve o excedente (50h → `50:00:00` em `HH:mm:ss`).
   */
  @Input() format = DEFAULT_COUNTDOWN_FORMAT;
  @Input() prefix = "";
  @Input() suffix = "";
  @Input() title = "";
  @Input() tone: CountdownTone = "neutral";
  @Input() valueColor = "";
  @Input() size: CountdownSize = "md";
  /** Pausa a contagem (o valor congela). Voltar pra `false` retoma. */
  @Input() paused = false;
  /** Período do tick em ms. Default: 50ms com milissegundos no `format`, senão 1000ms. */
  @Input() interval?: number;
  @Input() className = "";

  @Output() change = new EventEmitter<number>();
  @Output() finish = new EventEmitter<void>();

  private readonly cdr = inject(ChangeDetectorRef);
  private readonly zone = inject(NgZone);

  private timer: ReturnType<typeof setInterval> | null = null;
  private hasFinished = false;

  remaining = 0;

  get displayValue(): string {
    return formatDuration(this.remaining, this.format);
  }

  get tickInterval(): number {
    return this.interval && this.interval > 0 ? this.interval : countdownTickInterval(this.format);
  }

  get rootClass(): string {
    return [
      "arcana-countdown",
      `arcana-countdown--${this.size}`,
      `arcana-countdown--${this.tone}`,
      this.remaining <= 0 ? "is-finished" : "",
      this.paused ? "is-paused" : "",
      this.className
    ].filter(Boolean).join(" ");
  }

  ngOnInit(): void {
    this.sync();
    if (!this.paused) this.start();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"] && !changes["value"].firstChange) {
      this.restart();
      return;
    }
    if (changes["paused"] && !changes["paused"].firstChange) {
      if (this.paused) this.stop();
      else this.start();
      return;
    }
    const retimed = changes["format"] || changes["interval"];
    if (retimed && !retimed.firstChange && !this.paused) this.start();
  }

  ngOnDestroy(): void {
    this.stop();
  }

  pause(): void {
    this.paused = true;
    this.stop();
    this.cdr.markForCheck();
  }

  resume(): void {
    this.paused = false;
    this.start();
    this.cdr.markForCheck();
  }

  /** Zera a trava do `finish` e recomeça a partir do `value` atual. */
  restart(): void {
    this.hasFinished = false;
    this.sync();
    if (!this.paused) this.start();
    this.cdr.markForCheck();
  }

  /** Recalcula o restante a partir do relógio. */
  private sync(): number {
    this.remaining = remainingMs(this.value, Date.now());
    return this.remaining;
  }

  /** (Re)cria o intervalo. Sempre limpa o anterior — nunca acumula. */
  private start(): void {
    this.stop();
    if (this.hasFinished) return;
    if (this.sync() <= 0) {
      this.hasFinished = true;
      this.finish.emit();
      return;
    }
    // Fora da zona: o tick não deve disparar CD global — o `markForCheck` abaixo
    // acorda só este componente (e funciona igual em app zoneless).
    this.zone.runOutsideAngular(() => {
      this.timer = setInterval(() => this.tick(), this.tickInterval);
    });
  }

  private tick(): void {
    const rest = this.sync();
    this.cdr.markForCheck();
    this.zone.run(() => {
      this.change.emit(rest);
      if (rest <= 0 && !this.hasFinished) {
        this.hasFinished = true;
        this.stop();
        this.finish.emit();
      }
    });
  }

  private stop(): void {
    if (this.timer !== null) {
      clearInterval(this.timer);
      this.timer = null;
    }
  }
}

// src/vue/components/ArcanaCountdown.vue
<template>
    <div
        class="arcana-countdown"
        :class="[
            `arcana-countdown--${size}`,
            `arcana-countdown--${tone}`,
            { 'is-finished': isFinished, 'is-paused': isPaused },
        ]"
        :style="valueColor ? { '--arcana-countdown-value-color': valueColor } : undefined"
        role="timer"
    >
        <div v-if="hasTitle" class="arcana-countdown__title">
            <slot name="title">{{ title }}</slot>
        </div>

        <div class="arcana-countdown__content">
            <span v-if="hasPrefix" class="arcana-countdown__prefix">
                <slot name="prefix">{{ prefix }}</slot>
            </span>

            <span class="arcana-countdown__value">{{ displayValue }}</span>

            <span v-if="hasSuffix" class="arcana-countdown__suffix">
                <slot name="suffix">{{ suffix }}</slot>
            </span>
        </div>
    </div>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

import {
    DEFAULT_COUNTDOWN_FORMAT,
    countdownTickInterval,
    formatDuration,
    remainingMs,
} from "../../core/countdown"

type CountdownTone = 'neutral' | 'success' | 'danger' | 'warning' | 'info'
type CountdownSize = 'sm' | 'md' | 'lg' | 'xl'

/**
 * `<ArcanaCountdown>` — contagem regressiva até um instante alvo. Mesma anatomia do
 * `<ArcanaStatistic>` (título em cima, `[prefixo] VALOR [sufixo]` embaixo), só que o valor
 * é o tempo restante, re-renderizado a cada tick.
 *
 * API:
 * - `value` — instante ALVO: epoch em ms (`number`), `Date` ou string ISO. Valor inválido/
 *   vazio zera o contador em vez de virar `NaN`.
 * - `format` (default `'HH:mm:ss'`) — tokens `DD`,`D`,`HH`,`H`,`mm`,`m`,`ss`,`s`,`SSS`,`SS`,`S`
 *   e literais entre colchetes (`'DD [dias] HH:mm:ss'`). **A maior unidade presente absorve
 *   o excedente**: 50h viram `50:00:00` em `HH:mm:ss` (nada de tempo sumindo silenciosamente).
 * - `prefix` / `suffix` / `title` — textos (ou slots homônimos)
 * - `tone` / `valueColor` / `size` — idem `ArcanaStatistic`
 * - `paused` — pausa a contagem (o valor congela). Reativo: voltar pra `false` retoma.
 * - `interval` — período do tick em ms. Default automático: 50ms quando o `format` mostra
 *   milissegundos, 1000ms caso contrário.
 *
 * Eventos:
 * - `change(remaining: number)` — a cada tick, com o restante em ms
 * - `finish()` — uma única vez, ao zerar
 *
 * Métodos (via `ref`): `pause()`, `resume()`, `restart()`.
 *
 * Timers: um único `setInterval`, sempre limpo antes de recriar e no `beforeUnmount` — nada
 * de intervalos acumulando ao trocar `value`/`format`. Cada tick recalcula o restante a
 * partir do relógio, então o intervalo só controla a taxa de refresh (não acumula drift).
 *
 * A formatação vive em `core/countdown.ts` (framework-agnóstica e testada).
 */
export default {
    name: 'ArcanaCountdown',

    emits: ['change', 'finish'],

    props: {
        value: {
            type: [Number, String, Date, null] as PropType<number | string | Date | null>,
            default: null,
        },
        format: {
            type: String,
            default: DEFAULT_COUNTDOWN_FORMAT,
        },
        prefix: {
            type: String,
            default: '',
        },
        suffix: {
            type: String,
            default: '',
        },
        title: {
            type: String,
            default: '',
        },
        tone: {
            type: String as PropType<CountdownTone>,
            default: 'neutral',
            validator: (v: string) => ['neutral', 'success', 'danger', 'warning', 'info'].includes(v),
        },
        valueColor: {
            type: String,
            default: '',
        },
        size: {
            type: String as PropType<CountdownSize>,
            default: 'md',
            validator: (v: string) => ['sm', 'md', 'lg', 'xl'].includes(v),
        },
        paused: {
            type: Boolean,
            default: false,
        },
        /** Período do tick em ms. Sem valor, deriva do `format` (50ms com `S*`, senão 1000ms). */
        interval: {
            type: Number,
            default: undefined,
        },
    },

    data() {
        return {
            remaining: 0,
            isPaused: this.paused,
            /** Trava do `finish` (evita re-emitir a cada tick depois de zerar). */
            hasFinished: false,
            timer: null as ReturnType<typeof setInterval> | null,
        }
    },

    computed: {
        displayValue(): string {
            return formatDuration(this.remaining, this.format)
        },

        isFinished(): boolean {
            return this.remaining <= 0
        },

        hasTitle(): boolean {
            return Boolean(this.$slots.title || this.title)
        },

        hasPrefix(): boolean {
            return Boolean(this.$slots.prefix || this.prefix)
        },

        hasSuffix(): boolean {
            return Boolean(this.$slots.suffix || this.suffix)
        },

        tickInterval(): number {
            return this.interval && this.interval > 0 ? this.interval : countdownTickInterval(this.format)
        },
    },

    watch: {
        value() {
            this.restart()
        },
        format() {
            // O tick derivado do formato pode ter mudado (ms ↔ segundos).
            if (!this.isPaused) this.start()
        },
        interval() {
            if (!this.isPaused) this.start()
        },
        paused(value: boolean) {
            this.isPaused = value
            if (value) this.stop()
            else this.start()
        },
    },

    mounted() {
        this.sync()
        if (!this.isPaused) this.start()
    },

    beforeUnmount() {
        this.stop()
    },

    methods: {
        /** Recalcula o restante a partir do relógio e resolve o `finish`. */
        sync(): number {
            const rest = remainingMs(this.value, Date.now())
            this.remaining = rest
            return rest
        },

        tick() {
            const rest = this.sync()
            this.$emit('change', rest)
            if (rest <= 0 && !this.hasFinished) {
                this.hasFinished = true
                this.stop()
                this.$emit('finish')
            }
        },

        /** (Re)cria o intervalo. Sempre limpa o anterior — nunca acumula. */
        start() {
            this.stop()
            if (this.hasFinished) return
            if (this.sync() <= 0) {
                this.hasFinished = true
                this.$emit('finish')
                return
            }
            this.timer = setInterval(() => this.tick(), this.tickInterval)
        },

        stop() {
            if (this.timer !== null) {
                clearInterval(this.timer)
                this.timer = null
            }
        },

        pause() {
            this.isPaused = true
            this.stop()
        },

        resume() {
            this.isPaused = false
            this.start()
        },

        /** Zera a trava do `finish` e recomeça a partir do `value` atual. */
        restart() {
            this.hasFinished = false
            this.sync()
            if (!this.isPaused) this.start()
        },
    },
} as Component
</script>
