// src/react/ArcanaButton.tsx
import type { MouseEvent, ReactNode } from "react";

/**
 * `<ArcanaButton>` — React port do SFC Vue de mesmo nome. Emite o MESMO markup e as
 * MESMAS classes (`arcana-button`, `arcana-button--${variant}`, `is-disabled`) pra
 * reusar o CSS compartilhado (`@arcanalabs/ui-components/styles.css`).
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 * - `emit('click', ev)` → `onClick(ev)`
 */
export type ArcanaButtonVariant =
    | "primary"
    | "outline"
    | "outline-danger"
    | "ghost"
    | "danger"
    | "destructive"
    | "destructive-outline"
    | "success"
    | "secondary"
    | "dark"
    | "indigo"
    | "alert"
    | "info"
    | "warning"
    | "teal";

export interface ArcanaButtonProps {
    variant?: ArcanaButtonVariant;
    type?: "button" | "submit";
    disabled?: boolean;
    onClick?: (ev: MouseEvent<HTMLButtonElement>) => void;
    className?: string;
    children?: ReactNode;
}

export function ArcanaButton({
    variant = "primary",
    type = "button",
    disabled = false,
    onClick,
    className,
    children,
}: ArcanaButtonProps) {
    const classes = [
        "arcana-button",
        `arcana-button--${variant}`,
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <button
            type={type}
            className={classes}
            disabled={disabled}
            onClick={(ev) => onClick?.(ev)}
        >
            {children}
        </button>
    );
}

// src/vue/components/ArcanaButton.vue
<template>
    <button
        :type="type"
        class="arcana-button"
        :class="[`arcana-button--${variant}`, { 'is-disabled': disabled }]"
        :disabled="disabled"
        @click="onClick"
    >
        <slot />
    </button>
</template>

<script setup lang="ts">
defineOptions({ name: "ArcanaButton" })

withDefaults(defineProps<{
    variant?: "primary" | "outline" | "outline-danger" | "ghost" | "danger" | "destructive" | "destructive-outline" | "success" | "secondary" | "dark" | "indigo" | "alert" | "info" | "warning" | "teal"
    type?: "button" | "submit"
    disabled?: boolean
}>(), {
    variant: "primary",
    type: "button",
    disabled: false,
})

const emit = defineEmits<{ (e: "click", ev: MouseEvent): void }>()

function onClick(ev: MouseEvent) {
    emit("click", ev)
}
</script>
