// src/svelte/ArcanaSpecSheetField.svelte
<script lang="ts">
  /**
   * `<ArcanaSpecSheetField>` — Svelte 5 port do SFC Vue. Campo individual da
   * `<ArcanaSpecSheetSection>`: label uppercase mono + valor. Valor vazio mostra
   * `emptyText` em italic muted. Slot default substitui o valor (badges/HTML custom).
   *
   * slot default → snippet `children` (quando presente, NUNCA renderiza como vazio).
   */
  import type { Snippet } from "svelte";

  let {
    label,
    value = "",
    emptyText = "Não informado",
    span = 1,
    children,
  }: {
    label: string;
    value?: string | number | null;
    emptyText?: string;
    span?: number | string;
    children?: Snippet;
  } = $props();

  const isEmpty = $derived(
    !children && (value === null || value === undefined || value === "")
  );
  const displayValue = $derived(isEmpty ? emptyText : String(value));

  const valueClasses = $derived(
    ["arcana-spec-sheet__value", isEmpty ? "arcana-spec-sheet__value--empty" : ""]
      .filter(Boolean)
      .join(" ")
  );
</script>

<div class="arcana-spec-sheet__field" style={Number(span) > 1 ? `grid-column:span ${span};` : undefined}>
  <div class="arcana-spec-sheet__label">{label}</div>
  <div class={valueClasses}>
    {#if children}{@render children()}{:else}{displayValue}{/if}
  </div>
</div>

// src/vue/components/ArcanaSpecSheetField.vue
<template>
    <div class="arcana-spec-sheet__field" :style="Number(span) > 1 ? { gridColumn: 'span ' + span } : null">
        <div class="arcana-spec-sheet__label">{{ label }}</div>
        <div
            class="arcana-spec-sheet__value"
            :class="{ 'arcana-spec-sheet__value--empty': isEmpty }"
        >
            <slot>{{ displayValue }}</slot>
        </div>
    </div>
</template>

<script lang="ts">
import type { Component } from "vue"

/**
 * `<ArcanaSpecSheetField>` — campo individual no `<ArcanaSpecSheetSection>`.
 *
 * Renderiza label uppercase mono + valor Inter. Quando o `value` é vazio
 * (null/undefined/empty string), mostra `emptyText` em italic muted (default
 * "Não informado") pra deixar claro que não é um valor real.
 *
 * Pra valores complexos (badges, links, ícones), use o slot default:
 *
 *     <ArcanaSpecSheetField label="Status">
 *         <span class="arcana-spec-sheet-badge arcana-spec-sheet-badge--active">Ativo</span>
 *     </ArcanaSpecSheetField>
 *
 * API:
 * - `label` — uppercase mono (ex: "Razão Social", "CNPJ")
 * - `value` — texto direto. Pode ser string/number/null/undefined.
 * - `emptyText` — fallback quando value é vazio (default `'Não informado'`)
 *
 * Slot:
 * - `default` — substitui o valor renderizado (use pra HTML/badges custom)
 */
export default {
    name: 'ArcanaSpecSheetField',

    props: {
        label: {
            type: String,
            required: true,
        },
        value: {
            type: [String, Number, null] as any,
            default: '',
        },
        emptyText: {
            type: String,
            default: 'Não informado',
        },
        // Quantas colunas do grid o campo ocupa (ex: `:span="2"` pra um campo mais largo).
        span: {
            type: [Number, String],
            default: 1,
        },
    },

    computed: {
        isEmpty(): boolean {
            // Slot default sobrepõe o display de value — se há slot, NUNCA mostra como vazio
            // (caller decidiu o conteúdo). Sem slot, checa se value tem conteúdo útil.
            if (this.$slots.default) return false
            const v = this.value
            return v === null || v === undefined || v === ''
        },
        displayValue(): string {
            if (this.isEmpty) return this.emptyText
            return String(this.value)
        },
    },
} as Component
</script>
