// src/angular/arcana-accordion.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ArcanaAccordionComponent` — Angular port do SFC Vue `ArcanaAccordion`.
 *
 * Attribute selector num `<div>` (`<div arcanaAccordion>`): container `.arcana-accordion`.
 * O `provide`/`inject` do `accordionApi` (Vue) vira DI de componente pai: cada
 * `ArcanaAccordionItemComponent` injeta esta instância via `inject(ArcanaAccordionComponent)`.
 *
 * Vue → Angular:
 * - `modelValue` (v-model, `string | string[] | null`) → `value` + `@Output() valueChange`
 * - `accordion` (single-open) → `@Input() accordion`
 * - `animated` → `@Input() animated`
 * - slot default → `<ng-content>`
 *
 * `animated` (default `false`) liga a transição de altura (0 → altura real medida) + fade,
 * ~200ms. O `ArcanaAccordionItemComponent` também aceita `animated` e, quando informada lá,
 * ela tem **precedência** sobre a do container (permite um item animado num accordion
 * estático e vice-versa). Respeita `prefers-reduced-motion: reduce` (sem animação).
 */
@Component({
  selector: "div[arcanaAccordion]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "class": "arcana-accordion"
  },
  template: `<ng-content></ng-content>`
})
export class ArcanaAccordionComponent {
  @Input() value: string | string[] | null = null;
  /** `true` (default): só um item aberto por vez. `false`: múltiplos (array). */
  @Input() accordion = true;
  /** `false` (default): abre/fecha instantâneo. `true`: slide de altura + fade (~200ms). */
  @Input() animated = false;

  @Output() valueChange = new EventEmitter<string | string[] | null>();

  isOpen(name: string): boolean {
    if (Array.isArray(this.value)) return this.value.includes(name);
    return this.value === name;
  }

  toggle(name: string): void {
    if (this.accordion) {
      this.valueChange.emit(this.value === name ? null : name);
      return;
    }
    const current = Array.isArray(this.value) ? [...this.value] : [];
    const idx = current.indexOf(name);
    if (idx >= 0) current.splice(idx, 1);
    else current.push(name);
    this.valueChange.emit(current);
  }
}

// src/vue/components/ArcanaAccordion.vue
<template>
    <div class="arcana-accordion">
        <slot />
    </div>
</template>

<script lang="ts">
import { defineComponent, type PropType } from "vue"

/**
 * `<ArcanaAccordion>` — container dos itens colapsáveis.
 *
 * Compartilha estado com os `<ArcanaAccordionItem>` via `provide`/`inject`
 * (`accordionApi`): quem está aberto (`isOpen`), como alternar (`toggle`) e se o
 * expandir/recolher é animado (`animated`).
 *
 * Props:
 * - `modelValue` (v-model) — `string | string[] | null`: item(ns) aberto(s)
 * - `accordion` — `true` (default): só um item aberto por vez; `false`: múltiplos (array)
 * - `animated` — `false` (default): abre/fecha instantâneo (comportamento histórico).
 *   `true`: transição de altura (0 → altura real medida) + fade, ~200ms.
 *   Cada `<ArcanaAccordionItem>` também aceita `animated`; quando informada no item,
 *   ela tem **precedência** sobre a do container (permite um item animado dentro de um
 *   accordion estático e vice-versa). Respeita `prefers-reduced-motion: reduce`
 *   (sem animação nesse caso).
 */
export default defineComponent({
    name: "ArcanaAccordion",
    props: {
        modelValue: { type: [String, Array, null] as PropType<string | string[] | null>, default: null },
        accordion: { type: Boolean, default: true },
        animated: { type: Boolean, default: false },
    },
    emits: ["update:modelValue"],
    provide() {
        return {
            accordionApi: {
                isOpen: (name: string) => this.isOpen(name),
                toggle: (name: string) => this.toggle(name),
                // Closure (e não valor cru) pra preservar a reatividade no item.
                animated: () => this.animated,
            },
        }
    },
    methods: {
        isOpen(name: string): boolean {
            const v = this.modelValue
            if (Array.isArray(v)) return v.includes(name)
            return v === name
        },
        toggle(name: string) {
            if (this.accordion) {
                this.$emit("update:modelValue", this.modelValue === name ? null : name)
                return
            }
            const current = Array.isArray(this.modelValue) ? [...this.modelValue] : []
            const idx = current.indexOf(name)
            if (idx >= 0) current.splice(idx, 1)
            else current.push(name)
            this.$emit("update:modelValue", current)
        },
    },
})
</script>
