// src/angular/input-currency.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, OnChanges, Output, SimpleChanges,
  TemplateRef
} from "@angular/core";
import { NgTemplateOutlet } from "@angular/common";
import { CurrencyFormatter } from "../core/currency";

/**
 * `InputCurrencyComponent` — Angular port do SFC Vue `InputCurrency`. Input de moeda BRL.
 *
 * Decisão sobre a lib (mesma do React — sem deps novas):
 * - O SFC usa `v-money3` (Vue-only). Reimplementamos a mesma máscara de moeda right-to-left
 *   (dígitos preenchem dos centavos pra cima), mantendo markup/classes (`icur-shadcn-field`/
 *   `icur-shadcn-input` no modo shadcn; `input-group`/`form-control` no Bootstrap).
 * - Comportamento observável preservado: o `modelValue` emitido é a STRING mascarada BRL
 *   (ex. `"1.234,56"`), igual ao default do v-money3 no SFC.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change'|'enter'|'blur')`
 *   → `@Output() change`/`enter`/`blur`
 * - slots `#prepend`/`#append` → `@Input() prependTemplate`/`appendTemplate` (TemplateRef)
 */
const DECIMAL = ",";
const THOUSANDS = ".";

function digitsFromValue(v: string | number | undefined, precision: number): string {
  if (v == null || v === "") return "";
  if (typeof v === "number") {
    return String(Math.round(Math.abs(v) * Math.pow(10, precision)));
  }
  const s = String(v);
  if (s.includes(DECIMAL)) return s.replace(/\D/g, "");
  const n = parseFloat(s);
  if (!isFinite(n)) return s.replace(/\D/g, "");
  return String(Math.round(Math.abs(n) * Math.pow(10, precision)));
}

function formatDigits(digits: string, precision: number, prefix: string): string {
  let d = digits.replace(/\D/g, "");
  if (!d) d = "0";
  if (precision > 0) d = d.padStart(precision + 1, "0");
  const cut = precision > 0 ? d.length - precision : d.length;
  let intPart = d.slice(0, cut).replace(/^0+(?=\d)/, "");
  const fracPart = precision > 0 ? d.slice(cut) : "";
  intPart = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, THOUSANDS);
  return prefix + intPart + (precision > 0 ? DECIMAL + fracPart : "");
}

@Component({
  selector: "div[arcanaInputCurrency]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgTemplateOutlet],
  host: { "[class]": "wrapClasses" },
  template: `
    @if (prependTemplate) {
      <ng-container [ngTemplateOutlet]="prependTemplate"></ng-container>
    } @else {
      @if (showIcon && !shadcn) {
        <span class="input-group-addon"><i [class]="icon"></i></span>
      }
      @if (showIcon && shadcn) {
        <span class="icur-shadcn-field__icon"><i [class]="icon"></i></span>
      }
    }

    @if (!isDisabled) {
      <input
        type="text"
        [class]="inputClasses"
        [attr.name]="name ?? null"
        [value]="display"
        (input)="onInput($event)"
        (keyup)="onKeyup($event)"
        (blur)="onBlurEvent($event)"
      />
    } @else {
      <input
        disabled
        [class]="disabledInputClasses"
        type="text"
        [value]="formattedCurrency"
        readonly
      />
    }

    @if (appendTemplate) {
      <ng-container [ngTemplateOutlet]="appendTemplate"></ng-container>
    }
  `
})
export class InputCurrencyComponent implements OnChanges {
  @Input() value: string | number = "";
  @Input() disabled: boolean | number = false;
  @Input() fraction = 2;
  @Input() name?: string;
  @Input() showIcon = true;
  @Input() prefix = "";
  @Input() icon = "icon-coin-dollar";
  @Input() formatCurrency = true;
  @Input() shadcn = false;
  @Input() prependTemplate?: TemplateRef<unknown>;
  @Input() appendTemplate?: TemplateRef<unknown>;
  @Input() className = "";

  @Output() valueChange = new EventEmitter<string>();
  @Output() change = new EventEmitter<unknown>();
  @Output() enter = new EventEmitter<KeyboardEvent>();
  @Output() blur = new EventEmitter<FocusEvent>();

  display = "";

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["value"] || changes["fraction"] || changes["prefix"]) {
      const incoming = digitsFromValue(this.value, this.fraction);
      const current = this.display.replace(/\D/g, "");
      if (incoming.replace(/^0+(?=\d)/, "") !== current.replace(/^0+(?=\d)/, "")) {
        this.display = formatDigits(incoming, this.fraction, this.prefix);
      }
    }
  }

  get isDisabled(): boolean {
    return Boolean(this.disabled);
  }

  get formattedCurrency(): string {
    return String(this.formatCurrency ? CurrencyFormatter.format(this.value || 0) : this.value);
  }

  get inputClasses(): string {
    return [
      this.shadcn ? "icur-shadcn-input" : "form-control",
      this.shadcn && this.showIcon ? "has-icon" : "",
      this.className
    ].filter(Boolean).join(" ");
  }

  get disabledInputClasses(): string {
    return [
      this.shadcn ? "icur-shadcn-input" : "form-control",
      this.shadcn && this.showIcon ? "has-icon" : "",
      "full-width"
    ].filter(Boolean).join(" ");
  }

  get wrapClasses(): string {
    if (this.shadcn) {
      return ["icur-shadcn-field", this.isDisabled ? "is-disabled" : ""].filter(Boolean).join(" ");
    }
    return this.showIcon ? "input-group" : "";
  }

  onInput(e: Event): void {
    const digits = (e.target as HTMLInputElement).value.replace(/\D/g, "");
    const formatted = formatDigits(digits, this.fraction, this.prefix);
    this.display = formatted;
    this.valueChange.emit(formatted);
  }

  onKeyup(e: KeyboardEvent): void {
    if (e.key === "Enter") this.enter.emit(e);
  }

  onBlurEvent(e: FocusEvent): void {
    this.change.emit(this.display);
    this.blur.emit(e);
  }
}

// src/vue/components/InputCurrency.vue
<template>
    <div :class="shadcn ? ['icur-shadcn-field', { 'is-disabled': disabled }] : (showIcon ? 'input-group' : '')">
        <slot name="prepend">
            <span class="input-group-addon" v-if="showIcon && !shadcn"><i :class="icon"></i></span>
            <span class="icur-shadcn-field__icon" v-if="showIcon && shadcn"><i :class="icon"></i></span>
        </slot>

        <VueMoney
            v-show="!disabled"
            :class="[shadcn ? 'icur-shadcn-input' : 'form-control', { 'has-icon': shadcn && showIcon }, $attrs.class]"
            v-bind="formatting"
            ref="input"
            :precision="fraction"
            @update:modelValue="change"
            @keyup.enter="$emit('enter', $event)"
            @keyup="keyUp"
            @change="$emit('change', $event)"
            @blur="$emit('blur', $event)"
            :max="max"
            :min="min"
            :allow-blank="allowBlank && displayBlankValue"
            :model-value="input()"
        />

        <input disabled :class="[shadcn ? 'icur-shadcn-input' : 'form-control', { 'has-icon': shadcn && showIcon }, 'full-width']" v-show="disabled" type="text" :value="formattedCurrency">

        <slot name="append"></slot>
    </div>
</template>

<script lang="ts">
import {Money3Component} from 'v-money3'
import {CurrencyFormatter} from "../../core/currency"
import type {Component} from "@vue/runtime-core"

export default {
    emits: ['change', 'enter', 'blur', 'update:modelValue'],
    inheritAttrs: false,

    components: {VueMoney: Money3Component},

    props: {
        disabled: {
            type: [Boolean, Number],
            default: false
        },
        allowBlank: {
            type: Boolean,
            default: false,
        },
        fraction: {
            type: Number,
            default: 2
        },
        name: String,
        modelValue: [String, Number],
        showIcon: {
            type: Boolean,
            default: true
        },
        prefix: {
            type: String,
            default: ""
        },
        icon: {
            type: String,
            default: "icon-coin-dollar"
        },
        max: {
            type: Number,
            default: Number.MAX_SAFE_INTEGER
        },
        min: {
            type: Number,
        },
        formatCurrency: {
            type: Boolean,
            default: true
        },
        /**
         * Estilo shadcn (palette zinc, igual `<ShadcnInput>`). Quando `true`, troca o
         * `form-control` Bootstrap pelo input shadcn e esconde o addon de ícone `$`.
         */
        shadcn: {
            type: Boolean,
            default: false,
        },
    },

    computed: {
        formattedCurrency() {
            if (!this.formatCurrency) {
                return this.modelValue
            }

            return CurrencyFormatter.format(this.modelValue || 0)
        }
    },

    data() {
        return {
            displayBlankValue: false,

            formatting: {
                decimal: ",",
                thousands: ".",
                prefix: this.prefix,
                precision: this.fraction
            }
        }
    },

    methods: {
        input() {
            return this.modelValue || "0," + ("0".repeat(this.fraction))
        },

        keyUp(e: any) {
            if (e.key == '0') {
                this.displayBlankValue = false
            } else {
                this.displayBlankValue = true
            }
        },

        change(val: any) {
            this.$emit("update:modelValue", val)
        },

        focus() {
            (this.$refs.input as { focus: () => void }).focus()
        }
    }
} as Component
</script>

<!--
  Estilo NÃO-scoped (classe única `icur-shadcn-input`) porque o `<VueMoney>` (v-money3)
  renderiza um <input> filho — um `<style scoped>` do wrapper não atingiria de forma
  confiável o elemento interno. Espelha `.shadcn-input` do `<ShadcnInput>`.
-->
