// src/svelte/ShadcnDropdownItem.svelte
<script lang="ts">
  /**
   * `<ShadcnDropdownItem>` — Svelte 5 port do SFC Vue. Item do `<ShadcnDropdown>`:
   * ícone + label + (opcional) suffix.
   *
   * Equivalências Vue → Svelte 5:
   * - `inject('shadcnDropdownSize')` → `getContext(DROPDOWN_CONTEXT)` (herda densidade do pai)
   * - CustomEvent `shadcn-dropdown-close` → chama `ctx.close()` direto quando `closeOnClick`
   * - slot default → snippet `children`; slot `#suffix` → snippet `suffix`
   * - `emit('click')` → callback `onClick`
   */
  import type { Snippet } from "svelte";
  import { getContext } from "svelte";
  import {
    DROPDOWN_CONTEXT,
    type DropdownContextValue,
    type ShadcnDropdownSize,
  } from "./ShadcnDropdown.svelte";

  let {
    icon = "",
    iconColor = "",
    variant = "default",
    disabled = false,
    divided = false,
    closeOnClick = true,
    size = null,
    suffix,
    children,
    onClick,
  }: {
    icon?: string;
    iconColor?: string;
    variant?: "default" | "danger" | "success" | "warning";
    disabled?: boolean;
    divided?: boolean;
    closeOnClick?: boolean;
    size?: ShadcnDropdownSize | null;
    suffix?: Snippet;
    children?: Snippet;
    onClick?: (e: MouseEvent) => void;
  } = $props();

  // Contexto do `<ShadcnDropdown>` pai (fallback quando usado standalone).
  const ctx = getContext<DropdownContextValue | undefined>(DROPDOWN_CONTEXT);

  const effectiveSize = $derived(size ?? ctx?.size ?? "default");

  const classes = $derived(
    [
      "shadcn-dropdown-item",
      variant ? `shadcn-dropdown-item--${variant}` : "",
      effectiveSize === "comfortable" ? "shadcn-dropdown-item--comfortable" : "",
      disabled ? "is-disabled" : "",
    ]
      .filter(Boolean)
      .join(" ")
  );

  function handleClick(e: MouseEvent) {
    if (disabled) return;
    onClick?.(e);
    if (closeOnClick) ctx?.close();
  }
</script>

{#if divided}
  <div class="shadcn-dropdown-item__separator"></div>
{/if}

<button
  type="button"
  class={classes}
  {disabled}
  role="menuitem"
  onclick={handleClick}
>
  {#if icon}
    <i
      class={`shadcn-dropdown-item__icon ${icon}`}
      style={iconColor ? `color:${iconColor};` : undefined}
      aria-hidden="true"
    ></i>
  {/if}
  <span class="shadcn-dropdown-item__label">{@render children?.()}</span>
  {#if suffix}
    <span class="shadcn-dropdown-item__suffix">{@render suffix()}</span>
  {/if}
</button>

// src/vue/components/ShadcnDropdownItem.vue
<template>
    <div v-if="divided" class="shadcn-dropdown-item__separator"></div>

    <button
        type="button"
        class="shadcn-dropdown-item"
        :class="[
            variant ? `shadcn-dropdown-item--${variant}` : null,
            effectiveSize === 'comfortable' ? 'shadcn-dropdown-item--comfortable' : null,
            { 'is-disabled': disabled },
        ]"
        :disabled="disabled"
        role="menuitem"
        @click="handleClick"
    >
        <i v-if="icon" :class="['shadcn-dropdown-item__icon', icon]" :style="iconColor ? { color: iconColor } : null" aria-hidden="true"></i>
        <span class="shadcn-dropdown-item__label"><slot/></span>
        <span v-if="$slots.suffix" class="shadcn-dropdown-item__suffix"><slot name="suffix"/></span>
    </button>
</template>

<script lang="ts">
import type { Component } from "vue"

/**
 * Item do `<ShadcnDropdown>`. Apresenta ícone + label + (opcional) suffix.
 *
 * Variants:
 * - default — texto neutro (#18181b)
 * - danger  — texto vermelho, hover bg rosa (#fef2f2). Use pra deletar.
 * - success — texto verde, hover bg verde claro. Use pra confirmar/salvar.
 *
 * `divided`: insere uma linha separadora ANTES deste item (útil pra agrupar
 * "deletar" longe das ações benignas). Espelha o `divided` do el-dropdown.
 *
 * `closeOnClick` (default true): após o handler do `@click` rodar, dispara
 * um CustomEvent `shadcn-dropdown-close` que o parent escuta pra fechar.
 * Setar false pra items que mostram sub-menu ou expandem alguma seção
 * interna sem fechar o dropdown.
 */
export default {
    name: 'ShadcnDropdownItem',

    props: {
        icon: String,
        /** Cor custom só do ícone (ex: "#16a34a"). Não afeta o texto nem o hover.
         *  Pra colorir o item inteiro, use `variant`. */
        iconColor: { type: String, default: '' },
        variant: {
            type: String as () => 'default' | 'danger' | 'success' | 'warning',
            default: 'default',
        },
        disabled: { type: Boolean, default: false },
        divided: { type: Boolean, default: false },
        closeOnClick: { type: Boolean, default: true },
        /**
         * Densidade do item. Normalmente herdada do `<ShadcnDropdown size>` via
         * inject; passar aqui sobrescreve só este item.
         */
        size: {
            type: String as () => 'default' | 'comfortable' | null,
            default: null,
        },
    },

    // Herda a densidade do ShadcnDropdown pai (provide). Default 'default'
    // quando usado fora de um dropdown com size definido.
    inject: {
        shadcnDropdownSize: { default: 'default' },
    },

    emits: ['click'],

    computed: {
        // Prop local `size` tem prioridade sobre o valor herdado por inject.
        effectiveSize(): string {
            return this.size ?? (this as any).shadcnDropdownSize
        },
    },

    methods: {
        handleClick(e: MouseEvent) {
            if (this.disabled) return
            this.$emit('click', e)

            // CustomEvent bubbla pro <document> onde o ShadcnDropdown ouve e fecha.
            // Evita acoplamento via provide/inject — funciona mesmo com Teleport
            // (que quebra a hierarquia DOM mas mantém parent-child Vue).
            if (this.closeOnClick) {
                e.target?.dispatchEvent?.(new CustomEvent('shadcn-dropdown-close', { bubbles: true }))
            }
        },
    },
} as Component
</script>
