// src/svelte/ShadcnNotice.svelte
<script lang="ts" module>
  export type NoticeVariant =
    | "info" | "blue" | "success" | "warning" | "pending" | "destructive";

  const VARIANT_DEFAULT_ICONS: Record<NoticeVariant, string> = {
    info: "fa-solid fa-circle-info",
    blue: "fa-solid fa-circle-info",
    success: "fa-solid fa-circle-check",
    warning: "fa-solid fa-triangle-exclamation",
    pending: "fa-solid fa-clock",
    destructive: "fa-solid fa-circle-exclamation",
  };
</script>

<script lang="ts">
  import type { Snippet } from "svelte";

  /**
   * `<ShadcnNotice>` — Svelte 5 port. Banner informativo com variants semânticas. Reproduz
   * `<div class="shadcn-notice shadcn-notice--${variant}">` com `__icon`/`__content`/
   * `__title`/`__body` e o botão `__close` opcional, idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - slot default → snippet `children`; slots `#title`/`#icon` → props `title`/`iconNode`
   * - `emit('dismiss')` → `onDismiss`
   */
  let {
    variant = "info",
    title = "",
    icon = "",
    iconNode,
    showIcon = true,
    dismissible = false,
    onDismiss,
    class: className = "",
    children,
  }: {
    variant?: NoticeVariant;
    title?: string | Snippet;
    icon?: string;
    iconNode?: Snippet;
    showIcon?: boolean;
    dismissible?: boolean;
    onDismiss?: () => void;
    class?: string;
    children?: Snippet;
  } = $props();

  const resolvedIcon = $derived(icon || VARIANT_DEFAULT_ICONS[variant]);
  const rootClasses = $derived(
    ["shadcn-notice", `shadcn-notice--${variant}`, className].filter(Boolean).join(" ")
  );
</script>

<div class={rootClasses} role="status">
  {#if showIcon}
    <span class="shadcn-notice__icon" aria-hidden="true">
      {#if iconNode}{@render iconNode()}{:else}<i class={resolvedIcon}></i>{/if}
    </span>
  {/if}

  <div class="shadcn-notice__content">
    {#if title}
      <strong class="shadcn-notice__title">
        {#if typeof title === "function"}{@render title()}{:else}{title}{/if}
      </strong>
    {/if}
    <div class="shadcn-notice__body">{@render children?.()}</div>
  </div>

  {#if dismissible}
    <button type="button" class="shadcn-notice__close" aria-label="Fechar" onclick={() => onDismiss?.()}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
      </svg>
    </button>
  {/if}
</div>

// src/vue/components/ShadcnNotice.vue
<template>
    <div class="shadcn-notice" :class="rootClasses" role="status">
        <span v-if="showIcon" class="shadcn-notice__icon" aria-hidden="true">
            <slot name="icon">
                <i :class="resolvedIcon"></i>
            </slot>
        </span>

        <div class="shadcn-notice__content">
            <strong v-if="title || $slots.title" class="shadcn-notice__title">
                <slot name="title">{{ title }}</slot>
            </strong>
            <div class="shadcn-notice__body">
                <slot />
            </div>
        </div>

        <button
            v-if="dismissible"
            type="button"
            class="shadcn-notice__close"
            aria-label="Fechar"
            @click="$emit('dismiss')"
        >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
            </svg>
        </button>
    </div>
</template>

<script lang="ts">
import type { Component, PropType } from "vue"

/**
 * `<ShadcnNotice>` — banner informativo com variants semânticas.
 *
 * Use pra:
 * - Avisos contextuais (Pagamento manual, Sub bloqueada, etc)
 * - Status cards (Aguardando ativação Stripe, Migração concluída, etc)
 * - Erros não-bloqueantes (Falha ao carregar, retry available, etc)
 *
 * Variants:
 * - `info` (default) — zinc neutro, ícone `fa-circle-info`
 * - `blue` — azul suave, ícone `fa-circle-info` (avisos informativos com destaque)
 * - `success` — verde, ícone `fa-circle-check`
 * - `warning` — âmbar, ícone `fa-triangle-exclamation`
 * - `pending` — âmbar mais sutil, ícone `fa-clock` (pra "aguardando processamento")
 * - `destructive` — vermelho, ícone `fa-circle-exclamation`
 *
 * Slots:
 * - default — body do notice (texto, lista, etc)
 * - title — substitui a prop title (pra HTML rico)
 * - icon — substitui o ícone padrão da variant
 *
 * Exemplo:
 *
 *     <ShadcnNotice variant="warning" title="Pagamento manual">
 *         Pix e Boleto geram um link novo de cobrança a cada ciclo.
 *     </ShadcnNotice>
 *
 *     <ShadcnNotice variant="pending" title="Aguardando ativação no Stripe" dismissible @dismiss="...">
 *         Clique em "Sincronizar" pra criar a assinatura no gateway.
 *     </ShadcnNotice>
 */

type NoticeVariant = 'info' | 'blue' | 'success' | 'warning' | 'pending' | 'destructive'

const VARIANT_DEFAULT_ICONS: Record<NoticeVariant, string> = {
    info: 'fa-solid fa-circle-info',
    blue: 'fa-solid fa-circle-info',
    success: 'fa-solid fa-circle-check',
    warning: 'fa-solid fa-triangle-exclamation',
    pending: 'fa-solid fa-clock',
    destructive: 'fa-solid fa-circle-exclamation',
}

export default {
    name: 'ShadcnNotice',

    emits: ['dismiss'],

    props: {
        variant: {
            type: String as PropType<NoticeVariant>,
            default: 'info',
            validator: (v: string) => ['info', 'blue', 'success', 'warning', 'pending', 'destructive'].includes(v),
        },
        title: {
            type: String,
            default: '',
        },
        /**
         * Override do ícone default da variant. Aceita classe FontAwesome (ex: `'fa-solid fa-rocket'`).
         */
        icon: {
            type: String,
            default: '',
        },
        showIcon: {
            type: Boolean,
            default: true,
        },
        /**
         * Mostra o botão "X" pra fechar (emite `dismiss`). Default false porque na maioria dos
         * lugares o notice é informativo permanente, não fechável.
         */
        dismissible: {
            type: Boolean,
            default: false,
        },
    },

    computed: {
        rootClasses(): string {
            return `shadcn-notice--${this.variant}`
        },

        resolvedIcon(): string {
            return this.icon || VARIANT_DEFAULT_ICONS[this.variant as NoticeVariant]
        },
    },
} as Component
</script>
