// src/angular/arcana-badge.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `ArcanaBadgeComponent` — Angular port do SFC Vue `ArcanaBadge`.
 *
 * Attribute selector num `<span>` (`<span arcanaBadge>`): emite
 * `span.arcana-badge` + `arcana-badge--${variant}` (+ `--sm`, `--clickable`) e o
 * `span.arcana-badge__dot` opcional, idêntico ao Vue/React. O `@click` cai no próprio host.
 *
 * Vue → Angular: props → `@Input()`; slot default → `<ng-content>`.
 */
export type ArcanaBadgeVariant = "neutral" | "blue" | "green" | "red" | "amber" | "violet";

@Component({
  selector: "span[arcanaBadge]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass"
  },
  template: `
    @if (dot) {
      <span class="arcana-badge__dot"></span>
    }
    <ng-content></ng-content>
  `
})
export class ArcanaBadgeComponent {
  @Input() variant: ArcanaBadgeVariant = "neutral";
  @Input() dot = false;
  @Input() size: "sm" | "md" = "md";
  @Input() clickable = false;
  @Input() className = "";

  get rootClass(): string {
    return [
      "arcana-badge",
      `arcana-badge--${this.variant}`,
      this.size === "sm" ? "arcana-badge--sm" : "",
      this.clickable ? "arcana-badge--clickable" : "",
      this.className
    ].filter(Boolean).join(" ");
  }
}

// src/react/ArcanaBadge.tsx
import type { MouseEvent, ReactNode } from "react";

/**
 * `<ArcanaBadge>` — React port. Pill/badge shadcn. Emite `span.arcana-badge` +
 * `arcana-badge--${variant}` (+ `--sm`, `--clickable`) e o `span.arcana-badge__dot`
 * opcional, idêntico ao SFC Vue.
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 * - `@click` no root → `onClick`
 */
export type ArcanaBadgeVariant = "neutral" | "blue" | "green" | "red" | "amber" | "violet";

export interface ArcanaBadgeProps {
    variant?: ArcanaBadgeVariant;
    dot?: boolean;
    size?: "sm" | "md";
    clickable?: boolean;
    onClick?: (ev: MouseEvent<HTMLSpanElement>) => void;
    className?: string;
    children?: ReactNode;
}

export function ArcanaBadge({
    variant = "neutral",
    dot = false,
    size = "md",
    clickable = false,
    onClick,
    className,
    children,
}: ArcanaBadgeProps) {
    const classes = [
        "arcana-badge",
        `arcana-badge--${variant}`,
        size === "sm" ? "arcana-badge--sm" : "",
        clickable ? "arcana-badge--clickable" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <span className={classes} onClick={onClick}>
            {dot ? <span className="arcana-badge__dot" /> : null}
            {children}
        </span>
    );
}
