// src/angular/arcana-edit-field-dialog.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output, ViewChild
} from "@angular/core";
import { ArcanaDialogComponent, type ArcanaDialogSize } from "./arcana-dialog.component";
import { ArcanaButtonComponent } from "./arcana-button.component";

/**
 * `ArcanaEditFieldDialogComponent` — Angular port do SFC Vue de edição de campo.
 *
 * Attribute selector (`<div arcanaEditFieldDialog>`): wrapper genérico pra modais de
 * "Alterar X". Recebe o input via `<ng-content>` e fornece o chrome (header + footer com
 * Cancelar/Salvar). Reusa o `ArcanaDialogComponent` já portado (portal pro body).
 *
 * Vue → Angular:
 * - API ref-based `show()`/`hide()` → métodos públicos (delegam ao `ArcanaDialog` interno).
 * - `emit('save')` → `@Output() save` (sem auto-close; caller fecha via `hide()` após validar).
 * - slot default → `<ng-content>`; footer com dois `ArcanaButton`, contexto `{ hide }`.
 */
@Component({
  selector: "div[arcanaEditFieldDialog]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ArcanaDialogComponent, ArcanaButtonComponent],
  template: `
    <div
      arcanaDialog
      #dialog
      [title]="title"
      [description]="description"
      [size]="size"
      [footerTemplate]="footerTpl"
    >
      <ng-content></ng-content>
    </div>

    <ng-template #footerTpl let-hide>
      <button
        arcanaButton
        variant="outline-danger"
        [className]="cancelClass"
        (click)="hide()"
      ><i class="fa-solid fa-xmark"></i> {{ cancelLabel }}</button>
      <button
        arcanaButton
        variant="success"
        [className]="saveClass"
        (click)="onSave()"
      ><i class="fa-solid fa-check"></i> {{ saveLabel }}</button>
    </ng-template>
  `
})
export class ArcanaEditFieldDialogComponent {
  @ViewChild("dialog") private dialog?: ArcanaDialogComponent;

  @Input({ required: true }) title!: string;
  @Input() description = "";
  @Input() cancelLabel = "Cancelar";
  @Input() saveLabel = "Salvar Alterações";
  @Input() cancelColor = "white";
  @Input() saveColor = "primary-700";
  @Input() cancelClass = "";
  @Input() saveClass = "";
  @Input() size: ArcanaDialogSize = "md";

  @Output() save = new EventEmitter<void>();

  show(): void {
    this.dialog?.show();
  }

  hide(): void {
    this.dialog?.hide();
  }

  onSave(): void {
    // Não fecha automaticamente — caller valida/chama API antes e fecha via hide().
    this.save.emit();
  }
}

// src/react/ArcanaEditFieldDialog.tsx
import {
    forwardRef,
    useImperativeHandle,
    useRef,
    type ReactNode,
} from "react";
import {
    ArcanaDialog,
    type ArcanaDialogHandle,
    type ArcanaDialogSize,
} from "./ArcanaDialog";
import { ArcanaButton } from "./ArcanaButton";

/**
 * `<ArcanaEditFieldDialog>` — React port do SFC Vue. Wrapper genérico pra modais de
 * "Alterar X": recebe o input via `children` e fornece o chrome (header/footer com
 * Cancelar/Salvar). Reusa o `<ArcanaDialog>` React já portado.
 *
 * Equivalências Vue → React:
 * - API ref-based (`show()`/`hide()`) → `forwardRef` + `useImperativeHandle` (delega
 *   ao ref do `<ArcanaDialog>` interno, igual ao SFC que chama `this.$refs.dialog`)
 * - `emit('save')` → `onSave` (sem auto-close; caller fecha via ref após validar)
 * - slot default → `children`
 * - footer com `<ArcanaButton>` (Cancelar/Salvar), idêntico ao SFC
 */
export interface ArcanaEditFieldDialogHandle {
    show: () => void;
    hide: () => void;
}

export interface ArcanaEditFieldDialogProps {
    title: string;
    description?: string;
    cancelLabel?: string;
    saveLabel?: string;
    cancelColor?: string;
    saveColor?: string;
    cancelClass?: string;
    saveClass?: string;
    size?: ArcanaDialogSize;
    children?: ReactNode;
    onSave?: () => void;
}

export const ArcanaEditFieldDialog = forwardRef<
    ArcanaEditFieldDialogHandle,
    ArcanaEditFieldDialogProps
>(function ArcanaEditFieldDialog(
    {
        title,
        description = "",
        cancelLabel = "Cancelar",
        saveLabel = "Salvar Alterações",
        cancelColor = "white",
        saveColor = "primary-700",
        cancelClass = "",
        saveClass = "",
        size = "md",
        children,
        onSave,
    },
    ref
) {
    const dialogRef = useRef<ArcanaDialogHandle | null>(null);

    useImperativeHandle(
        ref,
        () => ({
            show: () => dialogRef.current?.show(),
            hide: () => dialogRef.current?.hide(),
        }),
        []
    );

    return (
        <ArcanaDialog
            ref={dialogRef}
            title={title}
            description={description}
            size={size}
            footer={(hide) => (
                <>
                    <ArcanaButton
                        variant="outline-danger"
                        className={cancelClass}
                        onClick={hide}
                    >
                        <><i className="fa-solid fa-xmark" /> {cancelLabel}</>
                    </ArcanaButton>
                    <ArcanaButton
                        variant="success"
                        className={saveClass}
                        onClick={() => onSave?.()}
                    >
                        <><i className="fa-solid fa-check" /> {saveLabel}</>
                    </ArcanaButton>
                </>
            )}
        >
            {children}
        </ArcanaDialog>
    );
});
