// src/svelte/ArcanaNotice.svelte
<script lang="ts" module>
  export type NoticeVariant =
    | "info" | "blue" | "success" | "warning" | "pending" | "destructive";

  const VARIANT_DEFAULT_ICONS: Record<NoticeVariant, string> = {
    info: "fa-solid fa-circle-info",
    blue: "fa-solid fa-circle-info",
    success: "fa-solid fa-circle-check",
    warning: "fa-solid fa-triangle-exclamation",
    pending: "fa-solid fa-clock",
    destructive: "fa-solid fa-circle-exclamation",
  };
</script>

<script lang="ts">
  import type { Snippet } from "svelte";

  /**
   * `<ArcanaNotice>` — Svelte 5 port. Banner informativo com variants semânticas. Reproduz
   * `<div class="arcana-notice arcana-notice--${variant}">` com `__icon`/`__content`/
   * `__title`/`__body` e o botão `__close` opcional, idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - slot default → snippet `children`; slots `#title`/`#icon` → props `title`/`iconNode`
   * - `emit('dismiss')` → `onDismiss`
   */
  let {
    variant = "info",
    title = "",
    icon = "",
    iconNode,
    showIcon = true,
    dismissible = false,
    onDismiss,
    class: className = "",
    children,
  }: {
    variant?: NoticeVariant;
    title?: string | Snippet;
    icon?: string;
    iconNode?: Snippet;
    showIcon?: boolean;
    dismissible?: boolean;
    onDismiss?: () => void;
    class?: string;
    children?: Snippet;
  } = $props();

  const resolvedIcon = $derived(icon || VARIANT_DEFAULT_ICONS[variant]);
  const rootClasses = $derived(
    ["arcana-notice", `arcana-notice--${variant}`, className].filter(Boolean).join(" ")
  );
</script>

<div class={rootClasses} role="status">
  {#if showIcon}
    <span class="arcana-notice__icon" aria-hidden="true">
      {#if iconNode}{@render iconNode()}{:else}<i class={resolvedIcon}></i>{/if}
    </span>
  {/if}

  <div class="arcana-notice__content">
    {#if title}
      <strong class="arcana-notice__title">
        {#if typeof title === "function"}{@render title()}{:else}{title}{/if}
      </strong>
    {/if}
    <div class="arcana-notice__body">{@render children?.()}</div>
  </div>

  {#if dismissible}
    <button type="button" class="arcana-notice__close" aria-label="Fechar" onclick={() => onDismiss?.()}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
        <line x1="18" y1="6" x2="6" y2="18" />
        <line x1="6" y1="6" x2="18" y2="18" />
      </svg>
    </button>
  {/if}
</div>

// src/react/ArcanaNotice.tsx
import type { ReactNode } from "react";

/**
 * `<ArcanaNotice>` — React port. Banner informativo com variants semânticas. Reproduz
 * `<div class="arcana-notice arcana-notice--${variant}">` com `__icon`/`__content`/
 * `__title`/`__body` e o botão `__close` opcional, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - slot default → `children`; slots `#title`/`#icon` → props `title`/`iconNode`
 * - `emit('dismiss')` → `onDismiss`
 */
export type NoticeVariant =
    | "info"
    | "blue"
    | "success"
    | "warning"
    | "pending"
    | "destructive";

const VARIANT_DEFAULT_ICONS: Record<NoticeVariant, string> = {
    info: "fa-solid fa-circle-info",
    blue: "fa-solid fa-circle-info",
    success: "fa-solid fa-circle-check",
    warning: "fa-solid fa-triangle-exclamation",
    pending: "fa-solid fa-clock",
    destructive: "fa-solid fa-circle-exclamation",
};

export interface ArcanaNoticeProps {
    variant?: NoticeVariant;
    title?: ReactNode;
    icon?: string;
    iconNode?: ReactNode;
    showIcon?: boolean;
    dismissible?: boolean;
    onDismiss?: () => void;
    className?: string;
    children?: ReactNode;
}

export function ArcanaNotice({
    variant = "info",
    title = "",
    icon = "",
    iconNode,
    showIcon = true,
    dismissible = false,
    onDismiss,
    className,
    children,
}: ArcanaNoticeProps) {
    const resolvedIcon = icon || VARIANT_DEFAULT_ICONS[variant];

    const rootClasses = [
        "arcana-notice",
        `arcana-notice--${variant}`,
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <div className={rootClasses} role="status">
            {showIcon ? (
                <span className="arcana-notice__icon" aria-hidden="true">
                    {iconNode ?? <i className={resolvedIcon} />}
                </span>
            ) : null}

            <div className="arcana-notice__content">
                {title ? (
                    <strong className="arcana-notice__title">{title}</strong>
                ) : null}
                <div className="arcana-notice__body">{children}</div>
            </div>

            {dismissible ? (
                <button
                    type="button"
                    className="arcana-notice__close"
                    aria-label="Fechar"
                    onClick={() => onDismiss?.()}
                >
                    <svg
                        width="14"
                        height="14"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        aria-hidden="true"
                    >
                        <line x1="18" y1="6" x2="6" y2="18" />
                        <line x1="6" y1="6" x2="18" y2="18" />
                    </svg>
                </button>
            ) : null}
        </div>
    );
}
