// src/angular/arcana-switch.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ArcanaSwitchComponent` — Angular port do SFC Vue `ArcanaSwitch`.
 *
 * Attribute selector num `<button>` (`<button arcanaSwitch>`): `role="switch"`,
 * `span.arcana-switch__thumb` e o `<input class="arcana-switch__hidden-input">` opcional
 * (quando `name`), idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 */
@Component({
  selector: "button[arcanaSwitch]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "type": "button",
    "role": "switch",
    "[class]": "rootClass",
    "[attr.aria-checked]": "isChecked",
    "[attr.aria-label]": "ariaLabel || null",
    "[disabled]": "disabled",
    "(click)": "toggle()",
    "(keydown)": "onKeydown($event)"
  },
  template: `
    <span class="arcana-switch__thumb" aria-hidden="true"></span>

    @if (name) {
      <input
        type="checkbox"
        class="arcana-switch__hidden-input"
        [attr.name]="name"
        [checked]="isChecked"
        [disabled]="disabled"
        tabindex="-1"
        aria-hidden="true"
        (change)="$event.stopPropagation()"
      />
    }
  `
})
export class ArcanaSwitchComponent {
  @Input() value = false;
  @Input() disabled = false;
  @Input() size: "sm" | "md" | "lg" = "md";
  @Input() name = "";
  @Input() ariaLabel = "";

  @Output() valueChange = new EventEmitter<boolean>();
  @Output() change = new EventEmitter<boolean>();

  get isChecked(): boolean {
    return Boolean(this.value);
  }

  get rootClass(): string {
    return [
      "arcana-switch",
      `arcana-switch--${this.size}`,
      this.isChecked ? "is-checked" : "",
      this.disabled ? "is-disabled" : ""
    ].filter(Boolean).join(" ");
  }

  toggle(): void {
    if (this.disabled) return;
    const next = !this.isChecked;
    this.valueChange.emit(next);
    this.change.emit(next);
  }

  onKeydown(e: KeyboardEvent): void {
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      this.toggle();
    }
  }
}

// src/react/ArcanaSwitch.tsx
import type { KeyboardEvent } from "react";

/**
 * `<ArcanaSwitch>` — React port. Reproduz o `<button role="switch" class="arcana-switch">`
 * (+ `arcana-switch--${size}`, `is-checked`, `is-disabled`), o `span.arcana-switch__thumb`
 * e o `<input class="arcana-switch__hidden-input">` opcional (quando `name`), idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` (controlado) + `onValueChange`
 * - `emit('change')` → `onChange`
 */
export interface ArcanaSwitchProps {
    value?: boolean;
    disabled?: boolean;
    size?: "sm" | "md" | "lg";
    name?: string;
    ariaLabel?: string;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    className?: string;
    /** Reproduz `tabindex`/`aria-hidden` que o ArcanaSwitchRow passa ao switch interno. */
    tabIndex?: number;
    "aria-hidden"?: boolean;
}

export function ArcanaSwitch({
    value = false,
    disabled = false,
    size = "md",
    name = "",
    ariaLabel = "",
    onValueChange,
    onChange,
    className,
    tabIndex,
    "aria-hidden": ariaHidden,
}: ArcanaSwitchProps) {
    const isChecked = Boolean(value);

    const rootClasses = [
        "arcana-switch",
        `arcana-switch--${size}`,
        isChecked ? "is-checked" : "",
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const toggle = () => {
        if (disabled) return;
        const next = !isChecked;
        onValueChange?.(next);
        onChange?.(next);
    };

    const onKeydown = (e: KeyboardEvent<HTMLButtonElement>) => {
        if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            toggle();
        }
    };

    return (
        <button
            type="button"
            role="switch"
            className={rootClasses}
            aria-checked={isChecked}
            aria-label={ariaLabel || undefined}
            aria-hidden={ariaHidden}
            disabled={disabled}
            tabIndex={tabIndex}
            onClick={toggle}
            onKeyDown={onKeydown}
        >
            <span className="arcana-switch__thumb" aria-hidden="true" />

            {name ? (
                <input
                    type="checkbox"
                    className="arcana-switch__hidden-input"
                    name={name}
                    checked={isChecked}
                    disabled={disabled}
                    tabIndex={-1}
                    aria-hidden="true"
                    readOnly
                    onClick={(e) => e.stopPropagation()}
                />
            ) : null}
        </button>
    );
}
