// src/angular/labeled-button.component.ts
import { ChangeDetectionStrategy, Component, Input } from "@angular/core";

/**
 * `LabeledButtonComponent` — Angular port do SFC Vue `LabeledButton`.
 *
 * Attribute selector num `<button>` (`<button arcanaLabeledButton label="…">`). Reproduz o
 * mapping de `color` legado → variant shadcn e os dois modos de render (shadcn vs. legado
 * Bootstrap `btn bg-{color} btn-labeled`), com as MESMAS classes/markup do Vue/React.
 *
 * Vue → Angular:
 * - props → `@Input()`; `emit('click', ev)` → binde o `(click)` DOM direto no host `<button>`
 *   (o host já preventDefault o clique nativo, como o `@click.prevent` do SFC)
 * - `class` extra do caller → `@Input() className` (mesclado nas classes do botão)
 * - `v-bind="forwardedAttrs"` (attrs arbitrários) NÃO é reproduzido nesta fase — passe os
 *   atributos nativos direto no elemento `<button>` já que ele é o próprio host.
 */
function shadcnVariantFrom(color: string): string {
  const c = String(color ?? "").toLowerCase();
  const isDanger = c.startsWith("danger") || c.startsWith("error") || c.startsWith("red");
  if (isDanger && c.includes("outline")) return "destructive-outline";
  if (isDanger) return "destructive";
  if (c === "white" || c.startsWith("grey") || c.startsWith("gray") || c.startsWith("slate")) return "ghost";
  if (c.startsWith("teal")) return "teal";
  if (c.startsWith("success") || c.startsWith("green") || c.startsWith("emerald")) return "success";
  if (c.startsWith("blue") || c.startsWith("sky") || c.startsWith("azure")) return "info";
  if (c.startsWith("amber") || c.startsWith("orange") || c.startsWith("yellow")) return "warning";
  if (c.startsWith("indigo") || c.startsWith("violet") || c.startsWith("purple")) return "alert";
  return "primary";
}

@Component({
  selector: "button[arcanaLabeledButton]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "type": "button",
    "[class]": "rootClass",
    "[disabled]": "disabled || loading",
    "(click)": "onClick($event)"
  },
  template: `
    @if (shadcn) {
      @if (loading) {
        <i class="fa-solid fa-spinner fa-spin shadcn-btn__icon"></i>
      } @else if (icon) {
        <i [class]="icon + ' shadcn-btn__icon'"></i>
      }
      <span>{{ label }}</span>
    } @else {
      <b><i [class]="loading ? 'fa-solid fa-spinner fa-spin' : icon" style="font-size: 15px;"></i></b>
      {{ label }}
    }
  `
})
export class LabeledButtonComponent {
  @Input() icon = "";
  @Input() color = "info-700";
  @Input() disabled = false;
  @Input() label = "";
  @Input() shadcn = false;
  @Input() loading = false;
  @Input() centerLabel = false;
  @Input() centerContent = false;
  @Input() className = "";

  get rootClass(): string {
    const list: string[] = [];
    if (this.shadcn) {
      list.push("shadcn-btn", `shadcn-btn--${shadcnVariantFrom(this.color)}`);
      if (this.centerLabel) list.push("shadcn-btn--center-label");
      else if (this.centerContent) list.push("shadcn-btn--center-content");
    } else {
      list.push("btn", `bg-${this.color}`, "btn-labeled");
    }
    if (this.className) list.push(this.className);
    return list.join(" ");
  }

  onClick(ev: MouseEvent): void {
    ev.preventDefault();
  }
}

// src/react/LabeledButton.tsx
import type { ButtonHTMLAttributes, MouseEvent } from "react";

/**
 * `<LabeledButton>` — React port do SFC Vue. Reproduz o mesmo markup/classes do
 * componente base (shadcn `shadcn-btn shadcn-btn--${variant}` OU legado
 * `btn bg-{color} btn-labeled`), incluindo o mapping de `color` legado → variant
 * semântica shadcn.
 *
 * Equivalências Vue → React:
 * - `v-bind="forwardedAttrs"` (attrs não-class) → `...rest` (props HTML nativas)
 * - `emit('click', $event)` → `onClick`
 * - `class` extra do caller → `className`
 */
export interface LabeledButtonProps
    extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "type" | "onClick" | "color"> {
    icon?: string;
    color?: string;
    disabled?: boolean;
    label: string;
    shadcn?: boolean;
    loading?: boolean;
    centerLabel?: boolean;
    centerContent?: boolean;
    onClick?: (ev: MouseEvent<HTMLButtonElement>) => void;
    className?: string;
}

function shadcnVariantFrom(color: string): string {
    const c = String(color ?? "").toLowerCase();
    const isDanger = c.startsWith("danger") || c.startsWith("error") || c.startsWith("red");
    if (isDanger && c.includes("outline")) return "destructive-outline";
    if (isDanger) return "destructive";
    if (c === "white" || c.startsWith("grey") || c.startsWith("gray") || c.startsWith("slate")) return "ghost";
    if (c.startsWith("teal")) return "teal";
    if (c.startsWith("success") || c.startsWith("green") || c.startsWith("emerald")) return "success";
    if (c.startsWith("blue") || c.startsWith("sky") || c.startsWith("azure")) return "info";
    if (c.startsWith("amber") || c.startsWith("orange") || c.startsWith("yellow")) return "warning";
    if (c.startsWith("indigo") || c.startsWith("violet") || c.startsWith("purple")) return "alert";
    return "primary";
}

export function LabeledButton({
    icon = "",
    color = "info-700",
    disabled = false,
    label,
    shadcn = false,
    loading = false,
    centerLabel = false,
    centerContent = false,
    onClick,
    className,
    ...rest
}: LabeledButtonProps) {
    const list: string[] = [];

    if (shadcn) {
        list.push("shadcn-btn", `shadcn-btn--${shadcnVariantFrom(color)}`);
        if (centerLabel) list.push("shadcn-btn--center-label");
        else if (centerContent) list.push("shadcn-btn--center-content");
    } else {
        list.push("btn", `bg-${color}`, "btn-labeled");
    }

    if (className && typeof className === "string") list.push(className);

    const classes = list.join(" ");

    return (
        <button
            {...rest}
            type="button"
            disabled={Boolean(disabled) || Boolean(loading)}
            className={classes}
            onClick={(ev) => {
                ev.preventDefault();
                onClick?.(ev);
            }}
        >
            {shadcn ? (
                <>
                    {loading ? (
                        <i className="fa-solid fa-spinner fa-spin shadcn-btn__icon" />
                    ) : icon ? (
                        <i className={`${icon} shadcn-btn__icon`} />
                    ) : null}
                    <span>{label}</span>
                </>
            ) : (
                <>
                    <b>
                        <i
                            className={loading ? "fa-solid fa-spinner fa-spin" : icon}
                            style={{ fontSize: "15px" }}
                        />
                    </b>
                    {" "}
                    {label}
                </>
            )}
        </button>
    );
}
