// src/svelte/ShadcnSwitchRow.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import ShadcnSwitch from "./ShadcnSwitch.svelte";

  /**
   * `<ShadcnSwitchRow>` — Svelte 5 port. Toggle full-width "linha de configuração".
   * Reproduz o `<button class="shadcn-switch-row">` (+ `is-on`, `is-disabled`), os textos
   * (`__text`/`__title`/`__sub`) e o `<ShadcnSwitch class="shadcn-switch-row__switch">`
   * interno (aria-hidden, sem click próprio), idêntico ao SFC.
   *
   * Equivalências Vue → Svelte 5:
   * - `modelValue` (v-model) → prop `value` + `onValueChange`; `emit('change')` → `onChange`
   * - slots `#label`/`#description` → props `label`/`description` (`string | Snippet`)
   */
  let {
    value = false,
    label = "",
    description,
    disabled = false,
    ariaLabel = "",
    onValueChange,
    onChange,
    class: className = "",
  }: {
    value?: boolean;
    label?: string | Snippet;
    description?: string | Snippet;
    disabled?: boolean;
    ariaLabel?: string;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    class?: string;
  } = $props();

  const hasDescription = $derived(Boolean(description));

  const rootClasses = $derived(
    ["shadcn-switch-row", value ? "is-on" : "", disabled ? "is-disabled" : "", className]
      .filter(Boolean)
      .join(" ")
  );

  const ariaLabelText = $derived(
    ariaLabel || (typeof label === "string" ? label : "") || undefined
  );

  function toggle() {
    if (disabled) return;
    const next = !value;
    onValueChange?.(next);
    onChange?.(next);
  }

  function onKeydown(e: KeyboardEvent) {
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      toggle();
    }
  }
</script>

<button
  type="button"
  class={rootClasses}
  role="switch"
  aria-checked={Boolean(value)}
  aria-label={ariaLabelText}
  {disabled}
  onclick={toggle}
  onkeydown={onKeydown}
>
  <div class="shadcn-switch-row__text">
    <div class="shadcn-switch-row__title">
      {#if typeof label === "function"}{@render label()}{:else}{label}{/if}
    </div>
    {#if hasDescription}
      <div class="shadcn-switch-row__sub">
        {#if typeof description === "function"}{@render description()}{:else}{description}{/if}
      </div>
    {/if}
  </div>

  <ShadcnSwitch
    class="shadcn-switch-row__switch"
    value={Boolean(value)}
    {disabled}
    tabindex={-1}
    aria-hidden={true}
  />
</button>

// src/react/ShadcnSwitchRow.tsx
import type { KeyboardEvent, ReactNode } from "react";
import { ShadcnSwitch } from "./ShadcnSwitch";

/**
 * `<ShadcnSwitchRow>` — React port. Toggle full-width "linha de configuração".
 * Reproduz o `<button class="shadcn-switch-row">` (+ `is-on`, `is-disabled`), os textos
 * (`__text`/`__title`/`__sub`) e o `<ShadcnSwitch class="shadcn-switch-row__switch">`
 * interno (aria-hidden, sem click próprio), idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` + `onValueChange`; `emit('change')` → `onChange`
 * - slots `#label`/`#description` → props `label`/`description` (ReactNode)
 */
export interface ShadcnSwitchRowProps {
    value?: boolean;
    label?: ReactNode;
    description?: ReactNode;
    disabled?: boolean;
    ariaLabel?: string;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    className?: string;
}

export function ShadcnSwitchRow({
    value = false,
    label = "",
    description,
    disabled = false,
    ariaLabel = "",
    onValueChange,
    onChange,
    className,
}: ShadcnSwitchRowProps) {
    const hasDescription = Boolean(description);

    const rootClasses = [
        "shadcn-switch-row",
        value ? "is-on" : "",
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const toggle = () => {
        if (disabled) return;
        const next = !value;
        onValueChange?.(next);
        onChange?.(next);
    };

    const onKeydown = (e: KeyboardEvent<HTMLButtonElement>) => {
        if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            toggle();
        }
    };

    const ariaLabelText =
        ariaLabel || (typeof label === "string" ? label : "") || undefined;

    return (
        <button
            type="button"
            className={rootClasses}
            role="switch"
            aria-checked={Boolean(value)}
            aria-label={ariaLabelText}
            disabled={disabled}
            onClick={toggle}
            onKeyDown={onKeydown}
        >
            <div className="shadcn-switch-row__text">
                <div className="shadcn-switch-row__title">{label}</div>
                {hasDescription ? (
                    <div className="shadcn-switch-row__sub">{description}</div>
                ) : null}
            </div>

            <ShadcnSwitch
                className="shadcn-switch-row__switch"
                value={Boolean(value)}
                disabled={disabled}
                tabIndex={-1}
                aria-hidden={true}
            />
        </button>
    );
}
