// src/angular/shadcn-switch-segmented.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ShadcnSwitchSegmentedComponent` — Angular port do SFC Vue `ShadcnSwitchSegmented`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnSwitchSegmented>`): reproduz
 * `.shadcn-switch-segmented` (+ `is-on`/`is-disabled`/`is-compact`/`is-squared`),
 * o `__indicator` e as duas metades `__option--off`/`__option--on` (com `__radio`
 * opcional), idêntico ao Vue/React. Preserva o inline `--seg-active`.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 * - slots `#off-label`/`#on-label` → conteúdo projetado `[segOff]`/`[segOn]` (fallback: offLabel/onLabel)
 */
@Component({
  selector: "div[arcanaShadcnSwitchSegmented]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.--seg-active]": "activeColor || null",
    "role": "switch",
    "[attr.aria-checked]": "!!value",
    "[attr.aria-label]": "ariaLabel || ariaLabelFallback || null",
    "[attr.aria-disabled]": "disabled",
    "[attr.tabindex]": "disabled ? -1 : 0",
    "(click)": "toggle()",
    "(keydown)": "onKeydown($event)"
  },
  template: `
    <div class="shadcn-switch-segmented__indicator" aria-hidden="true"></div>

    <div class="shadcn-switch-segmented__option shadcn-switch-segmented__option--off">
      @if (radio) {
        <span class="shadcn-switch-segmented__radio" aria-hidden="true"></span>
      }
      <ng-content select="[segOff]">{{ offLabel }}</ng-content>
    </div>
    <div class="shadcn-switch-segmented__option shadcn-switch-segmented__option--on">
      @if (radio) {
        <span class="shadcn-switch-segmented__radio" aria-hidden="true"></span>
      }
      <ng-content select="[segOn]">{{ onLabel }}</ng-content>
    </div>
  `
})
export class ShadcnSwitchSegmentedComponent {
  @Input() value = false;
  @Input() offLabel = "Inativo";
  @Input() onLabel = "Ativo";
  @Input() disabled = false;
  @Input() ariaLabel = "";
  @Input() compact = false;
  @Input() squared = false;
  @Input() activeColor = "";
  @Input() radio = false;

  @Output() valueChange = new EventEmitter<boolean>();
  @Output() change = new EventEmitter<boolean>();

  get ariaLabelFallback(): string {
    return `${this.offLabel} ou ${this.onLabel}`;
  }

  get rootClass(): string {
    return [
      "shadcn-switch-segmented",
      this.value ? "is-on" : "",
      this.disabled ? "is-disabled" : "",
      this.compact ? "is-compact" : "",
      this.squared ? "is-squared" : ""
    ].filter(Boolean).join(" ");
  }

  toggle(): void {
    if (this.disabled) return;
    const next = !this.value;
    this.valueChange.emit(next);
    this.change.emit(next);
  }

  onKeydown(e: KeyboardEvent): void {
    if (this.disabled) return;
    if (e.key === " " || e.key === "Enter") {
      e.preventDefault();
      this.toggle();
      return;
    }
    if (e.key === "ArrowLeft" && this.value) {
      e.preventDefault();
      this.toggle();
    }
    if (e.key === "ArrowRight" && !this.value) {
      e.preventDefault();
      this.toggle();
    }
  }
}

// src/react/ShadcnSwitchSegmented.tsx
import type { CSSProperties, KeyboardEvent, ReactNode } from "react";

/**
 * `<ShadcnSwitchSegmented>` — React port. Reproduz `<div class="shadcn-switch-segmented">`
 * (+ `is-on`/`is-disabled`/`is-compact`/`is-squared`), o `__indicator` e as duas metades
 * `__option--off`/`__option--on` (com `__radio` opcional), idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` + `onValueChange`; `emit('change')` → `onChange`
 * - slots `#off-label`/`#on-label` → props `offSlot`/`onSlot` (ReactNode)
 */
export interface ShadcnSwitchSegmentedProps {
    value?: boolean;
    offLabel?: string;
    onLabel?: string;
    disabled?: boolean;
    ariaLabel?: string;
    compact?: boolean;
    squared?: boolean;
    activeColor?: string;
    radio?: boolean;
    offSlot?: ReactNode;
    onSlot?: ReactNode;
    onValueChange?: (value: boolean) => void;
    onChange?: (value: boolean) => void;
    className?: string;
}

export function ShadcnSwitchSegmented({
    value = false,
    offLabel = "Inativo",
    onLabel = "Ativo",
    disabled = false,
    ariaLabel = "",
    compact = false,
    squared = false,
    activeColor = "",
    radio = false,
    offSlot,
    onSlot,
    onValueChange,
    onChange,
    className,
}: ShadcnSwitchSegmentedProps) {
    const ariaLabelFallback = `${offLabel} ou ${onLabel}`;

    const toggle = () => {
        if (disabled) return;
        const next = !value;
        onValueChange?.(next);
        onChange?.(next);
    };

    const onKeydown = (e: KeyboardEvent<HTMLDivElement>) => {
        if (disabled) return;
        if (e.key === " " || e.key === "Enter") {
            e.preventDefault();
            toggle();
            return;
        }
        if (e.key === "ArrowLeft" && value) {
            e.preventDefault();
            toggle();
        }
        if (e.key === "ArrowRight" && !value) {
            e.preventDefault();
            toggle();
        }
    };

    const rootClasses = [
        "shadcn-switch-segmented",
        value ? "is-on" : "",
        disabled ? "is-disabled" : "",
        compact ? "is-compact" : "",
        squared ? "is-squared" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const rootStyle = activeColor
        ? ({ "--seg-active": activeColor } as CSSProperties)
        : undefined;

    return (
        <div
            className={rootClasses}
            style={rootStyle}
            role="switch"
            aria-checked={Boolean(value)}
            aria-label={ariaLabel || ariaLabelFallback || undefined}
            aria-disabled={disabled}
            tabIndex={disabled ? -1 : 0}
            onClick={toggle}
            onKeyDown={onKeydown}
        >
            <div className="shadcn-switch-segmented__indicator" aria-hidden="true" />

            <div className="shadcn-switch-segmented__option shadcn-switch-segmented__option--off">
                {radio ? (
                    <span
                        className="shadcn-switch-segmented__radio"
                        aria-hidden="true"
                    />
                ) : null}
                {offSlot ?? offLabel}
            </div>
            <div className="shadcn-switch-segmented__option shadcn-switch-segmented__option--on">
                {radio ? (
                    <span
                        className="shadcn-switch-segmented__radio"
                        aria-hidden="true"
                    />
                ) : null}
                {onSlot ?? onLabel}
            </div>
        </div>
    );
}
