// src/svelte/ShadcnButton.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  /**
   * `<ShadcnButton>` — Svelte 5 port do SFC Vue. Emite o MESMO markup/classes
   * (`shadcn-button`, `shadcn-button--${variant}`, `is-disabled`), reusando o CSS
   * compartilhado (`@arcanalabs/ui-components/styles.css`).
   *
   * Equivalências Vue → Svelte 5 (runes):
   * - slot default → snippet `children`
   * - `emit('click', ev)` → callback prop `onClick(ev)`
   */
  type Variant =
    | "primary" | "outline" | "outline-danger" | "ghost" | "danger" | "destructive"
    | "destructive-outline" | "success" | "secondary" | "dark" | "indigo" | "alert"
    | "info" | "warning" | "teal";

  let {
    variant = "primary",
    type = "button",
    disabled = false,
    onClick,
    class: className = "",
    children,
  }: {
    variant?: Variant;
    type?: "button" | "submit";
    disabled?: boolean;
    onClick?: (ev: MouseEvent) => void;
    class?: string;
    children?: Snippet;
  } = $props();

  const classes = $derived(
    ["shadcn-button", `shadcn-button--${variant}`, disabled ? "is-disabled" : "", className]
      .filter(Boolean)
      .join(" ")
  );
</script>

<button {type} class={classes} {disabled} onclick={(ev) => onClick?.(ev)}>
  {@render children?.()}
</button>

// src/react/ShadcnButton.tsx
import type { MouseEvent, ReactNode } from "react";

/**
 * `<ShadcnButton>` — React port do SFC Vue de mesmo nome. Emite o MESMO markup e as
 * MESMAS classes (`shadcn-button`, `shadcn-button--${variant}`, `is-disabled`) pra
 * reusar o CSS compartilhado (`@arcanalabs/ui-components/styles.css`).
 *
 * Equivalências Vue → React:
 * - slot default → `children`
 * - `emit('click', ev)` → `onClick(ev)`
 */
export type ShadcnButtonVariant =
    | "primary"
    | "outline"
    | "outline-danger"
    | "ghost"
    | "danger"
    | "destructive"
    | "destructive-outline"
    | "success"
    | "secondary"
    | "dark"
    | "indigo"
    | "alert"
    | "info"
    | "warning"
    | "teal";

export interface ShadcnButtonProps {
    variant?: ShadcnButtonVariant;
    type?: "button" | "submit";
    disabled?: boolean;
    onClick?: (ev: MouseEvent<HTMLButtonElement>) => void;
    className?: string;
    children?: ReactNode;
}

export function ShadcnButton({
    variant = "primary",
    type = "button",
    disabled = false,
    onClick,
    className,
    children,
}: ShadcnButtonProps) {
    const classes = [
        "shadcn-button",
        `shadcn-button--${variant}`,
        disabled ? "is-disabled" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    return (
        <button
            type={type}
            className={classes}
            disabled={disabled}
            onClick={(ev) => onClick?.(ev)}
        >
            {children}
        </button>
    );
}
