// src/angular/shadcn-radio-card-group.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, Output
} from "@angular/core";

/**
 * `ShadcnRadioCardGroupComponent` — Angular port do SFC Vue `ShadcnRadioCardGroup`.
 *
 * Attribute selector num `<div>` (`<div arcanaShadcnRadioCardGroup>`): reproduz
 * `.shadcn-radio-card-group` (+ `--inline`/`--grid`/`--radio-end`), cada
 * `<label class="shadcn-radio-card">` (+ `is-selected`/`is-disabled`), o `__input` nativo,
 * `__radio`/`__dot`, `__icon`, `__content`/`__label`/`__desc` e `__badge`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `modelValue` (v-model) → `value` + `@Output() valueChange`; `emit('change')` → `@Output() change`
 */
export interface RadioCardOption {
  label: string;
  value: string | number | boolean | null;
  description?: string;
  icon?: string;
  badge?: string;
  disabled?: boolean;
  iconBg?: string;
  iconColor?: string;
  iconBorder?: string;
}

let uidCounter = 0;

@Component({
  selector: "div[arcanaShadcnRadioCardGroup]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "[class]": "rootClass",
    "[style.gridTemplateColumns]": "gridTemplateColumns",
    "role": "radiogroup",
    "[attr.aria-label]": "ariaLabel || null"
  },
  template: `
    @for (opt of normalizedOptions; track $index) {
      <label
        class="shadcn-radio-card"
        [class.is-selected]="isSelected(opt)"
        [class.is-disabled]="isOptionDisabled(opt)"
      >
        <input
          type="radio"
          class="shadcn-radio-card__input"
          [name]="groupName"
          [value]="opt.value"
          [checked]="isSelected(opt)"
          [disabled]="isOptionDisabled(opt)"
          (change)="handleChange(opt)"
        />

        <span class="shadcn-radio-card__radio" aria-hidden="true">
          <span class="shadcn-radio-card__dot"></span>
        </span>

        @if (opt.icon) {
          <span
            class="shadcn-radio-card__icon"
            [style.background]="opt.iconBg || null"
            [style.color]="opt.iconColor || null"
            [style.border]="opt.iconBorder ? '1px solid ' + opt.iconBorder : null"
            aria-hidden="true"
          >
            <i [class]="opt.icon"></i>
          </span>
        }

        <span class="shadcn-radio-card__content">
          <span class="shadcn-radio-card__label">{{ opt.label }}</span>
          @if (opt.description) {
            <span class="shadcn-radio-card__desc">{{ opt.description }}</span>
          }
        </span>

        @if (opt.badge) {
          <span class="shadcn-radio-card__badge">{{ opt.badge }}</span>
        }
      </label>
    }
  `
})
export class ShadcnRadioCardGroupComponent {
  private readonly uid = ++uidCounter;

  @Input() value: string | number | boolean | null = null;
  @Input() options: RadioCardOption[] = [];
  @Input() name = "";
  @Input() ariaLabel = "";
  @Input() disabled = false;
  @Input() inline = false;
  @Input() columns = 0;
  @Input() radioPosition: "start" | "end" = "start";
  @Input() className = "";

  @Output() valueChange = new EventEmitter<string | number | boolean | null>();
  @Output() change = new EventEmitter<string | number | boolean | null>();

  get groupName(): string {
    return this.name || `shadcn-radio-card-group-${this.uid}`;
  }

  get normalizedOptions(): RadioCardOption[] {
    return this.options ?? [];
  }

  get gridTemplateColumns(): string | null {
    return this.columns > 0 ? `repeat(${this.columns}, minmax(0, 1fr))` : null;
  }

  get rootClass(): string {
    return [
      "shadcn-radio-card-group",
      this.inline && !this.columns ? "shadcn-radio-card-group--inline" : "",
      this.columns > 0 ? "shadcn-radio-card-group--grid" : "",
      this.radioPosition === "end" ? "shadcn-radio-card-group--radio-end" : "",
      this.className
    ].filter(Boolean).join(" ");
  }

  isSelected(opt: RadioCardOption): boolean {
    return opt.value === this.value;
  }

  isOptionDisabled(opt: RadioCardOption): boolean {
    return Boolean(this.disabled || opt.disabled);
  }

  handleChange(opt: RadioCardOption): void {
    if (this.isOptionDisabled(opt)) return;
    this.valueChange.emit(opt.value);
    this.change.emit(opt.value);
  }
}

// src/react/ShadcnRadioCardGroup.tsx
import { useMemo, useRef, type CSSProperties } from "react";

/**
 * `<ShadcnRadioCardGroup>` — React port. Reproduz `<div class="shadcn-radio-card-group">`
 * (+ `--inline`/`--grid`/`--radio-end`), cada `<label class="shadcn-radio-card">`
 * (+ `is-selected`/`is-disabled`), o `__input` nativo, `__radio`/`__dot`, `__icon`,
 * `__content`/`__label`/`__desc` e `__badge`, idêntico ao SFC.
 *
 * Equivalências Vue → React:
 * - `modelValue` (v-model) → `value` + `onValueChange`; `emit('change')` → `onChange`
 */
export interface RadioCardOption {
    label: string;
    value: string | number | boolean | null;
    description?: string;
    icon?: string;
    badge?: string;
    disabled?: boolean;
    iconBg?: string;
    iconColor?: string;
    iconBorder?: string;
}

export interface ShadcnRadioCardGroupProps {
    value?: string | number | boolean | null;
    options: RadioCardOption[];
    name?: string;
    ariaLabel?: string;
    disabled?: boolean;
    inline?: boolean;
    columns?: number;
    radioPosition?: "start" | "end";
    onValueChange?: (value: string | number | boolean | null) => void;
    onChange?: (value: string | number | boolean | null) => void;
    className?: string;
}

let uidCounter = 0;

export function ShadcnRadioCardGroup({
    value = null,
    options,
    name = "",
    ariaLabel = "",
    disabled = false,
    inline = false,
    columns = 0,
    radioPosition = "start",
    onValueChange,
    onChange,
    className,
}: ShadcnRadioCardGroupProps) {
    const uid = useRef(++uidCounter);
    const groupName = name || `shadcn-radio-card-group-${uid.current}`;
    const normalizedOptions = useMemo(() => options ?? [], [options]);

    const isSelected = (opt: RadioCardOption) => opt.value === value;
    const isOptionDisabled = (opt: RadioCardOption) =>
        Boolean(disabled || opt.disabled);

    const handleChange = (opt: RadioCardOption) => {
        if (isOptionDisabled(opt)) return;
        onValueChange?.(opt.value);
        onChange?.(opt.value);
    };

    const rootClasses = [
        "shadcn-radio-card-group",
        inline && !columns ? "shadcn-radio-card-group--inline" : "",
        columns > 0 ? "shadcn-radio-card-group--grid" : "",
        radioPosition === "end" ? "shadcn-radio-card-group--radio-end" : "",
        className ?? "",
    ]
        .filter(Boolean)
        .join(" ");

    const rootStyle: CSSProperties | undefined =
        columns > 0
            ? { gridTemplateColumns: `repeat(${columns}, minmax(0, 1fr))` }
            : undefined;

    return (
        <div
            className={rootClasses}
            style={rootStyle}
            role="radiogroup"
            aria-label={ariaLabel}
        >
            {normalizedOptions.map((opt) => (
                <label
                    key={String(opt.value)}
                    className={[
                        "shadcn-radio-card",
                        isSelected(opt) ? "is-selected" : "",
                        isOptionDisabled(opt) ? "is-disabled" : "",
                    ]
                        .filter(Boolean)
                        .join(" ")}
                >
                    <input
                        type="radio"
                        className="shadcn-radio-card__input"
                        name={groupName}
                        value={String(opt.value)}
                        checked={isSelected(opt)}
                        disabled={isOptionDisabled(opt)}
                        onChange={() => handleChange(opt)}
                    />

                    <span className="shadcn-radio-card__radio" aria-hidden="true">
                        <span className="shadcn-radio-card__dot" />
                    </span>

                    {opt.icon ? (
                        <span
                            className="shadcn-radio-card__icon"
                            style={{
                                background: opt.iconBg,
                                color: opt.iconColor,
                                border: opt.iconBorder
                                    ? `1px solid ${opt.iconBorder}`
                                    : undefined,
                            }}
                            aria-hidden="true"
                        >
                            <i className={opt.icon} />
                        </span>
                    ) : null}

                    <span className="shadcn-radio-card__content">
                        <span className="shadcn-radio-card__label">{opt.label}</span>
                        {opt.description ? (
                            <span className="shadcn-radio-card__desc">
                                {opt.description}
                            </span>
                        ) : null}
                    </span>

                    {opt.badge ? (
                        <span className="shadcn-radio-card__badge">{opt.badge}</span>
                    ) : null}
                </label>
            ))}
        </div>
    );
}
