// src/angular/spark-grid-empty-state.component.ts
import {
  ChangeDetectionStrategy, Component, EventEmitter, Input, OnChanges, OnInit, Output, SimpleChanges
} from "@angular/core";
import { ShadcnOnboardingPanelComponent } from "./shadcn-onboarding-panel.component";

/**
 * `SparkGridEmptyStateComponent` — Angular port do SFC Vue `SparkGridEmptyState`.
 *
 * Attribute selector num `<div>` (`<div arcanaSparkGridEmptyState>`): mostra o
 * `<ShadcnOnboardingPanel>` só quando a grid terminou de carregar E está genuinamente vazia
 * (sem filtro). Reproduz `.spark-grid-empty-state`, idêntico ao Vue/React.
 *
 * Vue → Angular:
 * - `watch(loading)` que arma `loaded` no 1º flip `true → false` → `ngOnChanges`.
 * - `computed(showPanel)` → getter; `emit('panel-visible')` → `@Output() panelVisible`
 *   (dispara no mount também, espelhando `{ immediate: true }`).
 * - `emit('action')` / `emit('secondary-action')` → `@Output() action` / `secondaryAction`.
 * - slot default (conteúdo real quando NÃO vazio) → `<ng-content>`.
 */
@Component({
  selector: "div[arcanaSparkGridEmptyState]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ShadcnOnboardingPanelComponent],
  host: { "class": "spark-grid-empty-state" },
  template: `
    <div [style.display]="showPanel ? 'none' : null">
      <ng-content></ng-content>
    </div>
    @if (showPanel) {
      <div
        arcanaShadcnOnboardingPanel
        [icon]="icon"
        [title]="title"
        [description]="description"
        [actionLabel]="actionLabel"
        [secondaryActionLabel]="secondaryActionLabel"
        [secondaryActionIcon]="secondaryActionIcon"
        [subHint]="subHint"
        (action)="action.emit()"
        (secondaryAction)="secondaryAction.emit()"
      ></div>
    }
  `
})
export class SparkGridEmptyStateComponent implements OnChanges, OnInit {
  @Input({ required: true }) total!: number;
  @Input({ required: true }) loading!: boolean;
  @Input({ required: true }) filtered!: boolean;
  @Input({ required: true }) icon!: string;
  @Input({ required: true }) title!: string;
  @Input() description = "";
  @Input({ required: true }) actionLabel!: string;
  @Input() secondaryActionLabel = "";
  @Input() secondaryActionIcon = "";
  @Input() subHint = "";

  @Output() action = new EventEmitter<void>();
  @Output() secondaryAction = new EventEmitter<void>();
  @Output() panelVisible = new EventEmitter<boolean>();

  private loaded = false;
  private lastEmitted: boolean | null = null;

  get showPanel(): boolean {
    return this.loaded && !this.loading && this.total === 0 && !this.filtered;
  }

  ngOnInit(): void {
    this.emitPanelVisible();
  }

  ngOnChanges(changes: SimpleChanges): void {
    const l = changes["loading"];
    if (l && l.previousValue === true && l.currentValue === false) {
      this.loaded = true;
    }
    this.emitPanelVisible();
  }

  private emitPanelVisible(): void {
    const visible = this.showPanel;
    if (this.lastEmitted !== visible) {
      this.lastEmitted = visible;
      // Deferido pra fora do ciclo de CD atual: emitir um Output síncrono durante
      // `ngOnChanges`/`ngOnInit` dispara ExpressionChangedAfterItHasBeenChecked no
      // dev-mode se um handler do pai reagir. `queueMicrotask` desacopla a notificação.
      queueMicrotask(() => this.panelVisible.emit(visible));
    }
  }
}

// src/react/SparkGridEmptyState.tsx
import { useEffect, useRef, useState, type ReactNode } from "react";
import { ShadcnOnboardingPanel } from "./ShadcnOnboardingPanel";

/**
 * `<SparkGridEmptyState>` — React port do SFC Vue. Mostra o `<ShadcnOnboardingPanel>`
 * apenas quando a grid terminou de carregar e está genuinamente vazia (sem filtro).
 * Markup/classes `spark-grid-empty-state` idênticos ao SFC.
 *
 * Equivalências Vue → React:
 * - `watch(loading)` que arma `loaded` no primeiro `true → false` → `useEffect` + ref
 * - `computed(showPanel)` → derivação local
 * - `emit('panel-visible')` → `onPanelVisible` (disparado quando o painel aparece/some)
 * - `emit('action'|'secondary-action')` → `onAction` / `onSecondaryAction`
 * - slot default (conteúdo real quando NÃO vazio) → `children`
 */
export interface SparkGridEmptyStateProps {
    total: number;
    loading: boolean;
    filtered: boolean;
    icon: string;
    title: string;
    description?: string;
    actionLabel: string;
    secondaryActionLabel?: string;
    secondaryActionIcon?: string;
    subHint?: string;
    children?: ReactNode;
    onAction?: () => void;
    onSecondaryAction?: () => void;
    onPanelVisible?: (visible: boolean) => void;
}

export function SparkGridEmptyState({
    total,
    loading,
    filtered,
    icon,
    title,
    description = "",
    actionLabel,
    secondaryActionLabel = "",
    secondaryActionIcon = "",
    subHint = "",
    children,
    onAction,
    onSecondaryAction,
    onPanelVisible,
}: SparkGridEmptyStateProps) {
    // Arma `loaded` no primeiro flip `loading: true → false` (mesma lógica do watch do SFC).
    const [loaded, setLoaded] = useState(false);
    const prevLoadingRef = useRef(loading);
    useEffect(() => {
        if (prevLoadingRef.current === true && loading === false) {
            setLoaded(true);
        }
        prevLoadingRef.current = loading;
    }, [loading]);

    const showPanel = loaded && !loading && total === 0 && !filtered;

    // Notifica o pai quando o painel aparece/some (immediate: true no SFC → dispara no mount também).
    const prevShowRef = useRef<boolean | null>(null);
    useEffect(() => {
        if (prevShowRef.current !== showPanel) {
            prevShowRef.current = showPanel;
            onPanelVisible?.(showPanel);
        }
    }, [showPanel, onPanelVisible]);

    return (
        <div className="spark-grid-empty-state">
            <div style={{ display: showPanel ? "none" : undefined }}>{children}</div>
            {showPanel && (
                <ShadcnOnboardingPanel
                    icon={icon}
                    title={title}
                    description={description}
                    actionLabel={actionLabel}
                    secondaryActionLabel={secondaryActionLabel}
                    secondaryActionIcon={secondaryActionIcon}
                    subHint={subHint}
                    onAction={() => onAction?.()}
                    onSecondaryAction={() => onSecondaryAction?.()}
                />
            )}
        </div>
    );
}
